### ISSUE TITLE
unknown Conversion failed!

### ISSUE THREAD

**Issue by DJPlaya** [k4yt3x/video2x#116]
After i had the same bug as #109 i followed your Suggestion and switched the Engine, sadly this also failed for me and ime unsure why.

Some Data about my Machine:
Win 10 x64 1809
16GB DDR3 Memory
Everything should be Up-To-Date on the stable Branch

GPU Driver
```
Radeon Settings Version - 2019.0415.2324.42127
View Release Notes - https://www.amd.com/en/support/kb/release-notes/rn-rad-win-19-4-3
Driver Packaging Version - 18.50.31.09-190415a-341662E-RadeonSoftwareAdrenalin2019
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1634
Direct3D® Version - 9.14.10.01377
OpenGL® Version - 25.20.15000.13547
OpenCL™ Version - 10.0.2766.5
AMD Mantle Version - 9.1.10.0295
AMD Mantle API Version - 102400
AMD Audio Driver Version - 10.0.1.7
Vulkan™ Driver Version - 2.0.78
Vulkan™ API Version - 1.1.101
```

GPU Hardware:
```
Graphics Card Manufacturer - Powered by AMD
Graphics Chipset - AMD Radeon (TM) R9 390 Series
Device ID - 67B1
Vendor ID - 1002
SubSystem ID - 9390
SubSystem Vendor ID - 1682
Revision ID - 80
Bus Type - PCI Express 3.0
Current Bus Settings - PCI Express 3.0 x16
BIOS Version - 015.049.000.000
BIOS Part Number - 113-GRENADA_PRO_C671_D5_8GB_HY_W81
BIOS Date - 2015/06/03 04:37
Memory Size - 8192 MB
Memory Type - GDDR5
Memory Clock - 1500 MHz
Core Clock - 1015 MHz
Total Memory Bandwidth - 384 GByte/s
Memory Bit Rate - 6.00 Gbps
2D Driver File Path - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0000
OpenGL® API Version - 4.6
OpenCL™ API Version - 2.0
```

I used the Following CMD Line:
video2x.exe -d waifu2x_converter -m gpu -t 1 -i "C:\Users\Playa\Desktop\Alfred.flv" -o C:\Users\Playa\Desktop\123.flv -r 2.7

The Stack and some Log Data:
```
  Metadata:
    hasKeyframes    : true
    hasVideo        : true
    canSeekToEnd    : false
    datasize        : 4175027
    lasttimestamp   : 90
    audiosize       : 758843
    hasAudio        : true
    audiodelay      : 0
    videosize       : 3415238
    metadatacreator : MyVideo // http://www.myvideo.de
    lastkeyframetimestamp: 88
    hasMetadata     : true
    hasCuePoints    : false
    encoder         : Lavf58.26.101
    Stream #0:0: Video: png, rgb24, 400x300, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.47.106 png
[image2 @ 0000023f62627d40] Could not get frame filename number 2 from pattern 'C:\Users\Playa\AppData\Local\Temp\video2x\tmp0to372nu\extracted_.png'. Use '-frames:v 1' for a single image, or '-update'
 option, or use a pattern such as %03d within the filename.
av_interleaved_write_frame(): Invalid argument
frame=    6 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.08 bitrate=N/A speed=2.16x
video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 318, in <module>
  File "upscaler.py", line 263, in run
  File "ffmpeg.py", line 91, in extract_frames
  File "ffmpeg.py", line 212, in _execute
  File "subprocess.py", line 487, in run
```

**Comment by k4yt3x** [comment]
> File "ffmpeg.py", line 91, in extract_frames

Which version of Video2X are you using?
The line numbers don't seem to match up with the newest version.

**Comment by DJPlaya** [comment]
The latest, 2.7.1

**Comment by k4yt3x** [comment]
That is not the latest
