### ISSUE TITLE
AttributeError: module 'avalon_framework' has no attribute 'FM'

### ISSUE THREAD

**Issue by wuast94** [K4YT3X/video2x#12]
I get error:
```
               Video2X Video Enlarger
Traceback (most recent call last):
  File "video2x.py", line 175, in <module>
    print_logo()
  File "video2x.py", line 83, in print_logo
    '    Version ' + VERSION + '\n' + avalon.FM.RST)
AttributeError: module 'avalon_framework' has no attribute 'FM'
```

**Comment by K4YT3X** [comment]
@wuast94 Thanks for the issue and sorry about the error. The framework was update a day ago, and I haven't updated all the programs that are using this framework yet. I'll do it right now.

**Comment by K4YT3X** [comment]
Alright the issue should be fixed by now.
