### ISSUE TITLE
Is there a way around the libavcodec 59 dependency?

### ISSUE THREAD

**Issue by codecowboy** [K4YT3X/video2x#1242]
I have build the latest ffmpeg on Ubuntu 22.04 LTS and get the following when trying to install video2x

```

sudo apt install ./video2x-linux-ubuntu2204-amd64.deb  # I also tried with -f flag
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'video2x' instead of './video2x-linux-ubuntu2204-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ffmpeg : Depends: libavcodec59 (>= 7:5.0)
          Depends: libavfilter8 (>= 7:5.1)
          Depends: libavformat59 (>= 7:5.1)
 libavdevice59 : Depends: libavcodec59 (>= 7:5.0)
                 Depends: libavfilter8 (>= 7:5.1)
                 Depends: libavformat59 (= 7:5.1.6-0ubuntu1~22.04.sav1)
                 Depends: libsndio7 (>= 1.8.1) but it is not installable

E: Unable to correct problems, you have held broken packages.
```
I got the same error with the ffmpeg version in the ubuntu repo. Is there a way around this without building ffmpeg again?

ffmpeg version:

```
ffmpeg version N-117917-gac3f69a4b9 Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: 
libavutil      59. 47.101 / 59. 47.101
libavcodec     61. 26.100 / 61. 26.100
libavformat    61.  9.100 / 61.  9.100
libavdevice    61.  4.100 / 61.  4.100
libavfilter    10.  6.101 / 10.  6.101
libswscale      8. 12.100 /  8. 12.100
libswresample   5.  4.100 /  5.  4.100
```

**Comment by k4yt3x** [comment]
You have Ubuntu 24.04 but downloaded the 22.04 deb package?

**Comment by k4yt3x** [comment]
Oh right, for Ubuntu 22.04 you'll also need the Ubuntu Handbook PPA and install FFmpeg 7. The FFmpeg on Ubuntu 22 is just too old and won't work. Try this:

```bash
sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7
sudo apt-get update
sudo apt-get install ffmpeg
```

Then install video2x again.

**Comment by k4yt3x** [comment]
I admit it's not very well documented. I'll add more docs for it later. The 22.04 version is primarily built for use on Colab, and libplacbeo has some issues with the Ubuntu Handbook build (it can't find the libplacebo filter).

If your situation permits, I'd recommend using this on Ubuntu 24.04. The newer officially built FFmpeg has no problems at all.

**Comment by k4yt3x** [comment]
I'd say don't try building it on Ubuntu anymore, try the FFmpeg from the PPA or just Docker. I'm pretty sure the Docker would at least work.

**Comment by k4yt3x** [comment]
Yes RealESRGAN works when I test it on Colab which is Ubuntu 22.04. Just use the `realesrgan-plus` model. FYI upscaling real-life footage is a lot slower than animation.

**Comment by k4yt3x** [comment]
I believe the live footage model is slower because it's more complex than anime, so yeah the nature of the video. The quickest way you can check if you're using GPU is to run `video2x --list-gpus` to see if the GPU is recognized. If it is, you'll see something like:

```
0. NVIDIA RTX A6000
        Type: Discrete GPU
        Vulkan API Version: 1.3.289
        Driver Version: 565.228.64
```

If you see your GPU's name, your GPU is recognized and it's fine. If the only one showing up says LLVM, e.g., something like llvmpipe, then it's using the CPU.

**Comment by k4yt3x** [comment]
Fair enough, Vulkan is doing nothing good to my sanity here either.

**Comment by k4yt3x** [comment]
I'll try to do a flatpak when I finish 6.2.0. Maybe that'll work better. You and anyone else that's having issues with this can subscribe to #1224 to get notified

**Comment by loretoparisi** [comment]
> sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7
> sudo apt-get update
> sudo apt-get install ffmpeg

I'm still getting

```
[Thu, 27 Feb 2025 14:47:38] DEBUG Loading FFmpeg6
[Thu, 27 Feb 2025 14:47:38] DEBUG Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/home/coder/.local/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/coder/.local/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/coder/.local/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/coder/.local/lib/python3.10/site-packages/torch/_ops.py", line 1357, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.58: cannot open shared object file: No such file or directory
[Thu, 27 Feb 2025 14:47:38] DEBUG Loading FFmpeg5
[Thu, 27 Feb 2025 14:47:38] DEBUG Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "/home/coder/.local/lib/python3.10/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/coder/.local/lib/python3.10/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/home/coder/.local/lib/python3.10/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/home/coder/.local/lib/python3.10/site-packages/torch/_ops.py", line 1357, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavutil.so.57: cannot open shared object file: No such file or directory
[Thu, 27 Feb 2025 14:47:38] DEBUG Loading FFmpeg4
[Thu, 27 Feb 2025 14:47:38] DEBUG Successfully loaded FFmpeg4
```

**Comment by k4yt3x** [comment]
@loretoparisi I'm a bit confused. Why are you using Python?
