### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by wuast94** [K4YT3X/video2x#13]
an i get the next error :D 

> "C:/Users/Marcd/Desktop/videoenlarger/ffmpeg-4.0.2/ffmpeg.exe" -i "D:\S01E01o.avi" C:\Users\Marcd\Desktop\videoenlarger\video2x-master\frames\extracted_%0d.png -y
[!] ERROR: An exception occurred
Traceback (most recent call last):
  File "video2x.py", line 207, in <module>
    video2x()
  File "video2x.py", line 144, in video2x
    fm.extract_frames(args.video, FRAMES)
  File "C:\Users\Marcd\Desktop\videoenlarger\video2x-master\ffmpeg.py", line 41, in extract_frames
    subprocess.call(execute)
  File "C:\Users\Marcd\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 317, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Marcd\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Marcd\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by wuast94** [comment]
found the error. im loaded the wrong ffmpeg binarys

**Comment by K4YT3X** [comment]
@wuast94 so is it resolved right now?

**Comment by wuast94** [comment]
Yes you can close it :)
