### ISSUE TITLE
Upscaling Completes at 0%

### ISSUE THREAD

**Issue by Criuion** [k4yt3x/video2x#132]
## Environment Information

|Module|Version|
|-|-|
|`video2x`| 2.9.0-win32-full |
|`ffmpeg`| ffmpeg-20190729-43891ea-win64-static |
|`waifu2x-caffe`| ver 1.2.0.2 |
|`waifu2x-converter-cpp`| Not Available |

## Symptom

First time using Video2x it worked with no problem, ever since then it won't upscale and says it's completed upscaling in the command window.  It just sits there doing nothing and have to close it manually, which leaves all the temp folders undeleted.

Here is the current settings i am using (Have tried multiple others):
![image](https://user-images.githubusercontent.com/53840981/62585340-3eddf800-b8b0-11e9-86d6-c75792521f2a.png)

OS: Windows 10 64 Bit
GPU: AMD Radeon VII 
Driver: 19.7.5 (Also used older driver 19.7.3)

## Screenshots or Error Messages

> 2019-08-07 00:46:53.951102 [+] INFO: Extracted frames are being saved to: C:\Users\Criuion.Criuion-PC\AppData\Local\Temp\video2x\tmppqln207b
2019-08-07 00:46:53.951102 [+] INFO: Upscaled frames are being saved to: C:\Users\Criuion.Criuion-PC\AppData\Local\Temp\video2x\tmp4z25lo13
2019-08-07 00:46:53.951102 [+] INFO: Executing: [WindowsPath('C:/video2x-2.9.0-win32-full/dependencies/ffmpeg-latest-win64-static/bin/ffmpeg.exe'), '-i', WindowsPath('C:/Users/Criuion.Criuion-PC/Desktop/Test.mp4'), '-pix_fmt', 'rgba64be', WindowsPath('C:/Users/Criuion.Criuion-PC/AppData/Local/Temp/video2x/tmppqln207b/extracted_%0d.PNG'), '-hwaccel', 'auto', '-y']
ffmpeg version N-94405-g43891ea8ab Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190716
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 32.100 / 56. 32.100
  libavcodec     58. 55.100 / 58. 55.100
  libavformat    58. 30.100 / 58. 30.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.100 /  7. 58.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Trailing options were found on the commandline.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Criuion.Criuion-PC\Desktop\Test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2012-09-18T23:42:05.000000Z
  Duration: 00:03:23.71, start: 0.000000, bitrate: 1486 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 720x480 [SAR 32:27 DAR 16:9], 1294 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2012-09-18T22:32:07.000000Z
      handler_name    : Video
      encoder         : AVC Coding
    Stream #0:1(jpn): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      creation_time   : 2012-09-18T23:42:06.000000Z
      handler_name    : Main
    Side data:
      audio service type: main
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
[swscaler @ 0000024301cef080] No accelerated colorspace conversion found from yuv420p to rgba64be.
Output #0, image2, to 'C:\Users\Criuion.Criuion-PC\AppData\Local\Temp\video2x\tmppqln207b\extracted_%0d.PNG':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.30.100
    Stream #0:0(und): Video: png, rgba64be, 720x480 [SAR 32:27 DAR 16:9], q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2012-09-18T22:32:07.000000Z
      handler_name    : Video
      encoder         : Lavc58.55.100 png
frame= 4874 fps= 26 q=-0.0 Lsize=N/A time=00:03:23.28 bitrate=N/A speed=1.06x
video:6291260kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2019-08-07 00:50:05.093746 [+] INFO: Executing: C:\video2x-2.9.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i C:\Users\Criuion.Criuion-PC\Desktop\Test.mp4
2019-08-07 00:50:05.312444 [+] INFO: Executing: C:\video2x-2.9.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -pix_fmts
2019-08-07 00:50:05.343687 [+] INFO: {'yuv420p': 12, 'yuyv422': 16, 'rgb24': 24, 'bgr24': 24, 'yuv422p': 16, 'yuv444p': 24, 'yuv410p': 9, 'yuv411p': 12, 'gray': 8, 'monow': 1, 'monob': 1, 'pal8': 8, 'yuvj420p': 12, 'yuvj422p': 16, 'yuvj444p': 24, 'uyvy422': 16, 'uyyvyy411': 12, 'bgr8': 8, 'bgr4': 4, 'bgr4_byte': 4, 'rgb8': 8, 'rgb4': 4, 'rgb4_byte': 4, 'nv12': 12, 'nv21': 12, 'argb': 32, 'rgba': 32, 'abgr': 32, 'bgra': 32, 'gray16be': 16, 'gray16le': 16, 'yuv440p': 16, 'yuvj440p': 16, 'yuva420p': 20, 'rgb48be': 48, 'rgb48le': 48, 'rgb565be': 16, 'rgb565le': 16, 'rgb555be': 15, 'rgb555le': 15, 'bgr565be': 16, 'bgr565le': 16, 'bgr555be': 15, 'bgr555le': 15, 'vaapi_moco': 0, 'vaapi_idct': 0, 'vaapi_vld': 0, 'yuv420p16le': 24, 'yuv420p16be': 24, 'yuv422p16le': 32, 'yuv422p16be': 32, 'yuv444p16le': 48, 'yuv444p16be': 48, 'dxva2_vld': 0, 'rgb444le': 12, 'rgb444be': 12, 'bgr444le': 12, 'bgr444be': 12, 'ya8': 16, 'bgr48be': 48, 'bgr48le': 48, 'yuv420p9be': 13, 'yuv420p9le': 13, 'yuv420p10be': 15, 'yuv420p10le': 15, 'yuv422p10be': 20, 'yuv422p10le': 20, 'yuv444p9be': 27, 'yuv444p9le': 27, 'yuv444p10be': 30, 'yuv444p10le': 30, 'yuv422p9be': 18, 'yuv422p9le': 18, 'gbrp': 24, 'gbrp9be': 27, 'gbrp9le': 27, 'gbrp10be': 30, 'gbrp10le': 30, 'gbrp16be': 48, 'gbrp16le': 48, 'yuva422p': 24, 'yuva444p': 32, 'yuva420p9be': 22, 'yuva420p9le': 22, 'yuva422p9be': 27, 'yuva422p9le': 27, 'yuva444p9be': 36, 'yuva444p9le': 36, 'yuva420p10be': 25, 'yuva420p10le': 25, 'yuva422p10be': 30, 'yuva422p10le': 30, 'yuva444p10be': 40, 'yuva444p10le': 40, 'yuva420p16be': 40, 'yuva420p16le': 40, 'yuva422p16be': 48, 'yuva422p16le': 48, 'yuva444p16be': 64, 'yuva444p16le': 64, 'vdpau': 0, 'xyz12le': 36, 'xyz12be': 36, 'nv16': 16, 'nv20le': 20, 'nv20be': 20, 'rgba64be': 64, 'rgba64le': 64, 'bgra64be': 64, 'bgra64le': 64, 'yvyu422': 16, 'ya16be': 32, 'ya16le': 32, 'gbrap': 32, 'gbrap16be': 64, 'gbrap16le': 64, 'qsv': 0, 'mmal': 0, 'd3d11va_vld': 0, 'cuda': 0, '0rgb': 24, 'rgb0': 24, '0bgr': 24, 'bgr0': 24, 'yuv420p12be': 18, 'yuv420p12le': 18, 'yuv420p14be': 21, 'yuv420p14le': 21, 'yuv422p12be': 24, 'yuv422p12le': 24, 'yuv422p14be': 28, 'yuv422p14le': 28, 'yuv444p12be': 36, 'yuv444p12le': 36, 'yuv444p14be': 42, 'yuv444p14le': 42, 'gbrp12be': 36, 'gbrp12le': 36, 'gbrp14be': 42, 'gbrp14le': 42, 'yuvj411p': 12, 'bayer_bggr8': 8, 'bayer_rggb8': 8, 'bayer_gbrg8': 8, 'bayer_grbg8': 8, 'bayer_bggr16le': 16, 'bayer_bggr16be': 16, 'bayer_rggb16le': 16, 'bayer_rggb16be': 16, 'bayer_gbrg16le': 16, 'bayer_gbrg16be': 16, 'bayer_grbg16le': 16, 'bayer_grbg16be': 16, 'xvmc': 0, 'yuv440p10le': 20, 'yuv440p10be': 20, 'yuv440p12le': 24, 'yuv440p12be': 24, 'ayuv64le': 64, 'ayuv64be': 64, 'videotoolbox_vld': 0, 'p010le': 15, 'p010be': 15, 'gbrap12be': 48, 'gbrap12le': 48, 'gbrap10be': 40, 'gbrap10le': 40, 'mediacodec': 0, 'gray12be': 12, 'gray12le': 12, 'gray10be': 10, 'gray10le': 10, 'p016le': 24, 'p016be': 24, 'd3d11': 0, 'gray9be': 9, 'gray9le': 9, 'gbrpf32be': 96, 'gbrpf32le': 96, 'gbrapf32be': 128, 'gbrapf32le': 128, 'drm_prime': 0, 'opencl': 0, 'gray14be': 14, 'gray14le': 14, 'grayf32be': 32, 'grayf32le': 32, 'yuva422p12be': 36, 'yuva422p12le': 36, 'yuva444p12be': 48, 'yuva444p12le': 48, 'nv24': 24, 'nv42': 24}
[+] INFO: Framerate: 23.976023976023978
[+] INFO: Starting to upscale extracted images
2019-08-07 00:50:05.343687 [+] INFO: [upscaler] Thread Thread-1 started
2019-08-07 00:50:05.343687 [+] INFO: Executing: ['C:\\video2x-2.9.0-win32-full\\dependencies\\waifu2x-converter-cpp\\waifu2x-converter-cpp.exe', '--output-format', 'PNG', '--jobs', '1', '--model-dir', 'C:\\video2x-2.9.0-win32-full\\dependencies\\waifu2x-converter-cpp\\models_rgb', '--scale-ratio', '0.0', '--noise-level', '3', '--mode', 'noise-scale', '--silent', '--output', 'C:\\Users\\Criuion.Criuion-PC\\AppData\\Local\\Temp\\video2x\\tmp4z25lo13', '--input', 'C:\\Users\\Criuion.Criuion-PC\\AppData\\Local\\Temp\\video2x\\tmppqln207b']
Upscaling Progress:   0%|                                                                                                                                                | 0/4874 [00:00<?, ?it/s]OpenCL: gfx906
We're going to be operating in a directory. dir:C:\Users\Criuion.Criuion-PC\AppData\Local\Temp\video2x\tmppqln207b
Upscaling Progress:   0%|                                                                                                                                                | 0/4874 [00:01<?, ?it/s]
[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
2019-08-07 00:50:07.390081 [+] INFO: Executing: [WindowsPath('C:/video2x-2.9.0-win32-full/dependencies/ffmpeg-latest-win64-static/bin/ffmpeg.exe'), '-r', '23.976023976023978', '-s', '2559x1440', '-f', 'image2', '-pix_fmt', 'yuv420p', '-i', WindowsPath('C:/Users/Criuion.Criuion-PC/AppData/Local/Temp/video2x/tmp4z25lo13/extracted_%d.PNG'), '-vcodec', 'libx264', '-crf', '17', '-pix_fmt', 'yuv420p', '-y', WindowsPath('C:/Users/Criuion.Criuion-PC/AppData/Local/Temp/video2x/tmp4z25lo13/no_audio.mp4')]
ffmpeg version N-94405-g43891ea8ab Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190716
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 32.100 / 56. 32.100
  libavcodec     58. 55.100 / 58. 55.100
  libavformat    58. 30.100 / 58. 30.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.100 /  7. 58.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[image2 @ 00000231205eaec0] Could find no file with path 'C:\Users\Criuion.Criuion-PC\AppData\Local\Temp\video2x\tmp4z25lo13\extracted_%d.PNG' and index in the range 0-4
C:\Users\Criuion.Criuion-PC\AppData\Local\Temp\video2x\tmp4z25lo13\extracted_%d.PNG: No such file or directory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 288, in _upscale
  File "upscaler.py", line 351, in run
  File "ffmpeg.py", line 184, in convert_video
  File "ffmpeg.py", line 285, in _execute
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\video2x-2.9.0-win32-full\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-r', '23.976023976023978', '-s', '2559x1440', '-f', 'image2', '-pix_fmt', 'yuv420p', '-i', 'C:\\Users\\Criuion.Criuion-PC\\AppData\\Local\\Temp\\video2x\\tmp4z25lo13\\extracted_%d.PNG', '-vcodec', 'libx264', '-crf', '17', '-pix_fmt', 'yuv420p', '-y', 'C:\\Users\\Criuion.Criuion-PC\\AppData\\Local\\Temp\\video2x\\tmp4z25lo13\\no_audio.mp4']' returned non-zero exit status 1.

**Comment by Criuion** [comment]
I am sure anyone that knows what the problem is screaming at their screen as soon as they read my OP, but i had no clue to the restrictions for the upscalers.  Only reason i figured it out was i went back to 2.7.1 and used the command window and it told me of the limitations.

If you would kindly please add some kind of warning in the GUI 2.9.1 version about these limitations, so plebs like me don't think something is broke and post bug reports.

**Comment by k4yt3x** [comment]
This is a known issue and there has been discussions around it in the telegram group.
I think the newest python updates should have fixed it. Let me confirm

**Comment by k4yt3x** [comment]
It's working fine for me.

![2019-08-07_22-02-56](https://user-images.githubusercontent.com/21986859/62669881-d27ef980-b980-11e9-8661-6d12e1b1838b.png)

**Comment by erdog** [comment]
What was the actual problem? I'm having the same issue

**Comment by k4yt3x** [comment]
> What was the actual problem? I'm having the same issue

I don't quite remember, but if you're having similar issues:

1. Make sure your software is up-to-date
1. Make sure you have run the setup script
1. Make sure you have installed the video drivers
1. If all the above are checked and it still doesn't work, open a new issue
