### ISSUE TITLE
FFmpeg returned non-zero exit status 1

### ISSUE THREAD

**Issue by coderynx** [k4yt3x/video2x#149]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|2.10.0|
|`FFmpeg`| N-95015-gba24b24aab|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

After extracting all the frames from a video it throws an exception. I've got everything up to date (including Python and NVIDIA drivers).

## Error Messages
```
C:\Users\simon\Desktop\video2x-master\bin>python video2x_gui.py
2019-09-22 13:24:36.525199 [+] INFO: Extracted frames are being saved to: D:\video2x\cache\tmp13z4ab3o
2019-09-22 13:24:36.526174 [+] INFO: Upscaled frames are being saved to: D:\video2x\cache\tmp0vhbapj6
2019-09-22 13:24:36.527189 [+] INFO: Executing: ['C:\\Users\\simon\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-hwaccel', 'auto', '-y', '-i', 'C:\\Users\\simon\\Desktop\\sample_input.mp4', '-pix_fmt', 'rgba64be', 'D:\\video2x\\cache\\tmp13z4ab3o\\extracted_%0d.PNG']
ffmpeg version N-95015-gba24b24aab Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20190918
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 58.101 / 58. 58.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.102 /  7. 58.102
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\simon\Desktop\sample_input.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2019-02-08T01:47:01.000000Z
  Duration: 00:00:19.07, start: 0.000000, bitrate: 1997 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 426x240, 1659 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
[h264 @ 0000016a434c6140] Using auto hwaccel type dxva2 with new default device.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'D:\video2x\cache\tmp13z4ab3o\extracted_%0d.PNG':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    encoder         : Lavf58.33.100
    Stream #0:0(eng): Video: png, rgba64be, 426x240, q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2019-02-08T01:47:01.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : Lavc58.58.101 png
frame=  456 fps= 25 q=-0.0 Lsize=N/A time=00:00:19.01 bitrate=N/A speed=1.04x
video:237173kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "video2x_gui.py", line 321, in _upscale
    self.upscaler.run()
  File "C:\Users\simon\Desktop\video2x-master\bin\upscaler.py", line 314, in run
    fm.extract_frames(self.input_video, self.extracted_frames)
  File "C:\Users\simon\Desktop\video2x-master\bin\ffmpeg.py", line 134, in extract_frames
    self._execute(execute)
  File "C:\Users\simon\Desktop\video2x-master\bin\ffmpeg.py", line 287, in _execute
    return subprocess.run(execute, shell=True, check=True).returncode
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\simon\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-hwaccel', 'auto', '-y', '-i', 'C:\\Users\\simon\\Desktop\\sample_input.mp4', '-pix_fmt', 'rgba64be', 'D:\\video2x\\cache\\tmp13z4ab3o\\extracted_%0d.PNG']' returned non-zero exit status 1.
```

**Comment by k4yt3x** [comment]
I can't see were FFmpeg failed.
Can you provide a screenshot? or do you see anything highlighted/colored red in the terminal?

**Comment by coderynx** [comment]
![Cattura](https://user-images.githubusercontent.com/23385887/65393512-b93fda00-dd81-11e9-846c-242912975a05.PNG)

Here's the screenshot. There's nothing highlighted red.

**Comment by k4yt3x** [comment]
That's strange. FFmpeg's return code suggests that there's an error, but I don't see any error messages in its output.
What happens when you disable hwaccel in video2x.json?

**Comment by coderynx** [comment]
Nothing different. It gives me the same error.

**Comment by k4yt3x** [comment]
In which case then I can't locate where the problem is.

**Comment by coderynx** [comment]
Ok I managed to get it to work by adding an exception pass in the ffmpeg.py file. It's not the cleanest way but it works. The strange thing is that FFmpeg extracts all the frames without problems, in fact the upscaling process ends successfully.

**Comment by k4yt3x** [comment]
That's strange... why does it return a non-zero code then.
Well as long as it works for you I guess.
