### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Trentflix** [k4yt3x/video2x#154]
Using 2.10.0, all of the Waifu2x drivers work fine but with Anime4k when I attempt the same thing I get an error message after the PNG image creation process:

2019-10-05 15:05:03.147046 [+] INFO: Killing upscaled image cleaner
Upscaling Progress:   0%|                                                                     | 0/2881 [00:01<?, ?it/s][!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "C:\Users\Home\Downloads\video2x-2.10.0-win32-light\bin\video2x.py", line 403, in <module>
    upscaler.run()
  File "C:\Users\Home\Downloads\video2x-2.10.0-win32-light\bin\upscaler.py", line 357, in run
    self._upscale_frames()
  File "C:\Users\Home\Downloads\video2x-2.10.0-win32-light\bin\upscaler.py", line 293, in _upscale_frames
    raise(self.upscaler_exceptions[0])
  File "C:\Users\Home\Downloads\video2x-2.10.0-win32-light\bin\anime4k.py", line 82, in upscale
    return_value += subprocess.run(execute, check=True).returncode
  File "C:\Python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Upscaling Progress:   0%|                                                                     | 0/2881 [00:02<?, ?it/s]

**Comment by k4yt3x** [comment]
Did you install JDK 12?

**Comment by Trentflix** [comment]
No, I guess I missed that in the requirements or assumed it would be auto-downloaded like everything else. That worked though, apologies and thank you!

**Comment by k4yt3x** [comment]
@Trentflix The Java requirement is mentioned in Anime4K's documentation, but I should have mentioned it here as well. Though I still wasn't able to find time to write documentations for it.

**Comment by billxsand** [comment]
Hey, I installed JDK 12, restarted, but I am still getting this error. Any ideas?

https://pastebin.com/c538riPz

**Comment by k4yt3x** [comment]
@billxsand check if the file `C:\\Program Files\\Java\\jdk-12.0.2\\bin\\java.exe` exists

**Comment by billxsand** [comment]
Oops, I had accidentally installed 13.something instead of 12.0.2. Thank you!

**Comment by 54724531** [comment]
Appreciate y'all, didn't have to bother anyone and I found my solution here! Put ya Pipes Up!
