### ISSUE TITLE
xception in thread Thread-1:

### ISSUE THREAD

**Issue by HokutoShinken** [k4yt3x/video2x#156]
Hi again. 

An error pops out when Video2x starts upscaling the video file.
Here's the log:

xception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 288, in _upscale
  File "upscaler.py", line 344, in run
  File "upscaler.py", line 280, in _upscale_frames
  File "waifu2x_caffe.py", line 88, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\_-H-_\\Desktop\\video2x-2.9.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '4.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmpxeq_w41g\\0', '--output_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmpjzhfjjm6']' returned non-zero exit status 1.

**Comment by k4yt3x** [comment]
2.9.0 is outdated. Try to see if the problem still exists in 2.10.0.

**Comment by HokutoShinken** [comment]
Hi, yes. The problem persists in 2.10.0
Here's the log

Upscaling Progress:   0%|                                                                     | 0/3480 [00:02<?, ?it/s] 変換変変換換にに失失敗敗ししたたフファァイイルルががあありりにまますす

失敗したファイルがあり変ま換すに
Upscaling Progress:   0%|                                                                     | 0/3480 [00:03<?, ?it/s] したファイルがあります
2019-10-07 17:54:49.971264 [+] INFO: Killing upscaled image cleaner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 321, in _upscale
  File "upscaler.py", line 357, in run
  File "upscaler.py", line 293, in _upscale_frames
  File "waifu2x_caffe.py", line 88, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\_-H-_\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '4.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmpn4yt8om5\\3', '--output_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmpilsb2jtj']' returned non-zero exit status 1.

**Comment by HokutoShinken** [comment]
Tried changing the video codec th H264 just incase it was a problem with the video codec, but does still the same. 

I leave here the log

19-10-07 18:10:14.419994 [+] INFO: Extracted frames are being saved to: C:\Users\_-H-_\AppData\Local\Temp\video2x\tmp_hm4dgq3
2019-10-07 18:10:14.475238 [+] INFO: Upscaled frames are being saved to: C:\Users\_-H-_\AppData\Local\Temp\video2x\tmp6oedpwgp
2019-10-07 18:10:14.477159 [+] INFO: Executing: ['C:\\Users\\_-H-_\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-hwaccel', 'auto', '-y', '-i', 'C:\\Users\\_-H-_\\Desktop\\Op.avi', '-pix_fmt', 'rgba64be', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp_hm4dgq3\\extracted_%0d.PNG']
ffmpeg version git-2019-10-06-66d45af Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191005
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.101 / 58. 59.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 62.100 /  7. 62.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, avi, from 'C:\Users\_-H-_\Desktop\Op.avi':
  Metadata:
    encoder         : Lavf57.41.100
  Duration: 00:01:56.00, start: 0.000000, bitrate: 391 kb/s
    Stream #0:0: Video: h264 (High) (H264 / 0x34363248), yuv420p(progressive), 488x272 [SAR 544:549 DAR 16:9], 385 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc
[h264 @ 000001aa6475c6c0] Using auto hwaccel type dxva2 with new default device.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
[AVHWFramesContext @ 000001aa6651ce00] Could not create the surfaces
[AVHWFramesContext @ 000001aa6651ce00] Error creating an internal frame pool
[h264 @ 000001aa6478ff00] Failed setup for format dxva2_vld: hwaccel initialisation returned error.
[swscaler @ 000001aa6d389000] No accelerated colorspace conversion found from yuv420p to rgba64be.
Output #0, image2, to 'C:\Users\_-H-_\AppData\Local\Temp\video2x\tmp_hm4dgq3\extracted_%0d.PNG':
  Metadata:
    encoder         : Lavf58.33.100
    Stream #0:0: Video: png, rgba64be, 488x272 [SAR 544:549 DAR 16:9], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.59.101 png
frame= 3480 fps= 11 q=-0.0 Lsize=N/A time=00:01:56.06 bitrate=N/A speed=0.366x
video:1894812kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2019-10-07 18:15:32.886466 [+] INFO: Executing: C:\Users\_-H-_\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i C:\Users\_-H-_\Desktop\Op.avi
2019-10-07 18:15:34.650112 [+] INFO: Executing: C:\Users\_-H-_\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -pix_fmts
2019-10-07 18:15:35.799988 [+] INFO: {'yuv420p': 12, 'yuyv422': 16, 'rgb24': 24, 'bgr24': 24, 'yuv422p': 16, 'yuv444p': 24, 'yuv410p': 9, 'yuv411p': 12, 'gray': 8, 'monow': 1, 'monob': 1, 'pal8': 8, 'yuvj420p': 12, 'yuvj422p': 16, 'yuvj444p': 24, 'uyvy422': 16, 'uyyvyy411': 12, 'bgr8': 8, 'bgr4': 4, 'bgr4_byte': 4, 'rgb8': 8, 'rgb4': 4, 'rgb4_byte': 4, 'nv12': 12, 'nv21': 12, 'argb': 32, 'rgba': 32, 'abgr': 32, 'bgra': 32, 'gray16be': 16, 'gray16le': 16, 'yuv440p': 16, 'yuvj440p': 16, 'yuva420p': 20, 'rgb48be': 48, 'rgb48le': 48, 'rgb565be': 16, 'rgb565le': 16, 'rgb555be': 15, 'rgb555le': 15, 'bgr565be': 16, 'bgr565le': 16, 'bgr555be': 15, 'bgr555le': 15, 'vaapi_moco': 0, 'vaapi_idct': 0, 'vaapi_vld': 0, 'yuv420p16le': 24, 'yuv420p16be': 24, 'yuv422p16le': 32, 'yuv422p16be': 32, 'yuv444p16le': 48, 'yuv444p16be': 48, 'dxva2_vld': 0, 'rgb444le': 12, 'rgb444be': 12, 'bgr444le': 12, 'bgr444be': 12, 'ya8': 16, 'bgr48be': 48, 'bgr48le': 48, 'yuv420p9be': 13, 'yuv420p9le': 13, 'yuv420p10be': 15, 'yuv420p10le': 15, 'yuv422p10be': 20, 'yuv422p10le': 20, 'yuv444p9be': 27, 'yuv444p9le': 27, 'yuv444p10be': 30, 'yuv444p10le': 30, 'yuv422p9be': 18, 'yuv422p9le': 18, 'gbrp': 24, 'gbrp9be': 27, 'gbrp9le': 27, 'gbrp10be': 30, 'gbrp10le': 30, 'gbrp16be': 48, 'gbrp16le': 48, 'yuva422p': 24, 'yuva444p': 32, 'yuva420p9be': 22, 'yuva420p9le': 22, 'yuva422p9be': 27, 'yuva422p9le': 27, 'yuva444p9be': 36, 'yuva444p9le': 36, 'yuva420p10be': 25, 'yuva420p10le': 25, 'yuva422p10be': 30, 'yuva422p10le': 30, 'yuva444p10be': 40, 'yuva444p10le': 40, 'yuva420p16be': 40, 'yuva420p16le': 40, 'yuva422p16be': 48, 'yuva422p16le': 48, 'yuva444p16be': 64, 'yuva444p16le': 64, 'vdpau': 0, 'xyz12le': 36, 'xyz12be': 36, 'nv16': 16, 'nv20le': 20, 'nv20be': 20, 'rgba64be': 64, 'rgba64le': 64, 'bgra64be': 64, 'bgra64le': 64, 'yvyu422': 16, 'ya16be': 32, 'ya16le': 32, 'gbrap': 32, 'gbrap16be': 64, 'gbrap16le': 64, 'qsv': 0, 'mmal': 0, 'd3d11va_vld': 0, 'cuda': 0, '0rgb': 24, 'rgb0': 24, '0bgr': 24, 'bgr0': 24, 'yuv420p12be': 18, 'yuv420p12le': 18, 'yuv420p14be': 21, 'yuv420p14le': 21, 'yuv422p12be': 24, 'yuv422p12le': 24, 'yuv422p14be': 28, 'yuv422p14le': 28, 'yuv444p12be': 36, 'yuv444p12le': 36, 'yuv444p14be': 42, 'yuv444p14le': 42, 'gbrp12be': 36, 'gbrp12le': 36, 'gbrp14be': 42, 'gbrp14le': 42, 'yuvj411p': 12, 'bayer_bggr8': 8, 'bayer_rggb8': 8, 'bayer_gbrg8': 8, 'bayer_grbg8': 8, 'bayer_bggr16le': 16, 'bayer_bggr16be': 16, 'bayer_rggb16le': 16, 'bayer_rggb16be': 16, 'bayer_gbrg16le': 16, 'bayer_gbrg16be': 16, 'bayer_grbg16le': 16, 'bayer_grbg16be': 16, 'xvmc': 0, 'yuv440p10le': 20, 'yuv440p10be': 20, 'yuv440p12le': 24, 'yuv440p12be': 24, 'ayuv64le': 64, 'ayuv64be': 64, 'videotoolbox_vld': 0, 'p010le': 15, 'p010be': 15, 'gbrap12be': 48, 'gbrap12le': 48, 'gbrap10be': 40, 'gbrap10le': 40, 'mediacodec': 0, 'gray12be': 12, 'gray12le': 12, 'gray10be': 10, 'gray10le': 10, 'p016le': 24, 'p016be': 24, 'd3d11': 0, 'gray9be': 9, 'gray9le': 9, 'gbrpf32be': 96, 'gbrpf32le': 96, 'gbrapf32be': 128, 'gbrapf32le': 128, 'drm_prime': 0, 'opencl': 0, 'gray14be': 14, 'gray14le': 14, 'grayf32be': 32, 'grayf32le': 32, 'yuva422p12be': 36, 'yuva422p12le': 36, 'yuva444p12be': 48, 'yuva444p12le': 48, 'nv24': 24, 'nv42': 24}
[+] INFO: Framerate: 30.0
[+] INFO: Starting to upscale extracted images
2019-10-07 18:15:54.563104 [+] INFO: Starting upscaled image cleaner
2019-10-07 18:15:54.566101 [+] INFO: [upscaler] Thread 0 started2019-10-07 18:15:54.567100 [+] INFO: [upscaler] Thread 1 started
2019-10-07 18:15:54.568100 [+] INFO: [upscaler] Thread 2 started
2019-10-07 18:15:54.569102 [+] INFO: Executing: ['C:\\Users\\_-H-_\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '4.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp_hm4dgq3\\0', '--output_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp6oedpwgp']2019-10-07 18:15:54.571099 [+] INFO: Executing: ['C:\\Users\\_-H-_\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '4.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp_hm4dgq3\\1', '--output_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp6oedpwgp']


2019-10-07 18:15:54.571099 [+] INFO: [upscaler] Thread 3 started2019-10-07 18:15:54.585095 [+] INFO: Executing: ['C:\\Users\\_-H-_\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '4.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp_hm4dgq3\\2', '--output_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp6oedpwgp']
2019-10-07 18:15:54.611089 [+] INFO: Executing: ['C:\\Users\\_-H-_\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '4.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp_hm4dgq3\\3', '--output_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp6oedpwgp']

Upscaling Progress:   0%|                                                                     | 0/3480 [00:00<?, ?it/s] 変換に失敗し変た換フにァ失イ敗ルしがたあフりァまイすル
あります
変換に失敗したファイルがあります
変換に失敗したファイルがあります
2019-10-07 18:15:55.432950 [+] INFO: Killing upscaled image cleaner
Upscaling Progress:   0%|                                                                     | 0/3480 [00:01<?, ?it/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 321, in _upscale
  File "upscaler.py", line 357, in run
  File "upscaler.py", line 293, in _upscale_frames
  File "waifu2x_caffe.py", line 88, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\_-H-_\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '4.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp_hm4dgq3\\0', '--output_path', 'C:\\Users\\_-H-_\\AppData\\Local\\Temp\\video2x\\tmp6oedpwgp']' returned non-zero exit status 1.

Upscaling Progress:   0%|                                                                     | 0/3480 [00:02<?, ?it/s]

**Comment by k4yt3x** [comment]
It looks like waifu2x has failed to upscale, but the problem with waifu2x-caffe is that it's error messages don't contain too much information other than saying "oh it didn't work".

Do you have Nvidia GPU and GPU drivers installed?

**Comment by HokutoShinken** [comment]
No, i use dual graphics. An Intel and an AMD

**Comment by k4yt3x** [comment]
If you don't use Nvidia GPU then you can't use waifu2x-caffe.
You'll have to use waifu2x-converter-cpp.

**Comment by HokutoShinken** [comment]
Okay, it worked! It took several hours, but i'm happy with the result

Thanks again. Keep it up!

**Comment by k4yt3x** [comment]
@HokutoShinken glad to hear it worked.
