### ISSUE TITLE
When using Anime4k it looks like video2x is trying to get a file from "c:\users\k4t3x"

### ISSUE THREAD

**Issue by Hotvedt2** [k4yt3x/video2x#167]
Hi,

I've been using Video2x for some time now, and i wanted to try out Anime4k, but when it starts its upscaling progress it fails, and i think i know the problem, but i don't know how to fix it.

Here is a screenshot of the command window where it fails, it freezes here.
![f64ca0a1dc958e9446297eaa62c9f7b9](https://user-images.githubusercontent.com/52655886/68998944-15723680-08b9-11ea-9097-b713a89088a2.png)

Here is a paste from the command window, 

> INFO: Starting to upscale extracted images
2019-11-16 21:20:19.911342 [+] INFO: Starting upscaled image cleaner
Upscaling Progress:   0%|                                                                                                                               | 0/1121 [00:00<?, ?it/s]2019-11-16 21:20:19.923654 [+] INFO: Executing: ['C:\\Program Files\\Java\\jdk-12.0.2\\bin\\java.exe', '-jar', 'C:\\Users\\turbo\\AppData\\Local\\video2x\\anime4k\\Anime4K.jar', 'C:\\Users\\turbo\\AppData\\Local\\Temp\\video2x\\tmppt93xyvp\\0\\extracted_1.PNG', 'C:\\Users\\turbo\\AppData\\Local\\Temp\\video2x\\tmpo8lhinwm\\extracted_1.PNG', '133334.0']
2019-11-16 21:20:19.925625 [+] INFO: Killing upscaled image cleaner
Upscaling Progress:   0%|                                                                                                                               | 0/1121 [00:01<?, ?it/s]Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-1, started 12004)>>
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 321, in _upscale
  File "upscaler.py", line 357, in run
  File "upscaler.py", line 293, in _upscale_frames
    original_height = video_info['streams'][video_stream_index]['height']
  File "anime4k.py", line 82, in upscale
  File "subprocess.py", line 472, in run
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tokenize.py", line 397, in find_cookie
LookupError: unknown encoding: future_fstrings
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "threading.py", line 885, in _bootstrap
  File "threading.py", line 927, in _bootstrap_inner
  File "c:\users\k4yt3x\appdata\local\programs\python\python37\lib\traceback.py", line 167, in format_exc
  File "c:\users\k4yt3x\appdata\local\programs\python\python37\lib\traceback.py", line 121, in format_exception
  File "c:\users\k4yt3x\appdata\local\programs\python\python37\lib\traceback.py", line 508, in __init__
  File "c:\users\k4yt3x\appdata\local\programs\python\python37\lib\traceback.py", line 363, in extract
  File "c:\users\k4yt3x\appdata\local\programs\python\python37\lib\traceback.py", line 285, in line
  File "c:\users\k4yt3x\appdata\local\programs\python\python37\lib\linecache.py", line 16, in getline
  File "c:\users\k4yt3x\appdata\local\programs\python\python37\lib\linecache.py", line 47, in getlines
  File "c:\users\k4yt3x\appdata\local\programs\python\python37\lib\linecache.py", line 136, in updatecache
  File "tokenize.py", line 449, in open
  File "tokenize.py", line 436, in detect_encoding
  File "tokenize.py", line 405, in find_cookie
SyntaxError: unknown encoding for 'upscaler.py': future_fstrings
Upscaling Progress:   0%|                                                                                                                               | 0/1121 [00:02<?, ?it/s`

I assume this is because it is trying to find files in what i can tell is your computers user directory.
I hope this is all the information you need to identify the problem, if you need more information hit me up.

\Turbo, the python newbie.

**Comment by k4yt3x** [comment]
You need to install JDK 12 and write its path into the config file.
