### ISSUE TITLE
Anime4k Fails to Work

### ISSUE THREAD

**Issue by up2urheadlights** [k4yt3x/video2x#173]
Frames are extracted to temp folder but when it comes to actually upscaling an exception happens and then script exits.

Here is the error:

```
Upscaling Progress:   0%|                                                                    | 0/35887 [00:04<?, ?it/s][!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 401, in <module>
    upscaler.run()
  File "C:\Users\duffy\Desktop\video2x-master\src\upscaler.py", line 357, in run
    self._upscale_frames()
  File "C:\Users\duffy\Desktop\video2x-master\src\upscaler.py", line 293, in _upscale_frames
    raise(self.upscaler_exceptions[0])
  File "C:\Users\duffy\Desktop\video2x-master\src\anime4k.py", line 82, in upscale
    return_value += subprocess.run(execute, check=True).returncode
  File "C:\Users\duffy\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Java\\jre1.8.0_231\\bin\\java.exe', '-jar', 'C:\\Users\\duffy\\AppData\\Local\\video2x\\anime4k\\Anime4K.jar', 'C:\\Users\\duffy\\AppData\\Local\\Temp\\video2x\\tmpa1yqysbf\\6\\extracted_100.png', 'C:\\Users\\duffy\\AppData\\Local\\Temp\\video2x\\tmp9rjrllqn\\extracted_100.png', '4.5']' returned non-zero exit status 1.
Upscaling Progress:   0%|                                                                    | 0/35887 [00:05<?, ?it/s]
```

**Comment by k4yt3x** [comment]
You need JDK12.
https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase12-5440181.html
