### ISSUE TITLE
FileNotFoundError: "C:/Program Files (x86)/ffmpeg/bin/ffmpeg.exe"

### ISSUE THREAD

**Issue by WSADKeysGaming** [K4YT3X/video2x#18]
```
"C:/Program Files (x86)/ffmpeg/bin/ffmpeg.exe" -i "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\testvid.mp4" C:\Users\Me\AppData\Local\Programs\Python\Python37-32\frames\extracted_%0d.png -y
[!] ERROR: An exception occurred
Traceback (most recent call last):
  File "video2x.py", line 287, in <module>
    video2x()
  File "video2x.py", line 208, in video2x
    fm.extract_frames(args.video, FRAMES)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\ffmpeg.py", line 41, in extract_frames
    subprocess.call(execute)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 317, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by K4YT3X** [comment]
I admit that part is a bit counter-intuitive for average users, maybe I'll consider making an anto-deploy for all the dependencies. It shouldn't be hard.

**Comment by WSADKeysGaming** [comment]
I found an FF MPEG binary in my documents folder that I used for another
program, thought it would be okay, but I guess I needed the updated
version. Works now

**Comment by K4YT3X** [comment]
Congrats that it works. I'm closing the issue then.
