### ISSUE TITLE
Not letting me convert any videos at all and returns with this error:

### ISSUE THREAD

**Issue by Michael18751** [k4yt3x/video2x#182]
|`waifu2x-caffe`||
version 2.9.0
Nvidia Mx 150

C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpt1xwiv0f']' returned non-zero exit status 3221226505

**Comment by k4yt3x** [comment]
Version too old. Retry with a newer version.

**Comment by Michael18751** [comment]
ok. Thanks! I stayed on this version because it was the latest "full version"

**Comment by Michael18751** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 321, in _upscale
  File "upscaler.py", line 357, in run
  File "upscaler.py", line 293, in _upscale_frames
  File "waifu2x_caffe.py", line 88, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Owner\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '4.0', '--noise_level', '3', '--process', 'cudnn', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpu523vyyu\\2', '--output_path', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmp4i8a6_2h']' returned non-zero exit status 3228369022.

This happened in the latest version.

**Comment by Michael18751** [comment]
This is what happened when I tried to use anime4k

Upscaling Progress:   0%|                                                                                                                                                                 | 0/301 [00:01<?, ?it/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 321, in _upscale
  File "upscaler.py", line 357, in run
  File "upscaler.py", line 293, in _upscale_frames
  File "anime4k.py", line 82, in upscale
  File "subprocess.py", line 472, in run
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Michael18751** [comment]
CUDNN NcUN VULKAN seems to work!

**Comment by Michael18751** [comment]
so no matter what it cannot find files for anime4k

**Comment by Michael18751** [comment]
also is there a way to make it render one frame at a time so It wont eat up all my ram and vram instantly?

**Comment by k4yt3x** [comment]
I think you're missing JRE 12
https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase12-5440181.html

**Comment by k4yt3x** [comment]
> also is there a way to make it render one frame at a time so It wont eat up all my ram and vram instantly?

There is none. The program is designed to run at full efficiency. The load is also not determined by v2x, but rather the underlying w2x or a4k engine.

**Comment by Michael18751** [comment]
Thank you so much! The issue is fixed :)

**Comment by Michael18751** [comment]
But Waifu2x Caffe is still giving me an exception error :( I think im out of memory but I have 16gb. Idk anymore at this point. I'll stick with anime4k for now

**Comment by k4yt3x** [comment]
You've included too little information in your w2x output.
Post more of the context for me to see what happened.

**Comment by Michael18751** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
File "threading.py", line 917, in _bootstrap_inner
File "threading.py", line 865, in run
File "video2x_gui.py", line 321, in _upscale
File "upscaler.py", line 357, in run
File "upscaler.py", line 293, in _upscale_frames
File "waifu2x_caffe.py", line 88, in upscale
File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\Users\Owner\AppData\Local\video2x\waifu2x-caffe\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '4.0', '--noise_level', '3', '--process', 'cudnn', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\Users\Owner\AppData\Local\Temp\video2x\tmpu523vyyu\2', '--output_path', 'C:\Users\Owner\AppData\Local\Temp\video2x\tmp4i8a6_2h']' returned non-zero exit status 3228369022.


Also is there a way to output video using intel quicksync x264?

**Comment by Michael18751** [comment]
This is bad, my export that took almost 12 hours to do failed. ;(

[mp4 @ 00000295ec289980] Could not find tag for codec wmapro in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:1 -> #0:1 (copy)
    Last message repeated 1 times
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 321, in _upscale
  File "upscaler.py", line 369, in run
  File "ffmpeg.py", line 212, in migrate_audio_tracks_subtitles
  File "ffmpeg.py", line 287, in _execute
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Owner\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-hwaccel', 'auto', '-y', '-i', 'G:\\Files\\Video2xCache\\tmp1y8g8yho\\no_audio.mp4', '-i', 'C:\\Users\\Owner\\Videos\\Video2x Input\\Video2x TEST FOOTAGE S1E1.wmv', '-map', '0:v:0?', '-map', '1?', '-map', '-1:v?', '-c', 'copy', '-pix_fmt', 'yuv420p', 'C:\\Users\\Owner\\Videos\\Video2x Input\\Video2x TEST FOOTAGE S1E1.wmv_output.mp4']' returned non-zero exit status 1.
