### ISSUE TITLE
Command returned non-zero exit status 1

### ISSUE THREAD

**Issue by junglized** [k4yt3x/video2x#199]
I tried Video2x with another .mkv file, this time with double audio and ass subtitles (opening of anime series episode). Here is whole command window:

```
2020-02-09 14:18:41.510138 [+] INFO: Extracted frames are being saved to: C:\Users\JUNGLI~1\AppData\Local\Temp\video2x\tmp08bsi2s3
2020-02-09 14:18:41.510138 [+] INFO: Upscaled frames are being saved to: C:\Users\JUNGLI~1\AppData\Local\Temp\video2x\tmpxjj7l3ph
2020-02-09 14:18:41.510138 [+] INFO: Executing: ['C:\\Users\\Junglized\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-hwaccel', 'auto', '-y', '-i', "D:\\Opening.mkv", '-pix_fmt', 'rgba64be', 'C:\\Users\\JUNGLI~1\\AppData\\Local\\Temp\\video2x\\tmp08bsi2s3\\extracted_%0d.PNG']
ffmpeg version git-2020-02-06-343ccfc Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 39.100 / 56. 39.100
  libavcodec     58. 68.100 / 58. 68.100
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 74.100 /  7. 74.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, matroska,webm, from 'D:\Opening.mkv':
  Metadata:
    encoder         : libebml v0.7.9 + libmatroska v0.8.1
    creation_time   : 2010-01-20T04:40:57.000000Z
  Duration: 00:01:30.16, start: 0.000000, bitrate: 4059 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 704x576, SAR 12:11 DAR 4:3, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(eng): Subtitle: ass (default)
    Stream #0:2(eng): Subtitle: ass
    Metadata:
      title           : Songs & Signs
    Stream #0:3(jpn): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
    Stream #0:4(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
[h264 @ 00000230c61dcd80] Using auto hwaccel type dxva2 with new default device.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\Users\JUNGLI~1\AppData\Local\Temp\video2x\tmp08bsi2s3\extracted_%0d.PNG':
  Metadata:
    encoder         : Lavf58.38.100
    Stream #0:0: Video: png, rgba64be, 704x576 [SAR 12:11 DAR 4:3], q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      encoder         : Lavc58.68.100 png
frame= 2153 fps= 15 q=-0.0 Lsize=N/A time=00:01:29.79 bitrate=N/A speed=0.636x
video:3310023kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2020-02-09 14:21:02.875289 [+] INFO: Executing: C:\Users\Junglized\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i D:\Opening.mkv
2020-02-09 14:21:02.916094 [+] INFO: Executing: C:\Users\Junglized\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -pix_fmts
2020-02-09 14:21:02.962965 [+] INFO: {'yuv420p': 12, 'yuyv422': 16, 'rgb24': 24, 'bgr24': 24, 'yuv422p': 16, 'yuv444p': 24, 'yuv410p': 9, 'yuv411p': 12, 'gray': 8, 'monow': 1, 'monob': 1, 'pal8': 8, 'yuvj420p': 12, 'yuvj422p': 16, 'yuvj444p': 24, 'uyvy422': 16, 'uyyvyy411': 12, 'bgr8': 8, 'bgr4': 4, 'bgr4_byte': 4, 'rgb8': 8, 'rgb4': 4, 'rgb4_byte': 4, 'nv12': 12, 'nv21': 12, 'argb': 32, 'rgba': 32, 'abgr': 32, 'bgra': 32, 'gray16be': 16, 'gray16le': 16, 'yuv440p': 16, 'yuvj440p': 16, 'yuva420p': 20, 'rgb48be': 48, 'rgb48le': 48, 'rgb565be': 16, 'rgb565le': 16, 'rgb555be': 15, 'rgb555le': 15, 'bgr565be': 16, 'bgr565le': 16, 'bgr555be': 15, 'bgr555le': 15, 'vaapi_moco': 0, 'vaapi_idct': 0, 'vaapi_vld': 0, 'yuv420p16le': 24, 'yuv420p16be': 24, 'yuv422p16le': 32, 'yuv422p16be': 32, 'yuv444p16le': 48, 'yuv444p16be': 48, 'dxva2_vld': 0, 'rgb444le': 12, 'rgb444be': 12, 'bgr444le': 12, 'bgr444be': 12, 'ya8': 16, 'bgr48be': 48, 'bgr48le': 48, 'yuv420p9be': 13, 'yuv420p9le': 13, 'yuv420p10be': 15, 'yuv420p10le': 15, 'yuv422p10be': 20, 'yuv422p10le': 20, 'yuv444p9be': 27, 'yuv444p9le': 27, 'yuv444p10be': 30, 'yuv444p10le': 30, 'yuv422p9be': 18, 'yuv422p9le': 18, 'gbrp': 24, 'gbrp9be': 27, 'gbrp9le': 27, 'gbrp10be': 30, 'gbrp10le': 30, 'gbrp16be': 48, 'gbrp16le': 48, 'yuva422p': 24, 'yuva444p': 32, 'yuva420p9be': 22, 'yuva420p9le': 22, 'yuva422p9be': 27, 'yuva422p9le': 27, 'yuva444p9be': 36, 'yuva444p9le': 36, 'yuva420p10be': 25, 'yuva420p10le': 25, 'yuva422p10be': 30, 'yuva422p10le': 30, 'yuva444p10be': 40, 'yuva444p10le': 40, 'yuva420p16be': 40, 'yuva420p16le': 40, 'yuva422p16be': 48, 'yuva422p16le': 48, 'yuva444p16be': 64, 'yuva444p16le': 64, 'vdpau': 0, 'xyz12le': 36, 'xyz12be': 36, 'nv16': 16, 'nv20le': 20, 'nv20be': 20, 'rgba64be': 64, 'rgba64le': 64, 'bgra64be': 64, 'bgra64le': 64, 'yvyu422': 16, 'ya16be': 32, 'ya16le': 32, 'gbrap': 32, 'gbrap16be': 64, 'gbrap16le': 64, 'qsv': 0, 'mmal': 0, 'd3d11va_vld': 0, 'cuda': 0, '0rgb': 24, 'rgb0': 24, '0bgr': 24, 'bgr0': 24, 'yuv420p12be': 18, 'yuv420p12le': 18, 'yuv420p14be': 21, 'yuv420p14le': 21, 'yuv422p12be': 24, 'yuv422p12le': 24, 'yuv422p14be': 28, 'yuv422p14le': 28, 'yuv444p12be': 36, 'yuv444p12le': 36, 'yuv444p14be': 42, 'yuv444p14le': 42, 'gbrp12be': 36, 'gbrp12le': 36, 'gbrp14be': 42, 'gbrp14le': 42, 'yuvj411p': 12, 'bayer_bggr8': 8, 'bayer_rggb8': 8, 'bayer_gbrg8': 8, 'bayer_grbg8': 8, 'bayer_bggr16le': 16, 'bayer_bggr16be': 16, 'bayer_rggb16le': 16, 'bayer_rggb16be': 16, 'bayer_gbrg16le': 16, 'bayer_gbrg16be': 16, 'bayer_grbg16le': 16, 'bayer_grbg16be': 16, 'xvmc': 0, 'yuv440p10le': 20, 'yuv440p10be': 20, 'yuv440p12le': 24, 'yuv440p12be': 24, 'ayuv64le': 64, 'ayuv64be': 64, 'videotoolbox_vld': 0, 'p010le': 15, 'p010be': 15, 'gbrap12be': 48, 'gbrap12le': 48, 'gbrap10be': 40, 'gbrap10le': 40, 'mediacodec': 0, 'gray12be': 12, 'gray12le': 12, 'gray10be': 10, 'gray10le': 10, 'p016le': 24, 'p016be': 24, 'd3d11': 0, 'gray9be': 9, 'gray9le': 9, 'gbrpf32be': 96, 'gbrpf32le': 96, 'gbrapf32be': 128, 'gbrapf32le': 128, 'drm_prime': 0, 'opencl': 0, 'gray14be': 14, 'gray14le': 14, 'grayf32be': 32, 'grayf32le': 32, 'yuva422p12be': 36, 'yuva422p12le': 36, 'yuva444p12be': 48, 'yuva444p12le': 48, 'nv24': 24, 'nv42': 24, 'vulkan': 0}
[+] INFO: Framerate: 23.976023976023978
[+] INFO: Starting to upscale extracted images
2020-02-09 14:21:05.047913 [+] INFO: Starting upscaled image cleaner
2020-02-09 14:21:05.048912 [+] INFO: [upscaler] Thread 0 started
2020-02-09 14:21:05.049911 [+] INFO: Executing: ['C:\\Users\\Junglized\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'PNG', '--mode', 'noise_scale', '--scale_ratio', '2.0', '--noise_level', '3', '--process', 'cudnn', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '12', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\JUNGLI~1\\AppData\\Local\\Temp\\video2x\\tmp08bsi2s3\\0', '--output_path', 'C:\\Users\\JUNGLI~1\\AppData\\Local\\Temp\\video2x\\tmpxjj7l3ph']
Upscaling Progress: 100%|#########################################################9| 2152/2153 [54:08<00:01,  1.58s/it] 変換に成功しました
Upscaling Progress: 100%|#########################################################9| 2152/2153 [54:09<00:01,  1.51s/it]
2020-02-09 15:15:15.367770 [+] INFO: [upscaler] Thread 0 exiting
2020-02-09 15:15:15.367770 [+] INFO: Killing upscaled image cleaner
[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
2020-02-09 15:15:17.742598 [+] INFO: Executing: ['C:\\Users\\Junglized\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-r', '23.976023976023978', '-s', '1408x1152', '-hwaccel', 'auto', '-y', '-f', 'image2', '-pix_fmt', 'yuv420p', '-i', 'C:\\Users\\JUNGLI~1\\AppData\\Local\\Temp\\video2x\\tmpxjj7l3ph\\extracted_%d.PNG', '-vcodec', 'libx264', '-crf', '17', '-pix_fmt', 'yuv420p', 'C:\\Users\\JUNGLI~1\\AppData\\Local\\Temp\\video2x\\tmpxjj7l3ph\\no_audio.mp4']
ffmpeg version git-2020-02-06-343ccfc Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 39.100 / 56. 39.100
  libavcodec     58. 68.100 / 58. 68.100
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 74.100 /  7. 74.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, image2, from 'C:\Users\JUNGLI~1\AppData\Local\Temp\video2x\tmpxjj7l3ph\extracted_%d.PNG':
  Duration: 00:01:29.80, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, yuv420p(pc), 1408x1152, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 000002d9cc2792c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000002d9cc2792c0] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 000002d9cc2792c0] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=17.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\JUNGLI~1\AppData\Local\Temp\video2x\tmpxjj7l3ph\no_audio.mp4':
  Metadata:
    encoder         : Lavf58.38.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1408x1152, q=-1--1, 23.98 fps, 24k tbn, 23.98 tbc
    Metadata:
      encoder         : Lavc58.68.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame= 2153 fps= 27 q=-1.0 Lsize=   53515kB time=00:01:29.67 bitrate=4888.8kbits/s speed=1.12x
video:53490kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.047187%
[libx264 @ 000002d9cc2792c0] frame I:64    Avg QP:13.50  size: 69977
[libx264 @ 000002d9cc2792c0] frame P:665   Avg QP:15.97  size: 39398
[libx264 @ 000002d9cc2792c0] frame B:1424  Avg QP:17.64  size: 16920
[libx264 @ 000002d9cc2792c0] consecutive B-frames: 10.3%  3.5%  2.9% 83.2%
[libx264 @ 000002d9cc2792c0] mb I  I16..4:  9.9% 60.6% 29.5%
[libx264 @ 000002d9cc2792c0] mb P  I16..4:  6.1% 27.9%  7.3%  P16..4: 28.5% 16.5%  6.2%  0.0%  0.0%    skip: 7.6%
[libx264 @ 000002d9cc2792c0] mb B  I16..4:  1.4%  3.6%  0.8%  B16..8: 37.1% 10.6%  1.8%  direct: 6.4%  skip:38.3%  L0:47.2% L1:44.5% BI: 8.3%
[libx264 @ 000002d9cc2792c0] 8x8 transform intra:65.5% inter:79.2%
[libx264 @ 000002d9cc2792c0] coded y,uvDC,uvAC intra: 44.0% 43.0% 14.7% inter: 20.0% 23.0% 0.2%
[libx264 @ 000002d9cc2792c0] i16 v,h,dc,p: 35% 17%  5% 44%
[libx264 @ 000002d9cc2792c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 15% 19%  5%  8% 10%  6%  5%  5%
[libx264 @ 000002d9cc2792c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 33% 17% 15%  5% 10%  8%  6%  5%  2%
[libx264 @ 000002d9cc2792c0] i8c dc,h,v,p: 64% 16% 17%  3%
[libx264 @ 000002d9cc2792c0] Weighted P-Frames: Y:11.9% UV:6.6%
[libx264 @ 000002d9cc2792c0] ref P L0: 54.1%  7.8% 24.7% 13.0%  0.4%
[libx264 @ 000002d9cc2792c0] ref B L0: 79.1% 16.2%  4.7%
[libx264 @ 000002d9cc2792c0] ref B L1: 92.4%  7.6%
[libx264 @ 000002d9cc2792c0] kb/s:4879.64
[+] INFO: Conversion completed
[+] INFO: Migrating audio tracks and subtitles to upscaled video
2020-02-09 15:16:38.050421 [+] INFO: Executing: ['C:\\Users\\Junglized\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-hwaccel', 'auto', '-y', '-i', 'C:\\Users\\JUNGLI~1\\AppData\\Local\\Temp\\video2x\\tmpxjj7l3ph\\no_audio.mp4', '-i', "D:\\Opening.mkv", '-map', '0:v:0?', '-map', '1?', '-map', '-1:v?', '-c', 'copy', '-pix_fmt', 'yuv420p', "D:\\Opening.mkv_output.mp4"]
ffmpeg version git-2020-02-06-343ccfc Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 39.100 / 56. 39.100
  libavcodec     58. 68.100 / 58. 68.100
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 74.100 /  7. 74.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\JUNGLI~1\AppData\Local\Temp\video2x\tmpxjj7l3ph\no_audio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.38.100
  Duration: 00:01:29.80, start: 0.000000, bitrate: 4881 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1408x1152, 4879 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, matroska,webm, from 'D:\Opening.mkv':
  Metadata:
    encoder         : libebml v0.7.9 + libmatroska v0.8.1
    creation_time   : 2010-01-20T04:40:57.000000Z
  Duration: 00:01:30.16, start: 0.000000, bitrate: 4059 kb/s
    Stream #1:0: Video: h264 (High), yuv420p(progressive), 704x576, SAR 12:11 DAR 4:3, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #1:1(eng): Subtitle: ass (default)
    Stream #1:2(eng): Subtitle: ass
    Metadata:
      title           : Songs & Signs
    Stream #1:3(jpn): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
    Stream #1:4(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
[mp4 @ 000002a1692af780] Could not find tag for codec ass in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:1 -> #0:1 (copy)
  Stream #1:2 -> #0:2 (copy)
  Stream #1:3 -> #0:3 (copy)
  Stream #1:4 -> #0:4 (copy)
    Last message repeated 1 times
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 321, in _upscale
  File "upscaler.py", line 369, in run
  File "ffmpeg.py", line 212, in migrate_audio_tracks_subtitles
  File "ffmpeg.py", line 287, in _execute
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Junglized\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-hwaccel', 'auto', '-y', '-i', 'C:\\Users\\JUNGLI~1\\AppData\\Local\\Temp\\video2x\\tmpxjj7l3ph\\no_audio.mp4', '-i', "D:\\Opening.mkv", '-map', '0:v:0?', '-map', '1?', '-map', '-1:v?', '-c', 'copy', '-pix_fmt', 'yuv420p', "D:\\Opening.mkv_output.mp4"]' returned non-zero exit status 1.
```

**Comment by k4yt3x** [comment]
It seems like FFmpeg failed to parse the ASS subtitle files.

**Comment by junglized** [comment]
Does it mean not to upscale mkvs with subtitles then?

**Comment by k4yt3x** [comment]
I'm not quite sure why this is the case right now. A lot of codecs could use MKV, and it's not the cause here.
The problem here is just that FFmpeg failed to read the ASS stream in your original MKV file.
If you remove the subtitles, it should work fine.
Although I'm not quite sure why it wasn't able to read the ASS stream.

**Comment by dgcampea** [comment]
Your input is a MKV which can embed a multitude of things, you specified a MP4 output which is quite restricted to what content it might contain.
To fix, you should save the output as MKV.

**Comment by ZeroCool940711** [comment]
Im getting something similar to this error but with FFMPEG, seems like in my case it cant find the extracted frames for the video even tho they are on the cache folder, ffmpeg exits with the same error `Command returned non-zero exit status 1`, it only happens on the last 2 versions (2.10.0 and 3.0.0), older versions like 2.9.0 do work, I tried using multiple drivers and the only one working for me is Anime4K, the rest of them give the same error, for the Method im using CPU as its running on a server I have for this stuff, the server is running Windows 10 Pro, also for some reason the `Waify2x Converter CPP` driver those not works out of the box when using the `video2x-x.x.x-win32-full.zip` file, I had to change the path to the dependencies folder from the config file to use the full path instead of the relative one that it has by default, adding the path to the Windows path does not help either, the only way it works is if I add the full path on the config file which is weird.

**Comment by metanomial** [comment]
Another "returned non-zero exit status 1" error:
```
Upscaling Progress:   0%|                                | 0/268 [00:01<?, ?it/s][!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 398, in <module>
  File "upscaler.py", line 357, in run
  File "upscaler.py", line 293, in _upscale_frames
  File "waifu2x_caffe.py", line 88, in upscale
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--batch_size', '1', '--crop_size', '128', '--gpu', '0', '--input_path', 'C:\\Users\\benja\\AppData\\Local\\Temp\\video2x\\tmpffbjmbe6\\0', '--mode', 'noise_scale', '--noise_level', '3', '--output_depth', '12', '--output_extention', 'png', '--output_path', 'C:\\Users\\benja\\AppData\\Local\\Temp\\video2x\\tmpgla11kqi', '--output_quality', '-1', '--process', 'cpu', '--scale_ratio', '2.25', '--tta', '0']' returned non-zero exit status 1.
```
Only happens with `waifu2x-caffe`. tried CPU vs. GPU; .mp4 and .mkv; and a handful of configurations.

**Comment by k4yt3x** [comment]
@metanomial 
This only tells me that waifu2x ran into an error.
What's above might actually tell the cause of this error.
