### ISSUE TITLE
Permissionerror [Winerror 5] after Cleaning Temp

### ISSUE THREAD

**Issue by Darnasion** [k4yt3x/video2x#220]
Hello,

i am trying to upscale a whole directory. But after the first file and cleaning up temp i get a permission Error.

I used cmd in Admin mode. 

In the end the video gets created, but in avi format. And the temp folders are deleted as they should be. But the it does not continue with the next file.
```
PS C:\Users\Darnas\Desktop\video2x-3.1.0> python video2x.py -m gpu -d waifu2x_ncnn_vulkan -r 2 -i "D:\\JD\\serien\\One Piece\\convert\\" -o "D:\\JD\\serien\\One Piece\\"

    __      __  _       _                  ___   __   __
    \ \    / / (_)     | |                |__ \  \ \ / /
     \ \  / /   _    __| |   ___    ___      ) |  \ V /
      \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
       \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
        \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\


                  Video2X Video Enlarger

                       Version 3.1.0

[!] WARNING: Specified cache directory C:\Users\Darnas\AppData\Local\Temp\video2x does not exist
[?] USER: Create directory? [Y/n]: y
[+] INFO: C:\Users\Darnas\AppData\Local\Temp\video2x created
[+] INFO: Upscaling videos in directory: D:\JD\serien\One Piece\convert
2020-04-01 22:06:17.027750 [+] INFO: Extracted frames are being saved to: C:\Users\Darnas\AppData\Local\Temp\video2x\tmp5tepy_b5
2020-04-01 22:06:17.027750 [+] INFO: Upscaled frames are being saved to: C:\Users\Darnas\AppData\Local\Temp\video2x\tmp0e_atka4
2020-04-01 22:06:17.028748 [+] INFO: Executing: ['C:\\Users\\K4YT3X\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'D:\\JD\\serien\\One Piece\\convert\\One Piece - S01E007.avi', '-pix_fmt', 'rgba64be', 'C:\\Users\\Darnas\\AppData\\Local\\Temp\\video2x\\tmp5tepy_b5\\extracted_%0d.png']
ffmpeg version git-2020-03-28-3362330 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.101 / 56. 42.101
  libavcodec     58. 77.100 / 58. 77.100
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.100 /  7. 77.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, avi, from 'D:\JD\serien\One Piece\convert\One Piece - S01E007.avi':
  Metadata:
    encoder         : VirtualDubMod 1.5.10.2 (build 2540/release)
  Duration: 00:20:47.46, start: 0.000000, bitrate: 1265 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 1127 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 128 kb/s
[mpeg4 @ 0000020c5c062180] Using auto hwaccel type cuda with new default device.
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> png (native))
Press [q] to stop, [?] for help
[mpeg4 @ 0000020c5bdbb5c0] Video uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using the mpeg4_unpack_bframes bitstream filter without encoding but stream copy to fix it.
Output #0, image2, to 'C:\Users\Darnas\AppData\Local\Temp\video2x\tmp5tepy_b5\extracted_%0d.png':
  Metadata:
    encoder         : Lavf58.42.100
    Stream #0:0: Video: png, rgba64be, 640x480 [SAR 1:1 DAR 4:3], q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc
    Metadata:
      encoder         : Lavc58.77.100 png
frame=29910 fps= 19 q=-0.0 Lsize=N/A time=00:20:47.49 bitrate=N/A dup=1 drop=0 speed=0.795x
video:34796016kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2020-04-01 22:32:26.879351 [+] INFO: Executing: C:\Users\K4YT3X\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i D:\JD\serien\One Piece\convert\One Piece - S01E007.avi
2020-04-01 22:32:27.692178 [+] INFO: Executing: C:\Users\K4YT3X\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -pix_fmts
2020-04-01 22:32:27.723096 [+] INFO: {'yuv420p': 12, 'yuyv422': 16, 'rgb24': 24, 'bgr24': 24, 'yuv422p': 16, 'yuv444p': 24, 'yuv410p': 9, 'yuv411p': 12, 'gray': 8, 'monow': 1, 'monob': 1, 'pal8': 8, 'yuvj420p': 12, 'yuvj422p': 16, 'yuvj444p': 24, 'uyvy422': 16, 'uyyvyy411': 12, 'bgr8': 8, 'bgr4': 4, 'bgr4_byte': 4, 'rgb8': 8, 'rgb4': 4, 'rgb4_byte': 4, 'nv12': 12, 'nv21': 12, 'argb': 32, 'rgba': 32, 'abgr': 32, 'bgra': 32, 'gray16be': 16, 'gray16le': 16, 'yuv440p': 16, 'yuvj440p': 16, 'yuva420p': 20, 'rgb48be': 48, 'rgb48le': 48, 'rgb565be': 16, 'rgb565le': 16, 'rgb555be': 15, 'rgb555le': 15, 'bgr565be': 16, 'bgr565le': 16, 'bgr555be': 15, 'bgr555le': 15, 'vaapi_moco': 0, 'vaapi_idct': 0, 'vaapi_vld': 0, 'yuv420p16le': 24, 'yuv420p16be': 24, 'yuv422p16le': 32, 'yuv422p16be': 32, 'yuv444p16le': 48, 'yuv444p16be': 48, 'dxva2_vld': 0, 'rgb444le': 12, 'rgb444be': 12, 'bgr444le': 12, 'bgr444be': 12, 'ya8': 16, 'bgr48be': 48, 'bgr48le': 48, 'yuv420p9be': 13, 'yuv420p9le': 13, 'yuv420p10be': 15, 'yuv420p10le': 15, 'yuv422p10be': 20, 'yuv422p10le': 20, 'yuv444p9be': 27, 'yuv444p9le': 27, 'yuv444p10be': 30, 'yuv444p10le': 30, 'yuv422p9be': 18, 'yuv422p9le': 18, 'gbrp': 24, 'gbrp9be': 27, 'gbrp9le': 27, 'gbrp10be': 30, 'gbrp10le': 30, 'gbrp16be': 48, 'gbrp16le': 48, 'yuva422p': 24, 'yuva444p': 32, 'yuva420p9be': 22, 'yuva420p9le': 22, 'yuva422p9be': 27, 'yuva422p9le': 27, 'yuva444p9be': 36, 'yuva444p9le': 36, 'yuva420p10be': 25, 'yuva420p10le': 25, 'yuva422p10be': 30, 'yuva422p10le': 30, 'yuva444p10be': 40, 'yuva444p10le': 40, 'yuva420p16be': 40, 'yuva420p16le': 40, 'yuva422p16be': 48, 'yuva422p16le': 48, 'yuva444p16be': 64, 'yuva444p16le': 64, 'vdpau': 0, 'xyz12le': 36, 'xyz12be': 36, 'nv16': 16, 'nv20le': 20, 'nv20be': 20, 'rgba64be': 64, 'rgba64le': 64, 'bgra64be': 64, 'bgra64le': 64, 'yvyu422': 16, 'ya16be': 32, 'ya16le': 32, 'gbrap': 32, 'gbrap16be': 64, 'gbrap16le': 64, 'qsv': 0, 'mmal': 0, 'd3d11va_vld': 0, 'cuda': 0, '0rgb': 24, 'rgb0': 24, '0bgr': 24, 'bgr0': 24, 'yuv420p12be': 18, 'yuv420p12le': 18, 'yuv420p14be': 21, 'yuv420p14le': 21, 'yuv422p12be': 24, 'yuv422p12le': 24, 'yuv422p14be': 28, 'yuv422p14le': 28, 'yuv444p12be': 36, 'yuv444p12le': 36, 'yuv444p14be': 42, 'yuv444p14le': 42, 'gbrp12be': 36, 'gbrp12le': 36, 'gbrp14be': 42, 'gbrp14le': 42, 'yuvj411p': 12, 'bayer_bggr8': 8, 'bayer_rggb8': 8, 'bayer_gbrg8': 8, 'bayer_grbg8': 8, 'bayer_bggr16le': 16, 'bayer_bggr16be': 16, 'bayer_rggb16le': 16, 'bayer_rggb16be': 16, 'bayer_gbrg16le': 16, 'bayer_gbrg16be': 16, 'bayer_grbg16le': 16, 'bayer_grbg16be': 16, 'xvmc': 0, 'yuv440p10le': 20, 'yuv440p10be': 20, 'yuv440p12le': 24, 'yuv440p12be': 24, 'ayuv64le': 64, 'ayuv64be': 64, 'videotoolbox_vld': 0, 'p010le': 15, 'p010be': 15, 'gbrap12be': 48, 'gbrap12le': 48, 'gbrap10be': 40, 'gbrap10le': 40, 'mediacodec': 0, 'gray12be': 12, 'gray12le': 12, 'gray10be': 10, 'gray10le': 10, 'p016le': 24, 'p016be': 24, 'd3d11': 0, 'gray9be': 9, 'gray9le': 9, 'gbrpf32be': 96, 'gbrpf32le': 96, 'gbrapf32be': 128, 'gbrapf32le': 128, 'drm_prime': 0, 'opencl': 0, 'gray14be': 14, 'gray14le': 14, 'grayf32be': 32, 'grayf32le': 32, 'yuva422p12be': 36, 'yuva422p12le': 36, 'yuva444p12be': 48, 'yuva444p12le': 48, 'nv24': 24, 'nv42': 24, 'vulkan': 0, 'y210be': 20, 'y210le': 20}
[+] INFO: Framerate: 23.976
[+] INFO: Starting to upscale extracted images
2020-04-01 22:32:39.084726 [+] INFO: [upscaler] Subprocess 7336 executing: 'C:\Users\K4YT3X\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan' -i 'C:\Users\Darnas\AppData\Local\Temp\video2x\tmp5tepy_b5\0' -o 'C:\Users\Darnas\AppData\Local\Temp\video2x\tmp0e_atka4' -n 2 -s 2 -t 400 -m models-cunet -g 0 -j 1:2:2
2020-04-01 22:32:39.104673 [+] INFO: Starting upscaled image cleaner
2020-04-01 22:32:39.105670 [+] INFO: Main process waiting for subprocesses to exit
Upscaling Progress:   0%|                                                                    | 0/29910 [00:00<?, ?it/s][0 GeForce RTX 2080 Ti]  queueC=2[8]  queueT=1[2]  memU=4294967295  memDL=7  memHV=9
[0 GeForce RTX 2080 Ti]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
Upscaling Progress: 100%|#####################################################9| 29903/29910 [1:23:50<00:01,  5.94it/s]
2020-04-01 23:56:29.701439 [+] INFO: Subprocess 30956 exited with code 0
2020-04-01 23:56:29.701439 [+] INFO: Killing upscaled image cleaner
[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
2020-04-01 23:56:49.775780 [+] INFO: Executing: ['C:\\Users\\K4YT3X\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg', '-r', '23.976', '-s', '1280x960', '-hwaccel', 'auto', '-y', '-f', 'image2', '-pix_fmt', 'yuv420p', '-i', 'C:\\Users\\Darnas\\AppData\\Local\\Temp\\video2x\\tmp0e_atka4\\extracted_%d.png', '-vcodec', 'libx264', '-crf', '17', '-pix_fmt', 'yuv420p', 'C:\\Users\\Darnas\\AppData\\Local\\Temp\\video2x\\tmp0e_atka4\\no_audio.mp4']
ffmpeg version git-2020-03-28-3362330 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.101 / 56. 42.101
  libavcodec     58. 77.100 / 58. 77.100
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.100 /  7. 77.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, image2, from 'C:\Users\Darnas\AppData\Local\Temp\video2x\tmp0e_atka4\extracted_%d.png':
  Duration: 00:20:47.50, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, yuv420p(pc), 1280x960, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0000022dd9deefc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000022dd9deefc0] profile High, level 3.2, 4:2:0, 8-bit
[libx264 @ 0000022dd9deefc0] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=17.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\Darnas\AppData\Local\Temp\video2x\tmp0e_atka4\no_audio.mp4':
  Metadata:
    encoder         : Lavf58.42.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 1280x960, q=-1--1, 23.98 fps, 11988 tbn, 23.98 tbc
    Metadata:
      encoder         : Lavc58.77.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=29910 fps= 95 q=-1.0 Lsize=  634918kB time=00:20:47.37 bitrate=4169.8kbits/s speed=3.94x
video:634568kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.055041%
[libx264 @ 0000022dd9deefc0] frame I:550   Avg QP:12.37  size:114110
[libx264 @ 0000022dd9deefc0] frame P:8869  Avg QP:15.49  size: 42601
[libx264 @ 0000022dd9deefc0] frame B:20491 Avg QP:18.51  size: 10210
[libx264 @ 0000022dd9deefc0] consecutive B-frames:  5.3%  7.3%  7.9% 79.4%
[libx264 @ 0000022dd9deefc0] mb I  I16..4: 17.2% 46.2% 36.6%
[libx264 @ 0000022dd9deefc0] mb P  I16..4:  4.6% 13.7%  5.2%  P16..4: 30.2% 16.7%  9.1%  0.0%  0.0%    skip:20.4%
[libx264 @ 0000022dd9deefc0] mb B  I16..4:  0.7%  0.9%  0.4%  B16..8: 33.4%  6.3%  1.0%  direct: 4.6%  skip:52.7%  L0:43.7% L1:48.0% BI: 8.3%
[libx264 @ 0000022dd9deefc0] 8x8 transform intra:54.6% inter:68.3%
[libx264 @ 0000022dd9deefc0] coded y,uvDC,uvAC intra: 40.6% 75.9% 55.6% inter: 14.9% 24.0% 3.8%
[libx264 @ 0000022dd9deefc0] i16 v,h,dc,p: 60% 19%  8% 13%
[libx264 @ 0000022dd9deefc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 17% 30%  5%  5%  5%  5%  4%  5%
[libx264 @ 0000022dd9deefc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 20% 16%  5%  8%  7%  6%  5%  4%
[libx264 @ 0000022dd9deefc0] i8c dc,h,v,p: 50% 21% 20%  9%
[libx264 @ 0000022dd9deefc0] Weighted P-Frames: Y:1.8% UV:1.1%
[libx264 @ 0000022dd9deefc0] ref P L0: 58.5%  8.3% 23.3%  9.9%  0.1%
[libx264 @ 0000022dd9deefc0] ref B L0: 79.6% 15.9%  4.5%
[libx264 @ 0000022dd9deefc0] ref B L1: 92.3%  7.7%
[libx264 @ 0000022dd9deefc0] kb/s:4167.05
[+] INFO: Conversion completed
[+] INFO: Migrating audio tracks and subtitles to upscaled video
2020-04-02 00:02:06.395519 [+] INFO: Executing: ['C:\\Users\\K4YT3X\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'C:\\Users\\Darnas\\AppData\\Local\\Temp\\video2x\\tmp0e_atka4\\no_audio.mp4', '-i', 'D:\\JD\\serien\\One Piece\\convert\\One Piece - S01E007.avi', '-map', '0:v?', '-map', '1:a?', '-map', '1:s?', '-map', '1:d?', '-map', '1:t?', '-c', 'copy', '-pix_fmt', 'yuv420p', 'D:\\JD\\serien\\One Piece\\One Piece - S01E007.avi']
ffmpeg version git-2020-03-28-3362330 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.101 / 56. 42.101
  libavcodec     58. 77.100 / 58. 77.100
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.100 /  7. 77.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Darnas\AppData\Local\Temp\video2x\tmp0e_atka4\no_audio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.42.100
  Duration: 00:20:47.50, start: 0.000000, bitrate: 4169 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960, 4167 kb/s, 23.98 fps, 23.98 tbr, 11988 tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, avi, from 'D:\JD\serien\One Piece\convert\One Piece - S01E007.avi':
  Metadata:
    encoder         : VirtualDubMod 1.5.10.2 (build 2540/release)
  Duration: 00:20:47.46, start: 0.000000, bitrate: 1265 kb/s
    Stream #1:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 1127 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
    Stream #1:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 128 kb/s
Output #0, avi, to 'D:\JD\serien\One Piece\One Piece - S01E007.avi':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    ISFT            : Lavf58.42.100
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960, q=2-31, 4167 kb/s, 23.98 fps, 23.98 tbr, 47.95 tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=29910 fps=20401 q=-1.0 Lsize=  656705kB time=00:20:47.42 bitrate=4312.7kbits/s speed= 851x
video:634568kB audio:19491kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.404352%
Cleaning up cache directory: C:\Users\Darnas\AppData\Local\Temp\video2x\tmp5tepy_b5
Cleaning up cache directory: C:\Users\Darnas\AppData\Local\Temp\video2x\tmp0e_atka4
Cleaning up cache directory: C:\Users\Darnas\AppData\Local\Temp\video2x
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 454, in <module>
    upscaler.create_temp_directories()
  File "C:\Users\Darnas\Desktop\video2x-3.1.0\upscaler.py", line 74, in create_temp_directories
    self.extracted_frames = pathlib.Path(tempfile.mkdtemp(dir=self.video2x_cache_directory))
  File "C:\Users\Darnas\AppData\Local\Programs\Python\Python38\lib\tempfile.py", line 359, in mkdtemp
    _os.mkdir(file, 0o700)
PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\Darnas\\AppData\\Local\\Temp\\video2x\\tmpdy11x7bo'
```

**Comment by k4yt3x** [comment]
Oh I think I know what happened. The cleanup function might have deleted the whole video2x temp directory, and the program was trying to create a subdirectory inside the video2x temp directory when processing the second video.

I'll boot my Windows and make some changes. I'll keep you posted.

**Comment by Darnasion** [comment]
Thank you.

**Comment by k4yt3x** [comment]
@Darnasion I have just pushed a patch to address this problem.
Please clone the repo again and see if the patch solved the problem.

Sorry for the delay. It's the end of the semester so I'm a bit busy.
