### ISSUE TITLE
Ubuntu - AttributeError: module 'shlex' has no attribute 'join'

### ISSUE THREAD

**Issue by gateway** [k4yt3x/video2x#227]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|master|
|`FFmpeg`|ffmpeg version N-97298-g9f4054a0cb Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.5.0 (Ubuntu 6.5.0-2ubuntu1~18.04) 20181026
|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`|latest|

## Symptom

fails to work..

python3 video2x.py -i ~/Desktop/videos/360.mp4 -o a.mp4 -m gpu -r 2 -d waifu2x_ncnn_vulkan

yaml file points to the right waifu2x version on my system.

```
[+] INFO: Framerate: 25.0
[+] INFO: Starting to upscale extracted images
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 427, in <module>
    upscaler.run()
  File "/home/gateway/work/video/video2x/src/upscaler.py", line 348, in run
    self._upscale_frames()
  File "/home/gateway/work/video/video2x/src/upscaler.py", line 235, in _upscale_frames
    self.scale_ratio))
  File "/home/gateway/work/video/video2x/src/waifu2x_ncnn_vulkan.py", line 80, in upscale
    Avalon.debug_info(f'[upscaler] Subprocess {os.getpid()} executing: {shlex.join(execute)}')
AttributeError: module 'shlex' has no attribute 'join'
Cleaning up cache directory: /tmp/video2x/tmpgtyrdzh8
Cleaning up cache directory: /tmp/video2x/tmpezo5tzin
Cleaning up cache directory: /tmp/video2x
```

**Comment by k4yt3x** [comment]
Please use Python >= 3.8
