### ISSUE TITLE
Non Zero Exit Status 1

### ISSUE THREAD

**Issue by edberteliezer** [k4yt3x/video2x#243]
## Environment Information

|`4.0.0 Beta 3`||
|`Windows 10 1903 x64`||
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||

## Symptom
I tried both with .mkv and .mp4 both always yield this result, with or without running as admin

```
[+] INFO: Upscaling single video file: C:\Users\Edbert\Videos\2020-05-10 10-00-55.mp4
2020-05-10 10:02:29.717243 [+] INFO: Creating cache directory C:\Users\Edbert\AppData\Local\Temp\video2x
2020-05-10 10:02:29.718231 [+] INFO: Extracted frames are being saved to: C:\Users\Edbert\AppData\Local\Temp\video2x\tmpxscet1q6
2020-05-10 10:02:29.720232 [+] INFO: Upscaled frames are being saved to: C:\Users\Edbert\AppData\Local\Temp\video2x\tmpt6k0954m
[+] INFO: Reading video information
2020-05-10 10:02:29.720232 [+] INFO: Executing: Z:\Program\Video 2X\dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i C:\Users\Edbert\Videos\2020-05-10 10-00-55.mp4
2020-05-10 10:02:30.407562 [+] INFO: Executing: ['Z:\\Program\\Video 2X\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'C:\\Users\\Edbert\\Videos\\2020-05-10 10-00-55.mp4', '-pix_fmt', 'rgba64be', 'C:\\Users\\Edbert\\AppData\\Local\\Temp\\video2x\\tmpxscet1q6\\extracted_%0d.png']
2020-05-10 10:02:30.933291 [+] INFO: Main process waiting for subprocesses to exit
ffmpeg version git-2020-05-04-5767a2e Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 43.100 / 56. 43.100
  libavcodec     58. 82.100 / 58. 82.100
  libavformat    58. 42.102 / 58. 42.102
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 80.100 /  7. 80.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Edbert\Videos\2020-05-10 10-00-55.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:16.98, start: 0.000000, bitrate: 1273 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 604x340, 1068 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[h264 @ 0000025f0b025040] Using auto hwaccel type dxva2 with new default device.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\Users\Edbert\AppData\Local\Temp\video2x\tmpxscet1q6\extracted_%0d.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.42.102
    Stream #0:0(und): Video: png, rgba64be, 604x340, q=2-31, 200 kb/s, 60 fps, 60 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.82.100 png
frame= 1018 fps=8.0 q=-0.0 Lsize=N/A time=00:00:16.96 bitrate=N/A speed=0.134x
video:627183kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
2020-05-10 10:04:37.942305 [+] INFO: Subprocess 1656 exited with code 0
2020-05-10 10:04:38.044319 [+] INFO: Executing: Z:\Program\Video 2X\dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -pix_fmts
2020-05-10 10:04:38.187216 [+] INFO: {'yuv420p': 12, 'yuyv422': 16, 'rgb24': 24, 'bgr24': 24, 'yuv422p': 16, 'yuv444p': 24, 'yuv410p': 9, 'yuv411p': 12, 'gray': 8, 'monow': 1, 'monob': 1, 'pal8': 8, 'yuvj420p': 12, 'yuvj422p': 16, 'yuvj444p': 24, 'uyvy422': 16, 'uyyvyy411': 12, 'bgr8': 8, 'bgr4': 4, 'bgr4_byte': 4, 'rgb8': 8, 'rgb4': 4, 'rgb4_byte': 4, 'nv12': 12, 'nv21': 12, 'argb': 32, 'rgba': 32, 'abgr': 32, 'bgra': 32, 'gray16be': 16, 'gray16le': 16, 'yuv440p': 16, 'yuvj440p': 16, 'yuva420p': 20, 'rgb48be': 48, 'rgb48le': 48, 'rgb565be': 16, 'rgb565le': 16, 'rgb555be': 15, 'rgb555le': 15, 'bgr565be': 16, 'bgr565le': 16, 'bgr555be': 15, 'bgr555le': 15, 'vaapi_moco': 0, 'vaapi_idct': 0, 'vaapi_vld': 0, 'yuv420p16le': 24, 'yuv420p16be': 24, 'yuv422p16le': 32, 'yuv422p16be': 32, 'yuv444p16le': 48, 'yuv444p16be': 48, 'dxva2_vld': 0, 'rgb444le': 12, 'rgb444be': 12, 'bgr444le': 12, 'bgr444be': 12, 'ya8': 16, 'bgr48be': 48, 'bgr48le': 48, 'yuv420p9be': 13, 'yuv420p9le': 13, 'yuv420p10be': 15, 'yuv420p10le': 15, 'yuv422p10be': 20, 'yuv422p10le': 20, 'yuv444p9be': 27, 'yuv444p9le': 27, 'yuv444p10be': 30, 'yuv444p10le': 30, 'yuv422p9be': 18, 'yuv422p9le': 18, 'gbrp': 24, 'gbrp9be': 27, 'gbrp9le': 27, 'gbrp10be': 30, 'gbrp10le': 30, 'gbrp16be': 48, 'gbrp16le': 48, 'yuva422p': 24, 'yuva444p': 32, 'yuva420p9be': 22, 'yuva420p9le': 22, 'yuva422p9be': 27, 'yuva422p9le': 27, 'yuva444p9be': 36, 'yuva444p9le': 36, 'yuva420p10be': 25, 'yuva420p10le': 25, 'yuva422p10be': 30, 'yuva422p10le': 30, 'yuva444p10be': 40, 'yuva444p10le': 40, 'yuva420p16be': 40, 'yuva420p16le': 40, 'yuva422p16be': 48, 'yuva422p16le': 48, 'yuva444p16be': 64, 'yuva444p16le': 64, 'vdpau': 0, 'xyz12le': 36, 'xyz12be': 36, 'nv16': 16, 'nv20le': 20, 'nv20be': 20, 'rgba64be': 64, 'rgba64le': 64, 'bgra64be': 64, 'bgra64le': 64, 'yvyu422': 16, 'ya16be': 32, 'ya16le': 32, 'gbrap': 32, 'gbrap16be': 64, 'gbrap16le': 64, 'qsv': 0, 'mmal': 0, 'd3d11va_vld': 0, 'cuda': 0, '0rgb': 24, 'rgb0': 24, '0bgr': 24, 'bgr0': 24, 'yuv420p12be': 18, 'yuv420p12le': 18, 'yuv420p14be': 21, 'yuv420p14le': 21, 'yuv422p12be': 24, 'yuv422p12le': 24, 'yuv422p14be': 28, 'yuv422p14le': 28, 'yuv444p12be': 36, 'yuv444p12le': 36, 'yuv444p14be': 42, 'yuv444p14le': 42, 'gbrp12be': 36, 'gbrp12le': 36, 'gbrp14be': 42, 'gbrp14le': 42, 'yuvj411p': 12, 'bayer_bggr8': 8, 'bayer_rggb8': 8, 'bayer_gbrg8': 8, 'bayer_grbg8': 8, 'bayer_bggr16le': 16, 'bayer_bggr16be': 16, 'bayer_rggb16le': 16, 'bayer_rggb16be': 16, 'bayer_gbrg16le': 16, 'bayer_gbrg16be': 16, 'bayer_grbg16le': 16, 'bayer_grbg16be': 16, 'xvmc': 0, 'yuv440p10le': 20, 'yuv440p10be': 20, 'yuv440p12le': 24, 'yuv440p12be': 24, 'ayuv64le': 64, 'ayuv64be': 64, 'videotoolbox_vld': 0, 'p010le': 15, 'p010be': 15, 'gbrap12be': 48, 'gbrap12le': 48, 'gbrap10be': 40, 'gbrap10le': 40, 'mediacodec': 0, 'gray12be': 12, 'gray12le': 12, 'gray10be': 10, 'gray10le': 10, 'p016le': 24, 'p016be': 24, 'd3d11': 0, 'gray9be': 9, 'gray9le': 9, 'gbrpf32be': 96, 'gbrpf32le': 96, 'gbrapf32be': 128, 'gbrapf32le': 128, 'drm_prime': 0, 'opencl': 0, 'gray14be': 14, 'gray14le': 14, 'grayf32be': 32, 'grayf32le': 32, 'yuva422p12be': 36, 'yuva422p12le': 36, 'yuva444p12be': 48, 'yuva444p12le': 48, 'nv24': 24, 'nv42': 24, 'vulkan': 0, 'y210be': 20, 'y210le': 20}
[+] INFO: Framerate: 60.0
[+] INFO: Starting to upscale extracted images
2020-05-10 10:04:40.198077 [+] INFO: [upscaler] Subprocess 5384 executing: 'Z:\Program\Video 2X\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 12 --output_quality 8 --process gpu --model_dir 'Z:\Program\Video 2X\dependencies\waifu2x-caffe\models\cunet' --noise_level 3 --mode noise_scale --output_extention png --input_path 'C:\Users\Edbert\AppData\Local\Temp\video2x\tmpxscet1q6\0' --output_path 'C:\Users\Edbert\AppData\Local\Temp\video2x\tmpt6k0954m' --scale_ratio 2.0
2020-05-10 10:04:40.348593 [+] INFO: Starting progress monitor
2020-05-10 10:04:40.350591 [+] INFO: Starting upscaled image cleaner
2020-05-10 10:04:40.355591 [+] INFO: Main process waiting for subprocesses to exit
Upscaling Progress:   0%|                                                                     | 0/1018 [00:00<?, ?it/s] 変換に失敗したファイルがあります
[!] ERROR: Subprocess 11368 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
2020-05-10 10:04:41.502055 [+] INFO: Killing progress monitor
Upscaling Progress:   0%|                                                                     | 0/1018 [00:01<?, ?it/s]
2020-05-10 10:04:41.555027 [+] INFO: Killing upscaled image cleaner
Cleaning up cache directory: C:\Users\Edbert\AppData\Local\Temp\video2x\tmpxscet1q6
Cleaning up cache directory: C:\Users\Edbert\AppData\Local\Temp\video2x\tmpt6k0954m
Cleaning up cache directory: C:\Users\Edbert\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 94, in run
  File "upscaler.py", line 538, in run
  File "upscaler.py", line 516, in run
  File "upscaler.py", line 328, in _upscale_frames
  File "upscaler.py", line 320, in _upscale_frames
  File "upscaler.py", line 390, in _wait
  File "upscaler.py", line 374, in _wait
subprocess.CalledProcessError: Command '['Z:\\Program\\Video 2X\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '12', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'Z:\\Program\\Video 2X\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--input_path', 'C:\\Users\\Edbert\\AppData\\Local\\Temp\\video2x\\tmpxscet1q6\\0', '--output_path', 'C:\\Users\\Edbert\\AppData\\Local\\Temp\\video2x\\tmpt6k0954m', '--scale_ratio', '2.0']' returned non-zero exit status 1.

```

**Comment by k4yt3x** [comment]
You're using waifu2x-caffe, which requires Nvidia GPU with corresponding drivers.
Do you have them installed?

**Comment by edberteliezer** [comment]
Sorry, Let me try it on PC to double-check. Laptop's GPU is mobile GPU. I just wanted to test how fast it can go for 10 minutes of video in Laptop.

**Comment by k4yt3x** [comment]
If you want to use v2x on a non-Nvidia GPU, simply choose another driver like waifu2x-converter-cpp
