### ISSUE TITLE
unrecognized arguments: --input_path C:\Users\W\AppData\Local\Temp\video2x\tmpgxqnukw7\0 --output_path C:\Users\W\AppData\Local\Temp\video2x\tmpr5kpxub3

### ISSUE THREAD

**Issue by Bur0ri** [k4yt3x/video2x#252]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Happens everytime I try importing another video

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```[!] ERROR: Failed to parse driver argument: unrecognized arguments: --input_path C:\Users\W\AppData\Local\Temp\video2x\tmptw2omdvv\0 --output_path C:\Users\W\AppData\Local\Temp\video2x\tmpr9o0kypc
Traceback (most recent call last):
  File "video2x_gui.py", line 95, in run
  File "upscaler.py", line 398, in run
  File "upscaler.py", line 222, in _check_arguments
  File "upscaler.py", line 219, in _check_arguments
  File "C:\Users\W\AppData\Local\Temp\_MEI182642\wrappers\waifu2x_caffe.py", line 61, in parse_arguments
    return parser.parse_args(arguments)
  File "argparse.py", line 1771, in parse_args
  File "C:\Users\W\AppData\Local\Temp\_MEI182642\wrappers\waifu2x_caffe.py", line 40, in <lambda>
    parser.error = lambda message: (_ for _ in ()).throw(AttributeError(message))
  File "C:\Users\W\AppData\Local\Temp\_MEI182642\wrappers\waifu2x_caffe.py", line 40, in <genexpr>
    parser.error = lambda message: (_ for _ in ()).throw(AttributeError(message))
AttributeError: unrecognized arguments: --input_path C:\Users\W\AppData\Local\Temp\video2x\tmptw2omdvv\0 --output_path C:\Users\W\AppData\Local\Temp\video2x\tmpr9o0kypc

**Comment by k4yt3x** [comment]
Ah that's an issue that should be addressed in the newest version.
Try nightly to see if the problem persists.

**Comment by k4yt3x** [comment]
Since it's already resolved, I'll close the issue.
