### ISSUE TITLE
waifu2x-ncnn-vulkan invalid GPU device

### ISSUE THREAD

**Issue by vichoxthepanda** [k4yt3x/video2x#266]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`||
|`FFmpeg`||
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`||

## Symptom

Briefly describe what's going on.

## Screenshots or Error Messages

Please paste screenshots or error messages here.
Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```Upscaling Progress:   0%|                                                                       | 0/56 [00:00<?, ?it/s]
[0 AMD Radeon HD 8600/8700M]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon HD 8600/8700M]  buglssc=0  bugihfa=0
[0 AMD Radeon HD 8600/8700M]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
invalid gpu device
[!] ERROR: Subprocess 12628 exited with code 4294967295
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
2020-05-22 14:10:19.200441 [+] INFO: Killing progress monitor
Upscaling Progress:   0%|                                                                       | 0/56 [00:01<?, ?it/s]
2020-05-22 14:10:19.998679 [+] INFO: Killing upscaled image cleaner
Cleaning up cache directory: C:\Users\vichox\AppData\Local\Temp\video2x\tmp85mmk7j_
Cleaning up cache directory: C:\Users\vichox\AppData\Local\Temp\video2x\tmpsyg3gxh8
Cleaning up cache directory: C:\Users\vichox\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 100, in run
  File "upscaler.py", line 605, in run
  File "upscaler.py", line 525, in run
  File "upscaler.py", line 317, in _upscale_frames
  File "upscaler.py", line 309, in _upscale_frames
  File "upscaler.py", line 379, in _wait
  File "upscaler.py", line 363, in _wait
subprocess.CalledProcessError: Command '['C:\\Users\\vichox\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\vichox\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\models-upconv_7_anime_style_art_rgb', '-g', '1', '-j', '1:1:1', '-i', 'C:\\Users\\vichox\\AppData\\Local\\Temp\\video2x\\tmp85mmk7j_', '-o', 'C:\\Users\\vichox\\AppData\\Local\\Temp\\video2x\\tmpsyg3gxh8']' returned non-zero exit status 4294967295.
```

**Comment by k4yt3x** [comment]
> invalid gpu device

**Comment by k4yt3x** [comment]
check what GPU devices you have and which one you've picked
