### ISSUE TITLE
An exception occurred

### ISSUE THREAD

**Issue by gmonteir** [K4YT3X/video2x#27]
I'm getting this error when running the program:

```
[!] ERROR: An exception occurred
Traceback (most recent call last):
  File "video2x.py", line 357, in <module>
    video2x()
  File "video2x.py", line 207, in video2x
    ffmpeg_arguments.append('-hwaccel {}'.format(ffmpeg_hwaccel))
AttributeError: 'str' object has no attribute 'append'
```

**Comment by K4YT3X** [comment]
Thanks for reporting this bug. I have just pushed the patch to this bug. It should be fixed by now.
