### ISSUE TITLE
waifu2x-caffe error

### ISSUE THREAD

**Issue by SnappierSoap318** [k4yt3x/video2x#322]
- **Video2X release version**: 4.6.0
- **GUI version**:2.7.1

Log:

```
[32m[+] INFO: Loading files into processing queue[0m
[90m2020-08-01 22:01:59.718007 [+] INFO: Input path(s): C:\Users\adwai\Videos\Poochakoru Mookuthi.mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-08-01 22:01:59.725007 [+] INFO: Input file: C:\Users\adwai\Videos\Poochakoru Mookuthi.mp4[0m
[90m2020-08-01 22:01:59.726008 [+] INFO: Creating cache directory C:\Users\adwai\AppData\Local\Temp\video2x[0m
[90m2020-08-01 22:01:59.726008 [+] INFO: Extracted frames are being saved to: C:\Users\adwai\AppData\Local\Temp\video2x\tmptbmyv25b[0m
[90m2020-08-01 22:01:59.727007 [+] INFO: Upscaled frames are being saved to: C:\Users\adwai\AppData\Local\Temp\video2x\tmpy8adqp0v[0m
[32m[+] INFO: Reading video information[0m
[90m2020-08-01 22:01:59.728007 [+] INFO: Executing: 'D:\Soft\video2x-4.6.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe' -v quiet -print_format json -show_format -show_streams -i 'C:\Users\adwai\Videos\Poochakoru Mookuthi.mp4'[0m
[32m[+] INFO: Framerate: 60.0[0m
[90m2020-08-01 22:02:00.231009 [+] INFO: Executing: 'D:\Soft\video2x-4.6.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffmpeg' -hwaccel auto -y -i 'C:\Users\adwai\Videos\Poochakoru Mookuthi.mp4' -pix_fmt rgba64be 'C:\Users\adwai\AppData\Local\Temp\video2x\tmptbmyv25b\extracted_%0d.png'[0m
[90m2020-08-01 22:02:00.641033 [+] INFO: Main process waiting for subprocesses to exit[0m
[90m2020-08-01 22:09:22.381033 [+] INFO: Subprocess 18136 exited with code 0[0m
[90m2020-08-01 22:09:22.483893 [+] INFO: Executing: 'D:\Soft\video2x-4.6.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe' -v quiet -pix_fmts[0m
[90m2020-08-01 22:09:23.769812 [+] INFO: {'yuv420p': 12, 'yuyv422': 16, 'rgb24': 24, 'bgr24': 24, 'yuv422p': 16, 'yuv444p': 24, 'yuv410p': 9, 'yuv411p': 12, 'gray': 8, 'monow': 1, 'monob': 1, 'pal8': 8, 'yuvj420p': 12, 'yuvj422p': 16, 'yuvj444p': 24, 'uyvy422': 16, 'uyyvyy411': 12, 'bgr8': 8, 'bgr4': 4, 'bgr4_byte': 4, 'rgb8': 8, 'rgb4': 4, 'rgb4_byte': 4, 'nv12': 12, 'nv21': 12, 'argb': 32, 'rgba': 32, 'abgr': 32, 'bgra': 32, 'gray16be': 16, 'gray16le': 16, 'yuv440p': 16, 'yuvj440p': 16, 'yuva420p': 20, 'rgb48be': 48, 'rgb48le': 48, 'rgb565be': 16, 'rgb565le': 16, 'rgb555be': 15, 'rgb555le': 15, 'bgr565be': 16, 'bgr565le': 16, 'bgr555be': 15, 'bgr555le': 15, 'vaapi_moco': 0, 'vaapi_idct': 0, 'vaapi_vld': 0, 'yuv420p16le': 24, 'yuv420p16be': 24, 'yuv422p16le': 32, 'yuv422p16be': 32, 'yuv444p16le': 48, 'yuv444p16be': 48, 'dxva2_vld': 0, 'rgb444le': 12, 'rgb444be': 12, 'bgr444le': 12, 'bgr444be': 12, 'ya8': 16, 'bgr48be': 48, 'bgr48le': 48, 'yuv420p9be': 13, 'yuv420p9le': 13, 'yuv420p10be': 15, 'yuv420p10le': 15, 'yuv422p10be': 20, 'yuv422p10le': 20, 'yuv444p9be': 27, 'yuv444p9le': 27, 'yuv444p10be': 30, 'yuv444p10le': 30, 'yuv422p9be': 18, 'yuv422p9le': 18, 'gbrp': 24, 'gbrp9be': 27, 'gbrp9le': 27, 'gbrp10be': 30, 'gbrp10le': 30, 'gbrp16be': 48, 'gbrp16le': 48, 'yuva422p': 24, 'yuva444p': 32, 'yuva420p9be': 22, 'yuva420p9le': 22, 'yuva422p9be': 27, 'yuva422p9le': 27, 'yuva444p9be': 36, 'yuva444p9le': 36, 'yuva420p10be': 25, 'yuva420p10le': 25, 'yuva422p10be': 30, 'yuva422p10le': 30, 'yuva444p10be': 40, 'yuva444p10le': 40, 'yuva420p16be': 40, 'yuva420p16le': 40, 'yuva422p16be': 48, 'yuva422p16le': 48, 'yuva444p16be': 64, 'yuva444p16le': 64, 'vdpau': 0, 'xyz12le': 36, 'xyz12be': 36, 'nv16': 16, 'nv20le': 20, 'nv20be': 20, 'rgba64be': 64, 'rgba64le': 64, 'bgra64be': 64, 'bgra64le': 64, 'yvyu422': 16, 'ya16be': 32, 'ya16le': 32, 'gbrap': 32, 'gbrap16be': 64, 'gbrap16le': 64, 'qsv': 0, 'mmal': 0, 'd3d11va_vld': 0, 'cuda': 0, '0rgb': 24, 'rgb0': 24, '0bgr': 24, 'bgr0': 24, 'yuv420p12be': 18, 'yuv420p12le': 18, 'yuv420p14be': 21, 'yuv420p14le': 21, 'yuv422p12be': 24, 'yuv422p12le': 24, 'yuv422p14be': 28, 'yuv422p14le': 28, 'yuv444p12be': 36, 'yuv444p12le': 36, 'yuv444p14be': 42, 'yuv444p14le': 42, 'gbrp12be': 36, 'gbrp12le': 36, 'gbrp14be': 42, 'gbrp14le': 42, 'yuvj411p': 12, 'bayer_bggr8': 8, 'bayer_rggb8': 8, 'bayer_gbrg8': 8, 'bayer_grbg8': 8, 'bayer_bggr16le': 16, 'bayer_bggr16be': 16, 'bayer_rggb16le': 16, 'bayer_rggb16be': 16, 'bayer_gbrg16le': 16, 'bayer_gbrg16be': 16, 'bayer_grbg16le': 16, 'bayer_grbg16be': 16, 'xvmc': 0, 'yuv440p10le': 20, 'yuv440p10be': 20, 'yuv440p12le': 24, 'yuv440p12be': 24, 'ayuv64le': 64, 'ayuv64be': 64, 'videotoolbox_vld': 0, 'p010le': 15, 'p010be': 15, 'gbrap12be': 48, 'gbrap12le': 48, 'gbrap10be': 40, 'gbrap10le': 40, 'mediacodec': 0, 'gray12be': 12, 'gray12le': 12, 'gray10be': 10, 'gray10le': 10, 'p016le': 24, 'p016be': 24, 'd3d11': 0, 'gray9be': 9, 'gray9le': 9, 'gbrpf32be': 96, 'gbrpf32le': 96, 'gbrapf32be': 128, 'gbrapf32le': 128, 'drm_prime': 0, 'opencl': 0, 'gray14be': 14, 'gray14le': 14, 'grayf32be': 32, 'grayf32le': 32, 'yuva422p12be': 36, 'yuva422p12le': 36, 'yuva444p12be': 48, 'yuva444p12le': 48, 'nv24': 24, 'nv42': 24, 'vulkan': 0, 'y210be': 20, 'y210le': 20}[0m
[32m[+] INFO: Starting to upscale extracted frames[0m
[90m2020-08-01 22:09:30.947993 [+] INFO: [upscaler] Subprocess 17904 executing: 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 64 --output_quality 8 --process gpu --model_dir 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\models\cunet' --noise_level 3 --mode noise_scale --output_extention png --scale_ratio 2.0 --input_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmptbmyv25b\3' --output_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmpy8adqp0v'[0m
[90m2020-08-01 22:09:31.485803 [+] INFO: [upscaler] Subprocess 17904 executing: 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 64 --output_quality 8 --process gpu --model_dir 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\models\cunet' --noise_level 3 --mode noise_scale --output_extention png --scale_ratio 2.0 --input_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmptbmyv25b\4' --output_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmpy8adqp0v'[0m
[90m2020-08-01 22:09:31.685258 [+] INFO: [upscaler] Subprocess 17904 executing: 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 64 --output_quality 8 --process gpu --model_dir 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\models\cunet' --noise_level 3 --mode noise_scale --output_extention png --scale_ratio 2.0 --input_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmptbmyv25b\5' --output_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmpy8adqp0v'[0m
[90m2020-08-01 22:09:31.882613 [+] INFO: [upscaler] Subprocess 17904 executing: 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 64 --output_quality 8 --process gpu --model_dir 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\models\cunet' --noise_level 3 --mode noise_scale --output_extention png --scale_ratio 2.0 --input_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmptbmyv25b\0' --output_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmpy8adqp0v'[0m
[90m2020-08-01 22:09:32.081592 [+] INFO: [upscaler] Subprocess 17904 executing: 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 64 --output_quality 8 --process gpu --model_dir 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\models\cunet' --noise_level 3 --mode noise_scale --output_extention png --scale_ratio 2.0 --input_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmptbmyv25b\1' --output_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmpy8adqp0v'[0m
[90m2020-08-01 22:09:32.282646 [+] INFO: [upscaler] Subprocess 17904 executing: 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 64 --output_quality 8 --process gpu --model_dir 'D:\Soft\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\models\cunet' --noise_level 3 --mode noise_scale --output_extention png --scale_ratio 2.0 --input_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmptbmyv25b\2' --output_path 'C:\Users\adwai\AppData\Local\Temp\video2x\tmpy8adqp0v'[0m
[90m2020-08-01 22:09:32.486622 [+] INFO: Starting progress monitor[0m
[90m2020-08-01 22:09:32.488624 [+] INFO: Starting upscaled image cleaner[0m
[90m2020-08-01 22:09:32.489621 [+] INFO: Main process waiting for subprocesses to exit[0m

Upscaling Progress:   0%|                                                                    | 0/12111 [00:00<?, ?it/s]
Upscaling Progress:   0%|                                                                    | 0/12111 [00:01<?, ?it/s]
Upscaling Progress:   0%|                                                                    | 0/12111 [00:02<?, ?it/s]
Upscaling Progress:   0%|                                                                    | 0/12111 [00:03<?, ?it/s]
Upscaling Progress:   0%|                                                                    | 0/12111 [00:04<?, ?it/s]
Upscaling Progress:   0%|                                                                    | 0/12111 [00:05<?, ?it/s][31m[1m[!] ERROR: Subprocess 16244 exited with code 3221226505[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
[90m2020-08-01 22:09:37.759287 [+] INFO: Killing progress monitor[0m

Upscaling Progress:   0%|                                                                    | 0/12111 [00:06<?, ?it/s]
[90m2020-08-01 22:09:38.720905 [+] INFO: Killing upscaled image cleaner[0m
Cleaning up cache directory: C:\Users\adwai\AppData\Local\Temp\video2x\tmptbmyv25b
Cleaning up cache directory: C:\Users\adwai\AppData\Local\Temp\video2x\tmpy8adqp0v
Cleaning up cache directory: C:\Users\adwai\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 104, in run
  File "upscaler.py", line 667, in run
  File "upscaler.py", line 596, in run
  File "upscaler.py", line 339, in _upscale_frames
  File "upscaler.py", line 331, in _upscale_frames
  File "upscaler.py", line 401, in _wait
  File "upscaler.py", line 385, in _wait
subprocess.CalledProcessError: Command '['D:\\Soft\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '64', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'D:\\Soft\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '2.0', '--input_path', 'C:\\Users\\adwai\\AppData\\Local\\Temp\\video2x\\tmptbmyv25b\\1', '--output_path', 'C:\\Users\\adwai\\AppData\\Local\\Temp\\video2x\\tmpy8adqp0v']' returned non-zero exit status 3221226505.
```
screenshot:

![image](https://user-images.githubusercontent.com/42905211/89106054-3fb65500-d444-11ea-9127-def6ba33d7b4.png)

**Comment by k4yt3x** [comment]
Do you have NVIDIA GPU with its drivers installed?

**Comment by SnappierSoap318** [comment]
Yes the latest version, GPU

**Comment by k4yt3x** [comment]
This error looks very much like a driver issue. Are you sure that the driver is the latest?

**Comment by SnappierSoap318** [comment]
![image](https://user-images.githubusercontent.com/42905211/89107053-e4886080-d44b-11ea-884e-9c5be76efe19.png)

**Comment by SnappierSoap318** [comment]
is the game ready drivers gonna be an issue with the program?

**Comment by k4yt3x** [comment]
The driver looks fine. Thanks for double-checking.
I'm not quite sure why waifu2x-caffe is failing. Could you please try waifu2x-ncnn-vulkan?

**Comment by SnappierSoap318** [comment]
it works with Vulkan, when i tried increasing the number of processes it just straight up crashes my system.

**Comment by k4yt3x** [comment]
ML-based implementations are very resource-consuming. Launching multiple instances also doesn't significantly improve the processing speed. I'd recommend to use just a single process.
