### ISSUE TITLE
Crashes on output

### ISSUE THREAD

**Issue by greevak** [k4yt3x/video2x#329]
## Component Versions
![dd](https://user-images.githubusercontent.com/38337258/90231697-381f8480-de24-11ea-8594-37d2f06c118d.png)

- **Video2X release version*4.6.0*:
- **Upscaler version*?*:
- **GUI version*2.7.0*:
- **CLI version**:

## Symptom
Crashes on frame output.

I have an nvidia graphics card (GTX 1050) with the latest drivers installed "451.67" And it still crashes for some reason.
I tried with many different images and the issues is still occurding.

## Error Log or Screenshots

```[32m[+] INFO: Loading files into processing queue[0m
[90m2020-08-14 11:44:02.995927 [+] INFO: Input path(s): E:\koky_outpufinal.jpg[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-08-14 11:44:03.001911 [+] INFO: Input file: E:\koky_outpufinal.jpg[0m
[32m[+] INFO: Starting to upscale image[0m
[90m2020-08-14 11:44:03.001911 [+] INFO: [upscaler] Subprocess 5104 executing: 'E:\app.publish\video2x-4.6.0-win32-light\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 12 --output_quality 8 --process gpu --model_dir 'E:\app.publish\video2x-4.6.0-win32-light\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\models\cunet' --noise_level 3 --mode noise_scale --output_extention png --scale_ratio 4.0 --input_path 'E:\koky_outpufinal.jpg' --output_path 'E:\koky_outpufinal_output.png'[0m
[90m2020-08-14 11:44:03.150505 [+] INFO: Main process waiting for subprocesses to exit[0m
[31m[1m[!] ERROR: Subprocess 13000 exited with code 3221226505[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
Traceback (most recent call last):
  File "video2x_gui.py", line 104, in run
  File "upscaler.py", line 667, in run
  File "upscaler.py", line 534, in run
  File "upscaler.py", line 401, in _wait
  File "upscaler.py", line 385, in _wait
subprocess.CalledProcessError: Command '['E:\\app.publish\\video2x-4.6.0-win32-light\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '12', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'E:\\app.publish\\video2x-4.6.0-win32-light\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '4.0', '--input_path', 'E:\\koky_outpufinal.jpg', '--output_path', 'E:\\koky_outpufinal_output.png']' returned non-zero exit status 3221226505.```


Here is the log for a different file with the same issue:


```[32m[+] INFO: Loading files into processing queue[0m
[90m2020-08-14 11:52:44.290260 [+] INFO: Input path(s): C:\Users\PC\Pictures\a.jpg[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-08-14 11:52:44.295218 [+] INFO: Input file: C:\Users\PC\Pictures\a.jpg[0m
[32m[+] INFO: Starting to upscale image[0m
[90m2020-08-14 11:52:44.295218 [+] INFO: [upscaler] Subprocess 14160 executing: 'E:\app.publish\video2x-4.6.0-win32-light\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui' --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 12 --output_quality 8 --process gpu --model_dir 'E:\app.publish\video2x-4.6.0-win32-light\video2x-4.6.0-win32-full\dependencies\waifu2x-caffe\models\cunet' --noise_level 3 --mode noise_scale --output_extention png --scale_ratio 4.0 --input_path 'C:\Users\PC\Pictures\a.jpg' --output_path 'C:\Users\PC\Pictures\a_output.png'[0m
[90m2020-08-14 11:52:44.443818 [+] INFO: Main process waiting for subprocesses to exit[0m
[31m[1m[!] ERROR: Subprocess 7364 exited with code 3221226505[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
Traceback (most recent call last):
  File "video2x_gui.py", line 104, in run
  File "upscaler.py", line 667, in run
  File "upscaler.py", line 534, in run
  File "upscaler.py", line 401, in _wait
  File "upscaler.py", line 385, in _wait
subprocess.CalledProcessError: Command '['E:\\app.publish\\video2x-4.6.0-win32-light\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '12', '--output_quality', '8', '--process', 'gpu', '--model_dir', 'E:\\app.publish\\video2x-4.6.0-win32-light\\video2x-4.6.0-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_ratio', '4.0', '--input_path', 'C:\\Users\\PC\\Pictures\\a.jpg', '--output_path', 'C:\\Users\\PC\\Pictures\\a_output.png']' returned non-zero exit status 3221226505.```

**Comment by lagnap** [comment]
Hi @greevak 
I believe you are out of VRAM. (GPU RAM)
How much vram do you have? 2GB? 

Try setting _processes_ to 1 if not already 
also reduce _Scale_ down to 2 if possible, I think you have it set to 4.

I would give _SRMD_ a shot, it seams to use less vram for me.

(in the screen shot I have processes set to 2 to use up vram)
![2020-08-14-c](https://user-images.githubusercontent.com/69681429/90254419-0b03be00-de86-11ea-84ba-1a6dc23d70f4.PNG)
