### ISSUE TITLE
RealSR broken in docker container?

### ISSUE THREAD

**Issue by YacobBY** [k4yt3x/video2x#352]
## Component Versions

- **Video2X release version**: 4.2.0
- **Upscaler version**:
- **GUI version**:
- **CLI version**:  Version 4.2.0

## Symptom

RealSR Vulkan does not seem to work correctly with the Ubuntu Docker image. When using any other driver (changing realsr_ncnn_vulkan for waifu2x_ncnn_vulkan / srmd_ncnn_vulkan) it works fine. Is there an argument mismatch somewhere?

## Error Log or Screenshots

![Screenshot](https://user-images.githubusercontent.com/30029456/92611037-a5ee8d00-f2b8-11ea-8877-d42b52814acc.png)

[!] ERROR: Failed to parse driver argument: argument -s: invalid choice: 2 (choose from 4)
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "/video2x/src/video2x.py", line 261, in <module>
    upscaler.run()
  File "/video2x/src/upscaler.py", line 515, in run
    self._check_arguments()
  File "/video2x/src/upscaler.py", line 251, in _check_arguments
    raise e
  File "/video2x/src/upscaler.py", line 248, in _check_arguments
    DriverWrapperMain.parse_arguments(driver_arguments)
  File "/video2x/src/wrappers/realsr_ncnn_vulkan.py", line 53, in parse_arguments
    return parser.parse_args(arguments)
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1819, in parse_known_args
    self.error(str(err))
  File "/video2x/src/wrappers/realsr_ncnn_vulkan.py", line 42, in <lambda>
    parser.error = lambda message: (_ for _ in ()).throw(AttributeError(message))
  File "/video2x/src/wrappers/realsr_ncnn_vulkan.py", line 42, in <genexpr>
    parser.error = lambda message: (_ for _ in ()).throw(AttributeError(message))
AttributeError: argument -s: invalid choice: 2 (choose from 4)

**Comment by k4yt3x** [comment]
Ah no it's not broken. It's just that RealSR only supports 4x upscaling, not 2x.
You can see the red error message.
Arbitrary upscaling support is on the way though (already available in the newest commit).
