### ISSUE TITLE
waifu2x-ncnn-vulkan error

### ISSUE THREAD

**Issue by SloppyPuppy** [k4yt3x/video2x#375]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- 2.8.0:
- **Upscaler version**:
- 2.8.0:
- **CLI version**:

## Symptom

I do not know where to find the versions but its binary that I downloaded 30 minutes ago from posting of this thread

## Error Log or Screenshots

```
[32m[+] INFO: Loading files into processing queue[0m
[90m2020-10-02 19:09:36.800278 [+] INFO: Input path(s): D:\VideoX2\Input\y2mate.com - Stripping Midget_360p.mp4[0m
[90m2020-10-02 19:09:36.802757 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-10-02 19:09:36.806229 [+] INFO: Input file: D:\VideoX2\Input\y2mate.com - Stripping Midget_360p.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2020-10-02 19:09:36.806754 [+] INFO: Executing: D:\VideoX2\dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i D:\VideoX2\Input\y2mate.com - Stripping Midget_360p.mp4[0m
[90m2020-10-02 19:09:37.462550 [+] INFO: Extracted frames are being saved to: C:\Users\SLOPPY~1\AppData\Local\Temp\video2x\tmpq0o3tkuq[0m
[90m2020-10-02 19:09:37.463542 [+] INFO: Upscaled frames are being saved to: C:\Users\SLOPPY~1\AppData\Local\Temp\video2x\tmpp2ousu48[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[32m[+] INFO: Calculating scaling parameters[0m
[90m2020-10-02 19:09:37.464851 [+] INFO: Framerate: 30.0[0m
[90m2020-10-02 19:09:37.465349 [+] INFO: Width: 320[0m
[90m2020-10-02 19:09:37.465349 [+] INFO: Height: 240[0m
[90m2020-10-02 19:09:37.465844 [+] INFO: Total number of frames: 2330[0m
[90m2020-10-02 19:09:37.466340 [+] INFO: Output width: 960[0m
[90m2020-10-02 19:09:37.466340 [+] INFO: Output height: 720[0m
[90m2020-10-02 19:09:37.466340 [+] INFO: Required scale ratio: 3.0[0m
[90m2020-10-02 19:09:37.466836 [+] INFO: Upscaling jobs queue: [2, 2][0m
[90m2020-10-02 19:09:37.466836 [+] INFO: Executing: D:\VideoX2\dependencies\ffmpeg-latest-win64-static\bin\ffmpeg -hwaccel auto -y -i D:\VideoX2\Input\y2mate.com - Stripping Midget_360p.mp4 -pix_fmt rgb24 C:\Users\SLOPPY~1\AppData\Local\Temp\video2x\tmpq0o3tkuq\extracted_%0d.png[0m
[90m2020-10-02 19:09:37.511359 [+] INFO: Main process waiting for subprocesses to exit[0m
[90m2020-10-02 19:09:44.469227 [+] INFO: Subprocess 17100 exited with code 0[0m
[32m[+] INFO: Starting to upscale extracted frames[0m
[90m2020-10-02 19:09:44.596907 [+] INFO: [upscaler] Subprocess 2916 executing: D:\VideoX2\dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan -n 2 -s 2 -t 400 -m D:\VideoX2\dependencies\waifu2x-ncnn-vulkan\models-cunet -g 0 -j 1:1:1 -i C:\Users\SLOPPY~1\AppData\Local\Temp\video2x\tmpq0o3tkuq -o C:\Users\SLOPPY~1\AppData\Local\Temp\video2x\tmpp2ousu48[0m
[90m2020-10-02 19:09:44.726542 [+] INFO: Starting progress monitor[0m
[90m2020-10-02 19:09:44.727534 [+] INFO: Starting upscaled image cleaner[0m
[90m2020-10-02 19:09:44.728526 [+] INFO: Main process waiting for subprocesses to exit[0m

Processing: y2mate.com - Stripping Midget_360p.mp4 (pass 1/2):   0%|                          | 0/2330 [00:00<?, ?it/s][31m[1m[!] ERROR: Subprocess 12196 exited with code 4294967295[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
[90m2020-10-02 19:09:44.931716 [+] INFO: Killing progress monitor[0m

Processing: y2mate.com - Stripping Midget_360p.mp4 (pass 1/2):   0%|                          | 0/2330 [00:01<?, ?it/s]
[90m2020-10-02 19:09:45.743922 [+] INFO: Killing upscaled image cleaner[0m
Cleaning up cache directory: C:\Users\SLOPPY~1\AppData\Local\Temp\video2x\tmpq0o3tkuq
Cleaning up cache directory: C:\Users\SLOPPY~1\AppData\Local\Temp\video2x\tmpp2ousu48
Cleaning up cache directory: C:\Users\SLOPPY~1\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 802, in run
  File "upscaler.py", line 692, in run
  File "upscaler.py", line 347, in _upscale_frames
  File "upscaler.py", line 339, in _upscale_frames
  File "upscaler.py", line 409, in _wait
  File "upscaler.py", line 393, in _wait
subprocess.CalledProcessError: Command '['D:\\VideoX2\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'D:\\VideoX2\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-i', 'C:\\Users\\SLOPPY~1\\AppData\\Local\\Temp\\video2x\\tmpq0o3tkuq', '-o', 'C:\\Users\\SLOPPY~1\\AppData\\Local\\Temp\\video2x\\tmpp2ousu48']' returned non-zero exit status 4294967295.
```

**Comment by k4yt3x** [comment]
I'm not quite sure where the problem is since the log is incomplete due to an error in the logging system. Before I fix that, you can try upgrading your GPU drivers.

**Comment by SloppyPuppy** [comment]
Okay thank you! I did reinstall Cuda 10.0 drivers to be compatible with a
different project

пет, 2. окт 2020. у 20:13 K4YT3X <notifications@github.com> је написао/ла:
