### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xaiyeon** [k4yt3x/video2x#386]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.7.0
- **Upscaler version**: 4.4.0
- **GUI version**: 2.8.0
- **CLI version**: N/A

## Symptom

Tried to convert an MP4 video

## Error Log or Screenshots

```
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[32m[+] INFO: Calculating scaling parameters[0m
[90m2020-10-15 18:41:23.274041 [+] INFO: Framerate: 30.0[0m
[90m2020-10-15 18:41:23.275043 [+] INFO: Width: 3840[0m
[90m2020-10-15 18:41:23.277038 [+] INFO: Height: 2160[0m
[90m2020-10-15 18:41:23.278040 [+] INFO: Total number of frames: 19500[0m
[90m2020-10-15 18:41:23.279039 [+] INFO: Output width: 3840[0m
[90m2020-10-15 18:41:23.280040 [+] INFO: Output height: 2160[0m
[90m2020-10-15 18:41:23.281040 [+] INFO: Required scale ratio: 1.0[0m
[90m2020-10-15 18:41:23.282038 [+] INFO: Upscaling jobs queue: [][0m
[90m2020-10-15 18:41:23.283038 [+] INFO: Executing: A:\Ai\video2x-4.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffmpeg -hwaccel auto -y -i A:\Ai\input\PSO2 - Rare Drop Koi Koi (4K Raytracing).mp4 -pix_fmt rgb24 C:\Users\xxxx\AppData\Local\Temp\video2x\tmpnrolgzry\extracted_%0d.png[0m
[90m2020-10-15 18:41:23.295041 [+] INFO: Main process waiting for subprocesses to exit[0m
[90m2020-10-15 19:22:34.111467 [+] INFO: Subprocess 5484 exited with code 0[0m
[32m[+] INFO: Starting to upscale extracted frames[0m
Cleaning up cache directory: C:\Users\xxxx\AppData\Local\Temp\video2x\tmpnrolgzry
Cleaning up cache directory: C:\Users\xxxx\AppData\Local\Temp\video2x\tmpv63samj6
Cleaning up cache directory: C:\Users\xxxx\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 802, in run
  File "upscaler.py", line 691, in run
IndexError: list index out of range
```

**Comment by jitsuCM** [comment]
Happens reliably for me with 1.0 scale ratio

**Comment by jitsuCM** [comment]
#389 Kind of low effort, but does it job, allowing for 1.0 upscale jobs

**Comment by k4yt3x** [comment]
PR has been merged. Closing this issue.
