### ISSUE TITLE
ERROR when upscaling images. AttributeError: 'module' object has no attribute 'DEVNULL'

### ISSUE THREAD

**Issue by Kaisogen** [K4YT3X/video2x#4]
```
[+] INFO: Framerate: 24.0
[+] INFO: Starting to upscale extracted images
Upscaling: extracted_1.png:   0%|                                                            | 0/15666 [00:00<?, ?it/s][!] ERROR: An exception occurred
Traceback (most recent call last):
  File "video2x.py", line 212, in <module>
    video2x()
  File "video2x.py", line 164, in video2x
    width, int(args.factor) * height)
  File "C:\Users\Blarg\Downloads\VideoUpscaler\video2x\waifu2x.py", line 47, in upscale
    subprocess.call(execute, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
AttributeError: 'module' object has no attribute 'DEVNULL'
Exception KeyError: KeyError(<weakref at 000000000347E688; to 'tqdm' at 00000000039207F0>,) in <bound method tqdm.__del__ of Upscaling: extracted_1.png:   0%|                                                            | 0/15666 [00:00<?, ?it/s]> ignored
```

**Comment by K4YT3X** [comment]
I have edited your issue so it's easier to read.
Can you please tell me which version of python you're using? I'm trying to locate the problem.

**Comment by K4YT3X** [comment]
No response from issue owner.
