### ISSUE TITLE
Got Error while processing ".mpg" files.

### ISSUE THREAD

**Issue by QuantumLiu** [k4yt3x/video2x#418]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
Video2X 4.7.0
- **Upscaler version**:
ALL
- **GUI version**:
2.8
- **CLI version**:

## Symptom

Got error when I started to processing a ".mpg" file, which has following info exported by my local ffprobe:
  ```
 Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x480 [SAR 8:9 DAR 4:3], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:2[0x1c0]: Audio: mp2, 48000 Hz, stereo, s16p, 384 kb/s
    Stream #0:3[0x1c1]: Audio: mp2, 48000 Hz, stereo, s16p, 384 kb/s
```
It seems got error when trying to get number of frames of the input video.
I converted it into h264/mp4, and video2x process it well.

## Error Log or Screenshots

```
[32m[+] INFO: 正在将文件添加到处理队列中[0m
[90m2020-11-24 10:59:34.760251 [+] INFO: 输入路径：F:\Videos\lr_mv\lq_mv\7000992.mpg[0m
[90m2020-11-24 10:59:34.762212 [+] INFO: 文件 MIME 类型：video/mpeg[0m
[32m[+] INFO: 文件已添加到处理队列[0m
[90m2020-11-24 10:59:34.767035 [+] INFO: 输入文件：F:\Videos\lr_mv\lq_mv\7000992.mpg[0m
[32m[+] INFO: 正在读取视频信息[0m
[90m2020-11-24 10:59:34.767035 [+] INFO: Executing: E:\video2x-4.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i F:\Videos\lr_mv\lq_mv\7000992.mpg[0m
[90m2020-11-24 10:59:34.881318 [+] INFO: 提取的帧将被保存到：G:\cache\tmp26ioozqb[0m
[90m2020-11-24 10:59:34.882203 [+] INFO: 已放大的帧将被保存到：G:\cache\tmpb4x3grlq[0m
[32m[+] INFO: 开始放大视频/GIF[0m
[32m[+] INFO: 正在获取文件中的总帧数[0m
[90m2020-11-24 10:59:34.883180 [+] INFO: Executing: E:\video2x-4.7.0-win32-full\dependencies\ffmpeg-latest-win64-static\bin\ffprobe -v quiet -count_frames -select_streams v:1 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 F:\Videos\lr_mv\lq_mv\7000992.mpg[0m
清理缓存目录：G:\cache\tmp26ioozqb
清理缓存目录：G:\cache\tmpb4x3grlq
清理缓存目录：G:\cache
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 802, in run
  File "upscaler.py", line 589, in run
  File "wrappers\ffmpeg.py", line 106, in get_number_of_frames
ValueError: invalid literal for int() with base 10: ''

```

**Comment by QuantumLiu** [comment]
Solved by reencode videos

**Comment by k4yt3x** [comment]
Actually this might be an issue. I'll take a deeper look at it later.

**Comment by k4yt3x** [comment]
Fixed in the newest commit.
