### ISSUE TITLE
invalid literal for int() with base 10: '47001\r\n47001'

### ISSUE THREAD

**Issue by Sir-Antonic** [k4yt3x/video2x#427]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:
- **Upscaler version**:
- **GUI version**: 2.8.1
- **CLI version**:

## Symptom

I get an error when trying to start the upscale on default settings

## Error Log or Screenshots

https://pastebin.com/k2VSgPB9

```
[32m[+] INFO: Loading files into processing queue[0m
[90m2020-12-15 08:58:37.824747 [+] INFO: Input path(s): D:\2.0rc\Samoa Joe vs Kenta Kobashi October 1st, 2005.mp4[0m
[90m2020-12-15 08:58:37.827739 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-12-15 08:58:37.829733 [+] INFO: Input file: D:\2.0rc\Samoa Joe vs Kenta Kobashi October 1st, 2005.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2020-12-15 08:58:37.830731 [+] INFO: Executing: C:\video2x\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i D:\2.0rc\Samoa Joe vs Kenta Kobashi October 1st, 2005.mp4[0m
[90m2020-12-15 08:58:38.379264 [+] INFO: Creating cache directory C:\Users\sirlo\AppData\Local\Temp\video2x[0m
[90m2020-12-15 08:58:38.379264 [+] INFO: Extracted frames are being saved to: C:\Users\sirlo\AppData\Local\Temp\video2x\tmp2bnawbjs[0m
[90m2020-12-15 08:58:38.379264 [+] INFO: Upscaled frames are being saved to: C:\Users\sirlo\AppData\Local\Temp\video2x\tmpwqqqqxyl[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[90m2020-12-15 08:58:38.380262 [+] INFO: Executing: C:\video2x\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 D:\2.0rc\Samoa Joe vs Kenta Kobashi October 1st, 2005.mp4[0m
Cleaning up cache directory: C:\Users\sirlo\AppData\Local\Temp\video2x\tmp2bnawbjs
Cleaning up cache directory: C:\Users\sirlo\AppData\Local\Temp\video2x\tmpwqqqqxyl
Cleaning up cache directory: C:\Users\sirlo\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 810, in run
  File "upscaler.py", line 593, in run
  File "wrappers\ffmpeg.py", line 107, in get_number_of_frames
ValueError: invalid literal for int() with base 10: '47001\r\n47001'
[32m[+] INFO: Loading files into processing queue[0m
[90m2020-12-15 09:02:15.526916 [+] INFO: Input path(s): D:\2.0rc\1.mp4[0m
[90m2020-12-15 09:02:15.529908 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-12-15 09:02:15.531903 [+] INFO: Input file: D:\2.0rc\1.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2020-12-15 09:02:15.532901 [+] INFO: Executing: C:\video2x\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i D:\2.0rc\1.mp4[0m
[90m2020-12-15 09:02:15.579775 [+] INFO: Creating cache directory C:\Users\sirlo\AppData\Local\Temp\video2x[0m
[90m2020-12-15 09:02:15.580772 [+] INFO: Extracted frames are being saved to: C:\Users\sirlo\AppData\Local\Temp\video2x\tmp1q18e24v[0m
[90m2020-12-15 09:02:15.581773 [+] INFO: Upscaled frames are being saved to: C:\Users\sirlo\AppData\Local\Temp\video2x\tmpf7rxzh01[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[90m2020-12-15 09:02:15.582767 [+] INFO: Executing: C:\video2x\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 D:\2.0rc\1.mp4[0m
Cleaning up cache directory: C:\Users\sirlo\AppData\Local\Temp\video2x\tmp1q18e24v
Cleaning up cache directory: C:\Users\sirlo\AppData\Local\Temp\video2x\tmpf7rxzh01
Cleaning up cache directory: C:\Users\sirlo\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 810, in run
  File "upscaler.py", line 593, in run
  File "wrappers\ffmpeg.py", line 107, in get_number_of_frames
ValueError: invalid literal for int() with base 10: '47001\r\n47001'
[32m[+] INFO: Loading files into processing queue[0m
[90m2020-12-15 09:03:09.148243 [+] INFO: Input path(s): D:\2.0rc\1.mp4[0m
[90m2020-12-15 09:03:09.152232 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2020-12-15 09:03:09.154227 [+] INFO: Input file: D:\2.0rc\1.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2020-12-15 09:03:09.154227 [+] INFO: Executing: C:\video2x\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i D:\2.0rc\1.mp4[0m
[90m2020-12-15 09:03:09.203096 [+] INFO: Creating cache directory C:\Users\sirlo\AppData\Local\Temp\video2x[0m
[90m2020-12-15 09:03:09.204095 [+] INFO: Extracted frames are being saved to: C:\Users\sirlo\AppData\Local\Temp\video2x\tmp5bouaqba[0m
[90m2020-12-15 09:03:09.204095 [+] INFO: Upscaled frames are being saved to: C:\Users\sirlo\AppData\Local\Temp\video2x\tmpmm1dafu0[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[90m2020-12-15 09:03:09.205091 [+] INFO: Executing: C:\video2x\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 D:\2.0rc\1.mp4[0m
Cleaning up cache directory: C:\Users\sirlo\AppData\Local\Temp\video2x\tmp5bouaqba
Cleaning up cache directory: C:\Users\sirlo\AppData\Local\Temp\video2x\tmpmm1dafu0
Cleaning up cache directory: C:\Users\sirlo\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 810, in run
  File "upscaler.py", line 593, in run
  File "wrappers\ffmpeg.py", line 107, in get_number_of_frames
ValueError: invalid literal for int() with base 10: '47001\r\n47001'
```

**Comment by k4yt3x** [comment]
It is possible for me to take a look at the original video?

**Comment by Sir-Antonic** [comment]
yea let me upload it real quick.... https://www.mediafire.com/file/zzig1jtje9gg68l/1.mkv/file this should be it

**Comment by Sir-Antonic** [comment]
i tried changing the codec to h264 etc thats why its a mkv now

**Comment by k4yt3x** [comment]
Got it. Will take a look.

**Comment by k4yt3x** [comment]
> yea let me upload it real quick.... https://www.mediafire.com/file/zzig1jtje9gg68l/1.mkv/file this should be it

Is this the original video that's causing the problems? It runs fine on my machine.

**Comment by k4yt3x** [comment]
If this is not the original one, please upload the original one so I can reproduce the error.

**Comment by Sir-Antonic** [comment]
yea let me get the unconverted one, but the one I sent (and any video I try really) give me that error

https://www.mediafire.com/file/4fnn09tkb5zxjzf/Samoa+Joe+vs+Kenta+Kobashi+October+1st,+2005.mp4/file

**Comment by k4yt3x** [comment]
For whatever reason this file produces two lines of frame counts...
I've fixed it in the newest commit.

![image](https://user-images.githubusercontent.com/21986859/105615167-6f786100-5dc6-11eb-887a-2cf1c151cce6.png)
