### ISSUE TITLE
Command '['E:\\video2x\\video2x-4.8.0-win32-full\\dependencies\\srmd-ncnn-vulkan\\srmd-ncnn-vulkan', '-n', '3', '-s', '4', '-t', '400', '-m', 'E:\\video2x\\video2x-4.8.0-win32-full\\dependencies\\srmd-ncnn-vulkan\\models-srmd', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\xuan\\AppData\\Local\\Temp\\video2x\\tmp3bbm_5e5', '-o', 'C:\\Users\\xuan\\AppData\\Local\\Temp\\video2x\\tmpkuh3sx0p']' returned non-zero exit status 4294967295.

### ISSUE THREAD

**Issue by Kawaiimumu233** [k4yt3x/video2x#433]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.0
- **Upscaler version**:
- **GUI version**: 2.8.1
- **CLI version**:

## Symptom

I tried all drivers and all of them couldn't run and left " returned non-zero exit status 4294967295 "
It seems that it could extract all frams but couldn't upscaled
I was using " video2x-4.8.0-win32-full.zip "
I searched by google and issues but I didn't find a way to solve this
And sorry I'm using windows10 Chinese version and my English is not so well

## Error Log or Screenshots

[+] INFO: 正在将文件添加到处理队列中
2020-12-20 23:32:03.596572 [+] INFO: 输入路径：E:\waifu2x\parn\parn2\output.avi
2020-12-20 23:32:03.602571 [+] INFO: 文件 MIME 类型：video/x-msvideo
[+] INFO: 文件已添加到处理队列
2020-12-20 23:32:03.609569 [+] INFO: 输入文件：E:\waifu2x\parn\parn2\output.avi
[+] INFO: 正在读取视频信息
2020-12-20 23:32:03.610573 [+] INFO: Executing: E:\video2x\video2x-4.8.0-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i E:\waifu2x\parn\parn2\output.avi
2020-12-20 23:32:05.038569 [+] INFO: 创建缓存目录 C:\Users\xuan\AppData\Local\Temp\video2x
2020-12-20 23:32:05.042570 [+] INFO: 提取的帧将被保存到：C:\Users\xuan\AppData\Local\Temp\video2x\tmp3bbm_5e5
2020-12-20 23:32:05.045572 [+] INFO: 已放大的帧将被保存到：C:\Users\xuan\AppData\Local\Temp\video2x\tmpkuh3sx0p
[+] INFO: 开始放大视频/GIF
[+] INFO: 正在获取文件中的总帧数
[+] INFO: 正在计算缩放参数
2020-12-20 23:32:05.047571 [+] INFO: 帧率：60.0
2020-12-20 23:32:05.050569 [+] INFO: 宽：640
2020-12-20 23:32:05.050569 [+] INFO: 高：480
2020-12-20 23:32:05.051569 [+] INFO: 总帧数：1203
2020-12-20 23:32:05.052572 [+] INFO: 输出宽度：2560
2020-12-20 23:32:05.052572 [+] INFO: 输出高度：1920
2020-12-20 23:32:05.054569 [+] INFO: 需要的缩放比例：4.0
2020-12-20 23:32:05.055568 [+] INFO: 放大工作队列：[4]
2020-12-20 23:32:05.057572 [+] INFO: Executing: E:\video2x\video2x-4.8.0-win32-full\dependencies\ffmpeg\bin\ffmpeg -hwaccel auto -y -i E:\waifu2x\parn\parn2\output.avi -pix_fmt rgb24 C:\Users\xuan\AppData\Local\Temp\video2x\tmp3bbm_5e5\extracted_%0d.png
2020-12-20 23:32:06.127570 [+] INFO: 主进程开始等待子进程结束
2020-12-20 23:32:18.653570 [+] INFO: 子进程 8060 结束，返回码 0
[+] INFO: 开始对提取的帧进行放大
2020-12-20 23:32:18.774572 [+] INFO: [upscaler] Subprocess 5376 executing: E:\video2x\video2x-4.8.0-win32-full\dependencies\srmd-ncnn-vulkan\srmd-ncnn-vulkan -n 3 -s 4 -t 400 -m E:\video2x\video2x-4.8.0-win32-full\dependencies\srmd-ncnn-vulkan\models-srmd -g 0 -j 1:1:1 -f png -i C:\Users\xuan\AppData\Local\Temp\video2x\tmp3bbm_5e5 -o C:\Users\xuan\AppData\Local\Temp\video2x\tmpkuh3sx0p
2020-12-20 23:32:19.958570 [+] INFO: 启动进度监视器
2020-12-20 23:32:19.961569 [+] INFO: 启动已放大图像清理程序
正在处理：output.avi（进度）:   0%|                                                           | 0/1203 [00:00<?, ?it/s]
[!] ERROR: 子进程 10236 结束，返回码 4294967295
[!] ERROR: 子进程执行遇到错误
[!] WARNING: 正在终止所有进程
2020-12-20 23:32:20.102570 [+] INFO: 终结进度监视器
正在处理：output.avi（进度）:   0%|                                                           | 0/1203 [00:01<?, ?it/s]
2020-12-20 23:32:21.000571 [+] INFO: 终结已放大图像清理程序
清理缓存目录：C:\Users\xuan\AppData\Local\Temp\video2x\tmp3bbm_5e5
清理缓存目录：C:\Users\xuan\AppData\Local\Temp\video2x\tmpkuh3sx0p
清理缓存目录：C:\Users\xuan\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 106, in run
  File "upscaler.py", line 810, in run
  File "upscaler.py", line 700, in run
  File "upscaler.py", line 347, in _upscale_frames
  File "upscaler.py", line 339, in _upscale_frames
  File "upscaler.py", line 409, in _wait
  File "upscaler.py", line 393, in _wait
subprocess.CalledProcessError: Command '['E:\\video2x\\video2x-4.8.0-win32-full\\dependencies\\srmd-ncnn-vulkan\\srmd-ncnn-vulkan', '-n', '3', '-s', '4', '-t', '400', '-m', 'E:\\video2x\\video2x-4.8.0-win32-full\\dependencies\\srmd-ncnn-vulkan\\models-srmd', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\xuan\\AppData\\Local\\Temp\\video2x\\tmp3bbm_5e5', '-o', 'C:\\Users\\xuan\\AppData\\Local\\Temp\\video2x\\tmpkuh3sx0p']' returned non-zero exit status 4294967295.

Please upload or paste the error log here. You may also include screenshots.
**It is highly recommended to include your error log.**

**Comment by k4yt3x** [comment]
I'm sorry for the late reply. Somehow this issue slipped under my radar and I just saw it now.
Could you please update to the newest version and attach the error log file?

**Comment by Kawaiimumu233** [comment]
> I'm sorry for the late reply. Somehow this issue slipped under my radar and I just saw it now.
> Could you please update to the newest version and attach the error log file?

抱歉 之前期末考没关注xD(还是用中午交流好了((
用新版本(4.8.1)就可以了 感谢修复!!

sorry, I did not pay attention to github because of the final exam
it worked well in the new version ( 4.8.1 ) , thanks for the fix!!
