### ISSUE TITLE
FileNotFoundError: C:\Users\ro612\AppData\Local\video2x\ffmpeg\bin

### ISSUE THREAD

**Issue by jygkh** [k4yt3x/video2x#438]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:4.8.1
- **Upscaler version**:
- **GUI version**:
- **CLI version**:

## Symptom

In this section, briefly describe what's going on.

## Error Log or Screenshots

```
[32m[+] INFO: Loading files into processing queue[0m [90m2020-12-29 00:39:13.277620 [+] INFO: Input path(s): D:\Documents\Shows\Beyblade Burst\Beyblade Burst Rise S04E22  Shining Ashindra!.mp4[0m [90m2020-12-29 00:39:13.279590 [+] INFO: File MIME type: video/mp4[0m [31m[1m[!] ERROR: FFmpeg or FFprobe cannot be found under the specified path[0m [31m[1m[!] ERROR: Please check the configuration file settings[0m Traceback (most recent call last):   File "C:\Program Files\video2x-4.8.1\src\video2x_gui.py", line 105, in run     self.fn(*self.args, **self.kwargs)   File "C:\Program Files\video2x-4.8.1\src\upscaler.py", line 633, in run     self._check_arguments()   File "C:\Program Files\video2x-4.8.1\src\upscaler.py", line 281, in _check_arguments     raise FileNotFoundError(self.ffmpeg_settings["ffmpeg_path"]) FileNotFoundError: C:\Users\ro612\AppData\Local\video2x\ffmpeg\bin [32m[+] INFO: Loading files into processing queue[0m [90m2020-12-29 00:42:12.615057 [+] INFO: Input path(s): D:\Documents\Shows\Beyblade Burst\Beyblade Burst Rise S04E22  Shining Ashindra!.mp4[0m [90m2020-12-29 00:42:12.616615 [+] INFO: File MIME type: video/mp4[0m [31m[1m[!] ERROR: FFmpeg or FFprobe cannot be found under the specified path[0m [31m[1m[!] ERROR: Please check the configuration file settings[0m Traceback (most recent call last):   File "C:\Program Files\video2x-4.8.1\src\video2x_gui.py", line 105, in run     self.fn(*self.args, **self.kwargs)   File "C:\Program Files\video2x-4.8.1\src\upscaler.py", line 633, in run     self._check_arguments()   File "C:\Program Files\video2x-4.8.1\src\upscaler.py", line 281, in _check_arguments     raise FileNotFoundError(self.ffmpeg_settings["ffmpeg_path"]) FileNotFoundError: C:\Users\ro612\AppData\Local\video2x\ffmpeg\bin [32m[+] INFO: Loading files into processing queue[0m [90m2020-12-29 00:43:07.413796 [+] INFO: Input path(s): D:\Documents\Shows\Beyblade Burst\Beyblade Burst Rise S04E22  Shining Ashindra!.mp4[0m [90m2020-12-29 00:43:07.416819 [+] INFO: File MIME type: video/mp4[0m [31m[1m[!] ERROR: Specified driver executable directory doesn't exist[0m [31m[1m[!] ERROR: Please check the configuration file settings[0m Traceback (most recent call last):   File "C:\Program Files\video2x-4.8.1\src\video2x_gui.py", line 105, in run     self.fn(*self.args, **self.kwargs)   File "C:\Program Files\video2x-4.8.1\src\upscaler.py", line 633, in run     self._check_arguments()   File "C:\Program Files\video2x-4.8.1\src\upscaler.py", line 294, in _check_arguments     raise FileNotFoundError(driver_path) FileNotFoundError: C:\Users\ro612\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan
```

**Comment by k4yt3x** [comment]
Have you ran the setup script?
