### ISSUE TITLE
[!] ERROR: FFmpeg or FFprobe cannot be found under the specified path, despite putting the correct path in the config

### ISSUE THREAD

**Issue by APersonWhoLikesPasta** [k4yt3x/video2x#447]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1
- **Upscaler version**: ???
- **GUI version**: ???
- **CLI version**: ???
- **Distro**: Fedora 33
Sorry I'm not entirely sure what to put for the versions. I looked, but didn't see any version numbers.

## Symptom

I followed the "Run from Source Code" direction in the docs. I followed the instructions installing the Python dependencies, FFmpeg, and waifu2x-converter-cpp. The next direction said to "Update the configuration file and replace the driver's path with the path of the driver you've just installed." So I did `which ffmpeg` and changed the path parameter in `video2x.yaml` to `/usr/bin/ffmpeg`. I did the same for waifu2x-converter-cpp.

For some reason though it doesn't work. It says that I put the incorrect path, despite the fact that (as far as I know) this is the correct path.  Paths I have tried include `/usr/bin/ffmpeg`, `/bin/ffmpeg`, `/usr/bin/ffprobe`, `/bin/ffprobe`, `ffmpeg`, and `ffprobe`.

## Error Log or Screenshots
```bash
2021-01-17 23:36:29.035054 [+] INFO: Input path(s): /home/apersonwholikespasta/Videos/Candy_Boy/360p
2021-01-17 23:36:29.038555 [+] INFO: File MIME type: video/mp4
2021-01-17 23:36:29.040634 [+] INFO: File MIME type: video/mp4
2021-01-17 23:36:29.044479 [+] INFO: File MIME type: video/mp4
2021-01-17 23:36:29.046544 [+] INFO: File MIME type: video/mp4
[!] ERROR: FFmpeg or FFprobe cannot be found under the specified path
[!] ERROR: Please check the configuration file settings
Traceback (most recent call last):
  File "/home/apersonwholikespasta/.local/share/video2x_4.8.1/video2x/src/video2x_gui.py", line 105, in run
    self.fn(*self.args, **self.kwargs)
  File "/home/apersonwholikespasta/.local/share/video2x_4.8.1/video2x/src/upscaler.py", line 633, in run
    self._check_arguments()
  File "/home/apersonwholikespasta/.local/share/video2x_4.8.1/video2x/src/upscaler.py", line 281, in _check_arguments
    raise FileNotFoundError(self.ffmpeg_settings["ffmpeg_path"])
FileNotFoundError: /usr/bin/ffmpeg
```

**Comment by k4yt3x** [comment]
The path to use is the parent containing folder.
e.g., `/usr/bin` in your case.

**Comment by APersonWhoLikesPasta** [comment]
Thank you it works now.
