### ISSUE TITLE
returned non-zero exit status 1.

### ISSUE THREAD

**Issue by raziEiL** [k4yt3x/video2x#462]
## Component Versions

Please at least fill in the release version and GUI or CLI version.
[Video2X 4.8.1 Full](https://github.com/k4yt3x/video2x/releases/tag/4.8.1)
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 461.09       Driver Version: 461.09       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 650 Ti WDDM  | 00000000:01:00.0 N/A |                  N/A |
| 30%   32C    P8    N/A /  N/A |    643MiB /  1024MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

## Symptom
Throw an upscale run error

## Error Log or Screenshots
```
[+] INFO: Loading files into processing queue
2021-02-18 20:24:03.125166 [+] INFO: Input path(s): C:\Users\denis\Desktop\videoplayback.mp4
2021-02-18 20:24:03.128166 [+] INFO: File MIME type: video/mp4
[+] INFO: Loaded files into processing queue
2021-02-18 20:24:03.132174 [+] INFO: Input file: C:\Users\denis\Desktop\videoplayback.mp4
[+] INFO: Reading file information
2021-02-18 20:24:03.132174 [+] INFO: Executing: C:\Users\denis\Downloads\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i C:\Users\denis\Desktop\videoplayback.mp4
2021-02-18 20:24:03.227487 [+] INFO: Creating cache directory C:\Users\denis\AppData\Local\Temp\video2x
2021-02-18 20:24:03.229487 [+] INFO: Extracted frames are being saved to: C:\Users\denis\AppData\Local\Temp\video2x\tmp9cd3xmjc
2021-02-18 20:24:03.229487 [+] INFO: Upscaled frames are being saved to: C:\Users\denis\AppData\Local\Temp\video2x\tmpgcyva_62
[+] INFO: Starting upscaling video/GIF
[+] INFO: Getting total number of frames in the file
[+] INFO: Calculating scaling parameters
2021-02-18 20:24:03.231536 [+] INFO: Framerate: 25.0
2021-02-18 20:24:03.231536 [+] INFO: Width: 320
2021-02-18 20:24:03.231536 [+] INFO: Height: 240
2021-02-18 20:24:03.231536 [+] INFO: Total number of frames: 377
2021-02-18 20:24:03.232536 [+] INFO: Output width: 640
2021-02-18 20:24:03.232536 [+] INFO: Output height: 480
2021-02-18 20:24:03.232536 [+] INFO: Required scale ratio: 2.0
2021-02-18 20:24:03.232536 [+] INFO: Upscaling jobs queue: [2.0]
2021-02-18 20:24:03.233536 [+] INFO: Executing: C:\Users\denis\Downloads\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -hwaccel auto -y -i C:\Users\denis\Desktop\videoplayback.mp4 -pix_fmt rgb24 C:\Users\denis\AppData\Local\Temp\video2x\tmp9cd3xmjc\extracted_%0d.png
2021-02-18 20:24:03.237317 [+] INFO: Main process waiting for subprocesses to exit
2021-02-18 20:24:07.881046 [+] INFO: Subprocess 11680 exited with code 0
2021-02-18 20:24:07.982930 [+] INFO: Executing: C:\Users\denis\Downloads\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -pix_fmts
2021-02-18 20:24:08.066883 [+] INFO: {'yuv420p': 12, 'yuyv422': 16, 'rgb24': 24, 'bgr24': 24, 'yuv422p': 16, 'yuv444p': 24, 'yuv410p': 9, 'yuv411p': 12, 'gray': 8, 'monow': 1, 'monob': 1, 'pal8': 8, 'yuvj420p': 12, 'yuvj422p': 16, 'yuvj444p': 24, 'uyvy422': 16, 'uyyvyy411': 12, 'bgr8': 8, 'bgr4': 4, 'bgr4_byte': 4, 'rgb8': 8, 'rgb4': 4, 'rgb4_byte': 4, 'nv12': 12, 'nv21': 12, 'argb': 32, 'rgba': 32, 'abgr': 32, 'bgra': 32, 'gray16be': 16, 'gray16le': 16, 'yuv440p': 16, 'yuvj440p': 16, 'yuva420p': 20, 'rgb48be': 48, 'rgb48le': 48, 'rgb565be': 16, 'rgb565le': 16, 'rgb555be': 15, 'rgb555le': 15, 'bgr565be': 16, 'bgr565le': 16, 'bgr555be': 15, 'bgr555le': 15, 'vaapi_moco': 0, 'vaapi_idct': 0, 'vaapi_vld': 0, 'yuv420p16le': 24, 'yuv420p16be': 24, 'yuv422p16le': 32, 'yuv422p16be': 32, 'yuv444p16le': 48, 'yuv444p16be': 48, 'dxva2_vld': 0, 'rgb444le': 12, 'rgb444be': 12, 'bgr444le': 12, 'bgr444be': 12, 'ya8': 16, 'bgr48be': 48, 'bgr48le': 48, 'yuv420p9be': 13, 'yuv420p9le': 13, 'yuv420p10be': 15, 'yuv420p10le': 15, 'yuv422p10be': 20, 'yuv422p10le': 20, 'yuv444p9be': 27, 'yuv444p9le': 27, 'yuv444p10be': 30, 'yuv444p10le': 30, 'yuv422p9be': 18, 'yuv422p9le': 18, 'gbrp': 24, 'gbrp9be': 27, 'gbrp9le': 27, 'gbrp10be': 30, 'gbrp10le': 30, 'gbrp16be': 48, 'gbrp16le': 48, 'yuva422p': 24, 'yuva444p': 32, 'yuva420p9be': 22, 'yuva420p9le': 22, 'yuva422p9be': 27, 'yuva422p9le': 27, 'yuva444p9be': 36, 'yuva444p9le': 36, 'yuva420p10be': 25, 'yuva420p10le': 25, 'yuva422p10be': 30, 'yuva422p10le': 30, 'yuva444p10be': 40, 'yuva444p10le': 40, 'yuva420p16be': 40, 'yuva420p16le': 40, 'yuva422p16be': 48, 'yuva422p16le': 48, 'yuva444p16be': 64, 'yuva444p16le': 64, 'vdpau': 0, 'xyz12le': 36, 'xyz12be': 36, 'nv16': 16, 'nv20le': 20, 'nv20be': 20, 'rgba64be': 64, 'rgba64le': 64, 'bgra64be': 64, 'bgra64le': 64, 'yvyu422': 16, 'ya16be': 32, 'ya16le': 32, 'gbrap': 32, 'gbrap16be': 64, 'gbrap16le': 64, 'qsv': 0, 'mmal': 0, 'd3d11va_vld': 0, 'cuda': 0, '0rgb': 24, 'rgb0': 24, '0bgr': 24, 'bgr0': 24, 'yuv420p12be': 18, 'yuv420p12le': 18, 'yuv420p14be': 21, 'yuv420p14le': 21, 'yuv422p12be': 24, 'yuv422p12le': 24, 'yuv422p14be': 28, 'yuv422p14le': 28, 'yuv444p12be': 36, 'yuv444p12le': 36, 'yuv444p14be': 42, 'yuv444p14le': 42, 'gbrp12be': 36, 'gbrp12le': 36, 'gbrp14be': 42, 'gbrp14le': 42, 'yuvj411p': 12, 'bayer_bggr8': 8, 'bayer_rggb8': 8, 'bayer_gbrg8': 8, 'bayer_grbg8': 8, 'bayer_bggr16le': 16, 'bayer_bggr16be': 16, 'bayer_rggb16le': 16, 'bayer_rggb16be': 16, 'bayer_gbrg16le': 16, 'bayer_gbrg16be': 16, 'bayer_grbg16le': 16, 'bayer_grbg16be': 16, 'xvmc': 0, 'yuv440p10le': 20, 'yuv440p10be': 20, 'yuv440p12le': 24, 'yuv440p12be': 24, 'ayuv64le': 64, 'ayuv64be': 64, 'videotoolbox_vld': 0, 'p010le': 15, 'p010be': 15, 'gbrap12be': 48, 'gbrap12le': 48, 'gbrap10be': 40, 'gbrap10le': 40, 'mediacodec': 0, 'gray12be': 12, 'gray12le': 12, 'gray10be': 10, 'gray10le': 10, 'p016le': 24, 'p016be': 24, 'd3d11': 0, 'gray9be': 9, 'gray9le': 9, 'gbrpf32be': 96, 'gbrpf32le': 96, 'gbrapf32be': 128, 'gbrapf32le': 128, 'drm_prime': 0, 'opencl': 0, 'gray14be': 14, 'gray14le': 14, 'grayf32be': 32, 'grayf32le': 32, 'yuva422p12be': 36, 'yuva422p12le': 36, 'yuva444p12be': 48, 'yuva444p12le': 48, 'nv24': 24, 'nv42': 24, 'vulkan': 0, 'y210be': 20, 'y210le': 20}
[+] INFO: Starting to upscale extracted frames
2021-02-18 20:24:08.381339 [+] INFO: [upscaler] Subprocess 1400 executing: C:\Users\denis\Downloads\video2x-4.8.1-win32-full\dependencies\waifu2x-caffe\waifu2x-caffe-cui --tta 0 --gpu 0 --batch_size 1 --crop_size 128 --output_depth 24 --output_quality -1 --process gpu --model_dir C:\Users\denis\Downloads\video2x-4.8.1-win32-full\dependencies\waifu2x-caffe\models\cunet --noise_level 3 --mode noise_scale --output_extention png --scale_width 640 --scale_height 480 --input_path C:\Users\denis\AppData\Local\Temp\video2x\tmp9cd3xmjc\0 --output_path C:\Users\denis\AppData\Local\Temp\video2x\tmpgcyva_62
2021-02-18 20:24:08.387341 [+] INFO: Starting progress monitor
2021-02-18 20:24:08.388339 [+] INFO: Starting upscaled image cleaner
2021-02-18 20:24:08.390339 [+] INFO: Main process waiting for subprocesses to exit
Processing: videoplayback.mp4 (pass 1/1):   0%|                                                | 0/377 [00:00<?, ?it/s][!] ERROR: Subprocess 11724 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
2021-02-18 20:24:08.596845 [+] INFO: Killing progress monitor
Processing: videoplayback.mp4 (pass 1/1):   0%|                                                | 0/377 [00:01<?, ?it/s]
2021-02-18 20:24:09.404630 [+] INFO: Killing upscaled image cleaner
Cleaning up cache directory: C:\Users\denis\AppData\Local\Temp\video2x\tmp9cd3xmjc
Cleaning up cache directory: C:\Users\denis\AppData\Local\Temp\video2x\tmpgcyva_62
Cleaning up cache directory: C:\Users\denis\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 849, in run
  File "upscaler.py", line 416, in _upscale_frames
  File "upscaler.py", line 408, in _upscale_frames
  File "upscaler.py", line 489, in _wait
  File "upscaler.py", line 467, in _wait
subprocess.CalledProcessError: Command '['C:\\Users\\denis\\Downloads\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui', '--tta', '0', '--gpu', '0', '--batch_size', '1', '--crop_size', '128', '--output_depth', '24', '--output_quality', '-1', '--process', 'gpu', '--model_dir', 'C:\\Users\\denis\\Downloads\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-caffe\\models\\cunet', '--noise_level', '3', '--mode', 'noise_scale', '--output_extention', 'png', '--scale_width', '640', '--scale_height', '480', '--input_path', 'C:\\Users\\denis\\AppData\\Local\\Temp\\video2x\\tmp9cd3xmjc\\0', '--output_path', 'C:\\Users\\denis\\AppData\\Local\\Temp\\video2x\\tmpgcyva_62']' returned non-zero exit status 1.
```

**Comment by k4yt3x** [comment]
You'll need to submit the original error log. This output file doesn't contain the subprocesses' stdout/stderr streams.
