### ISSUE TITLE
Setup Script error on FFmpeg

### ISSUE THREAD

**Issue by troy125478** [k4yt3x/video2x#482]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**:  4.8.1
- **Upscaler version**: N/A
- **GUI version**: N/A
- **CLI version**: N/A
- **Setup version**:  2.4.1

## Symptom

First off the step by step seems outdated I think. Downloading the new code has the folder "bin" missing. So I assumed that src would work. But continuing the steps and running video2x_setup.py in cmd I get an error on the first download "FFmpeg".

## Error Log or Screenshots

Installing FFmpeg
Downloading: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z
Total size: 36900306
Chunk size: 4096
Saving to: C:\Users\Public\Documents\Wondershare\CreatorTemp\ffmpeg-4.3.2-2021-02-27-full_build.7z
100%|################################################################| 36900306/36900306 [00:01<00:00, 20419832.71it/s]
patool: Extracting C:\Users\Public\Documents\Wondershare\CreatorTemp\ffmpeg-4.3.2-2021-02-27-full_build.7z ...
Traceback (most recent call last):
  File "C:\Users\danny\Downloads\video2x-master\src\video2x_setup.py", line 475, in <module>
    setup.run()
  File "C:\Users\danny\Downloads\video2x-master\src\video2x_setup.py", line 110, in run
    getattr(self, f"_install_{driver}")()
  File "C:\Users\danny\Downloads\video2x-master\src\video2x_setup.py", line 160, in _install_ffmpeg
    patoolib.extract_archive(str(ffmpeg_7z), outdir=str(LOCALAPPDATA / "video2x"))
  File "C:\Users\danny\AppData\Local\Programs\Python\Python39\lib\site-packages\patoolib\__init__.py", line 684, in extract_archive
    return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python39\lib\site-packages\patoolib\__init__.py", line 470, in _extract_archive
    program = find_archive_program(format, 'extract', program=program)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python39\lib\site-packages\patoolib\__init__.py", line 336, in find_archive_program
    raise util.PatoolError("could not find an executable program to %s format %s; candidates are (%s)," % (command, format, ",".join(programs)))
patoolib.util.PatoolError: could not find an executable program to extract format 7z; candidates are (7z,7za,7zr),
An error has occurred
Video2X Automatic Setup has failed

Cleaning up temporary files
Deleting file: C:\Users\Public\Documents\Wondershare\CreatorTemp\ffmpeg-4.3.2-2021-02-27-full_build.7z
Script finished
Time taken: 0:00:04

**Comment by k4yt3x** [comment]
gyan.dev's FFmpeg build is packaged in 7z format, which can only be correctly decompressed by 7zip. patool uses 7zip's binary to do that. You'll need to have 7zip installed.
