### ISSUE TITLE
non-zero exit status 255

### ISSUE THREAD

**Issue by Excelsiorly** [k4yt3x/video2x#497]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.8.1

## Symptom

returned non-zero exit status 255.

## Error Log or Screenshots

subprocess.CalledProcessError: Command '['/home/jojo/PythonProjects/video/video2x/src/model/waifu2x-ncnn-vulkan-20210210-ubuntu/waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-g', '0', '-j', '1:1:1', '-i', '/tmp/video2x/tmp2zlngl9c', '-o', '/tmp/video2x/tmpn3e_984d']' returned non-zero exit status 255.
**It is highly recommended to include your error log.**
log:
```shell
[32m[+] INFO: Loading files into processing queue[0m
[90m2021-04-22 13:39:24.845862 [+] INFO: Input path(s): workspace/src/test.mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2021-04-22 13:39:24.857852 [+] INFO: Input file: /home/jojo/PythonProjects/video/video2x/src/workspace/src/test.mp4[0m
[90m2021-04-22 13:39:24.859068 [+] INFO: Creating cache directory /tmp/video2x[0m
[90m2021-04-22 13:39:24.859878 [+] INFO: Extracted frames are being saved to: /tmp/video2x/tmp2zlngl9c[0m
[90m2021-04-22 13:39:24.860335 [+] INFO: Upscaled frames are being saved to: /tmp/video2x/tmpn3e_984d[0m
[32m[+] INFO: Reading video information[0m
[90m2021-04-22 13:39:24.860532 [+] INFO: Executing: /home/jojo/ffmpeg/bin/ffprobe -v quiet -print_format json -show_format -show_streams -i /home/jojo/PythonProjects/video/video2x/src/workspace/src/test.mp4[0m
[32m[+] INFO: Framerate: 23.976023976023978[0m
[90m2021-04-22 13:39:24.902391 [+] INFO: Executing: /home/jojo/ffmpeg/bin/ffmpeg -hwaccel auto -y -i /home/jojo/PythonProjects/video/video2x/src/workspace/src/test.mp4 -pix_fmt rgb24 /tmp/video2x/tmp2zlngl9c/extracted_%0d.png[0m
[90m2021-04-22 13:39:24.904593 [+] INFO: Main process waiting for subprocesses to exit[0m
[90m2021-04-22 13:39:25.606668 [+] INFO: Subprocess 26288 exited with code 0[0m
[32m[+] INFO: Starting to upscale extracted frames[0m
[90m2021-04-22 13:39:25.723152 [+] INFO: [upscaler] Subprocess 26266 executing: /home/jojo/PythonProjects/video/video2x/src/model/waifu2x-ncnn-vulkan-20210210-ubuntu/waifu2x-ncnn-vulkan -n 2 -s 2 -t 400 -g 0 -j 1:1:1 -i /tmp/video2x/tmp2zlngl9c -o /tmp/video2x/tmpn3e_984d[0m
[90m2021-04-22 13:39:25.725735 [+] INFO: Starting progress monitor[0m
[90m2021-04-22 13:39:25.726710 [+] INFO: Starting upscaled image cleaner[0m
[90m2021-04-22 13:39:25.727408 [+] INFO: Main process waiting for subprocesses to exit[0m

Upscaling Progress:   0%|          | 0/456 [00:00<?, ?it/s][31m[1m[!] ERROR: Subprocess 26489 exited with code 255[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
[90m2021-04-22 13:39:25.829094 [+] INFO: Killing progress monitor[0m

Upscaling Progress:   0%|          | 0/456 [00:01<?, ?it/s]
[90m2021-04-22 13:39:26.766122 [+] INFO: Killing upscaled image cleaner[0m
Cleaning up cache directory: /tmp/video2x/tmp2zlngl9c
Cleaning up cache directory: /tmp/video2x/tmpn3e_984d
Cleaning up cache directory: /tmp/video2x
[31m[1m[!] ERROR: An exception has occurred[0m
Traceback (most recent call last):
  File "video2x.py", line 263, in <module>
    upscaler.run()
  File "/home/jojo/PythonProjects/video/video2x/src/upscaler.py", line 669, in run
    raise e
  File "/home/jojo/PythonProjects/video/video2x/src/upscaler.py", line 598, in run
    self._upscale_frames()
  File "/home/jojo/PythonProjects/video/video2x/src/upscaler.py", line 341, in _upscale_frames
    raise e
  File "/home/jojo/PythonProjects/video/video2x/src/upscaler.py", line 333, in _upscale_frames
    self._wait()
  File "/home/jojo/PythonProjects/video/video2x/src/upscaler.py", line 403, in _wait
    raise e
  File "/home/jojo/PythonProjects/video/video2x/src/upscaler.py", line 387, in _wait
    raise subprocess.CalledProcessError(process_status, process.args)
subprocess.CalledProcessError: Command '['/home/jojo/PythonProjects/video/video2x/src/model/waifu2x-ncnn-vulkan-20210210-ubuntu/waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-g', '0', '-j', '1:1:1', '-i', '/tmp/video2x/tmp2zlngl9c', '-o', '/tmp/video2x/tmpn3e_984d']' returned non-zero exit status 255.
```

my graphic card info:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   43C    P0    56W / 300W |   5486MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   41C    P0    53W / 300W |   1843MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```

**Comment by k4yt3x** [comment]
Do you have the original error logs?

**Comment by Excelsiorly** [comment]
After i re-installed the nvidia driver, that bugs magically disappeared. Everything works just fine! Thank I will closes this issue!
