### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/usr/bin'

### ISSUE THREAD

**Issue by TheFel0x** [k4yt3x/video2x#499]
## Component Versions

- **Video2X release version**: 4.3.1
- **Upscaler version**: 4.4.1
- **CLI version**: 4.3.1

## Symptom

Upscaling a gif results in an error while converting frames to gif.
Error occurred when I ran `video2x -i input.gif  -o test.gif -r 2`
also happens when using sudo
I didn't make any changes to any configs

## Error Log or Screenshots
```
[+] INFO: Upscaling completed
[+] INFO: Average processing speed: 1.9955688166204466 seconds per frame
[+] INFO: Lanczos downscaling frames

Downscaling:   0%|          | 0/4 [00:00<?, ?it/s]
Downscaling: 100%|##########| 4/4 [00:00<00:00, 612.73it/s]
[+] INFO: Converting extracted frames into GIF image
2021-04-25 17:43:35.803423 [+] INFO: Executing: ['/usr/bin', '-o', '/home/thefel0x/test.gif', '--fps', '10', '--width', '440', '--height', '440', '--quality', '100', '/var/tmp/video2x/tmpekmusah4/extracted_*.png']
Cleaning up cache directory: /var/tmp/video2x/tmpgl6gszvt
Cleaning up cache directory: /var/tmp/video2x/tmpekmusah4
Cleaning up cache directory: /var/tmp/video2x
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "/usr/bin/video2x", line 342, in <module>
    upscaler.run()
  File "/usr/share/video2x/upscaler.py", line 1022, in run
    raise e
  File "/usr/share/video2x/upscaler.py", line 919, in run
    gifski_object.make_gif(
  File "/usr/share/video2x/wrappers/gifski.py", line 52, in make_gif
    return self._execute(execute)
  File "/usr/share/video2x/wrappers/gifski.py", line 82, in _execute
    return subprocess.Popen(execute, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/bin'
```

**Comment by k4yt3x** [comment]
Since you're using a Linux path, I'll assume that you're on Linux.
That `/usr/bin` should be the path to Gifski. It should be something more like `/usr/bin/gifski`. Instead, now you're trying to execute a directory, hence the permission errors.
You'll need to install Gifski (with cargo, preferably) and change its path to wherever you've installed it in the config.

**Comment by TheFel0x** [comment]
Sadly this gave me a new error.
```
[+] INFO: Upscaling completed
[+] INFO: Average processing speed: 1.9965671910528475 seconds per frame
[+] INFO: Lanczos downscaling frames
Downscaling: 100%|##########| 4/4 [00:00<00:00, 1099.93it/s]
[+] INFO: Converting extracted frames into GIF image
2021-04-26 17:39:38.411943 [+] INFO: Executing: ['/home/thefel0x/.cargo/bin/gifski', '-o', '/home/thefel0x/output.gif', '--fps', '10', '--width', '440', '--height', '440', '--quality', '100', '/var/tmp/video2x/tmp6s94xpic/extracted_*.png']
2021-04-26 17:39:38.413154 [+] INFO: Main process waiting for subprocesses to exit
[!] ERROR: Subprocess 52431 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "/usr/bin/video2x", line 342, in <module>
    upscaler.run()
  File "/usr/share/video2x/upscaler.py", line 1022, in run
    raise e
  File "/usr/share/video2x/upscaler.py", line 928, in run
    self._wait()
  File "/usr/share/video2x/upscaler.py", line 489, in _wait
    raise e
  File "/usr/share/video2x/upscaler.py", line 467, in _wait
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/home/thefel0x/.cargo/bin/gifski', '-o', '/home/thefel0x/output.gif', '--fps', '10', '--width', '440', '--height', '440', '--quality', '100', '/var/tmp/video2x/tmp6s94xpic/extracted_*.png']' returned non-zero exit status 1.
[!] ERROR: The error log file can be found at: /tmp/video2x_y44p_z9u.log
```
Trying to put the gif together myself (I had put `--preserve_frames`) I ran `/home/thefel0x/.cargo/bin/gifski -o /home/thefel0x/output.gif --fps 10 --width 440 --height 440 --quality 100 /var/tmp/video2x/tmp6s94xpic/extracted_*.png` myself and that created the gif without any problems. So gifski should be working fine.

**Comment by k4yt3x** [comment]
Your terminal doesn't care what's the return code of the binary, the script does since that's the standard way it's supposed to tell if Gifski exited correctly. Also, pasting terminal outputs doesn't help. The terminal output doesn't contain stderr, only stdout.

**Comment by k4yt3x** [comment]
I'll need the error log to be able to tell what actually happened during the execution there.

**Comment by TheFel0x** [comment]
Ah I see, sorry about that. The log looked the same to me at first glance that's why I copied the terminal output. I'll send the error log from now on.
```
[+] INFO: Converting extracted frames into GIF image
2021-04-27 15:49:27.814439 [+] INFO: Executing: ['/home/thefel0x/.cargo/bin/gifski', '-o', '/home/thefel0x/out.gif', '--fps', '8', '--width', '996', '--height', '842', '--quality', '100', '/var/tmp/video2x/tmp3s8asjq7/extracted_*.png']
2021-04-27 15:49:27.816813 [+] INFO: Main process waiting for subprocesses to exit
error: Unable to find the input file: "/var/tmp/video2x/tmp3s8asjq7/extracted_*.png"
The path contains a literal "*" character. If you want to select multiple files, don't put the special wildcard characters in quotes.
[!] ERROR: Subprocess 2540 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
Cleaning up cache directory: /var/tmp/video2x/tmpccsoam9a
Cleaning up cache directory: /var/tmp/video2x/tmp3s8asjq7
Cleaning up cache directory: /var/tmp/video2x
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "/usr/bin/video2x", line 342, in <module>
    upscaler.run()
  File "/usr/share/video2x/upscaler.py", line 1022, in run
    raise e
  File "/usr/share/video2x/upscaler.py", line 928, in run
    self._wait()
  File "/usr/share/video2x/upscaler.py", line 489, in _wait
    raise e
  File "/usr/share/video2x/upscaler.py", line 467, in _wait
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/home/thefel0x/.cargo/bin/gifski', '-o', '/home/thefel0x/out.gif', '--fps', '8', '--width', '996', '--height', '842', '--quality', '100', '/var/tmp/video2x/tmp3s8asjq7/extracted_*.png']' returned non-zero exit status 1.
```

**Comment by k4yt3x** [comment]
> error: Unable to find the input file: "/var/tmp/video2x/tmp3s8asjq7/extracted_*.png"

I think this is the problem. I think someone else has reported it before: #343 
There's a problem with the path name expansion.
