### ISSUE TITLE
Unable to complete the python setup

### ISSUE THREAD

**Issue by FSDuke** [k4yt3x/video2x#506]
Here is the output I get when running the setup:

Microsoft Windows [Version 10.0.18363.1441]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\video2x-master\video2x-master\src

C:\video2x-master\video2x-master\src>python video2x_setup.py
Video2X Setup Script
Version: 2.4.1

Installing Python libraries
Ignoring python-magic: markers 'platform_system != "Windows"' don't match your environment
Collecting avalon_framework
  Downloading avalon_framework-1.8.2.tar.gz (3.1 kB)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting patool
  Downloading patool-1.12-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 2.6 MB/s
Collecting pillow
  Downloading Pillow-8.2.0-cp39-cp39-win_amd64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.8 MB/s
Collecting pyqt5
  Downloading PyQt5-5.15.4-cp36.cp37.cp38.cp39-none-win_amd64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 6.4 MB/s
Collecting python-magic-bin
  Downloading python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl (409 kB)
     |████████████████████████████████| 409 kB ...
Collecting pyyaml
  Downloading PyYAML-5.4.1-cp39-cp39-win_amd64.whl (213 kB)
     |████████████████████████████████| 213 kB ...
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 3.8 MB/s
Collecting tqdm
  Downloading tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB ...
Collecting PyQt5-sip<13,>=12.8
  Downloading PyQt5_sip-12.8.1-cp39-cp39-win_amd64.whl (63 kB)
     |████████████████████████████████| 63 kB 980 kB/s
Collecting PyQt5-Qt5>=5.15
  Downloading PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
     |████████████████████████████████| 50.1 MB 89 kB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB ...
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB ...
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB ...
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 6.4 MB/s
Using legacy 'setup.py install' for avalon-framework, since package 'wheel' is not installed.
Installing collected packages: urllib3, PyQt5-sip, PyQt5-Qt5, idna, chardet, certifi, tqdm, requests, pyyaml, python-magic-bin, pyqt5, pillow, patool, colorama, avalon-framework
    Running setup.py install for avalon-framework ... done
Successfully installed PyQt5-Qt5-5.15.2 PyQt5-sip-12.8.1 avalon-framework-1.8.2 certifi-2020.12.5 chardet-4.0.0 colorama-0.4.4 idna-2.10 patool-1.12 pillow-8.2.0 pyqt5-5.15.4 python-magic-bin-0.4.14 pyyaml-5.4.1 requests-2.25.1 tqdm-4.60.0 urllib3-1.26.4

Installing FFmpeg
Traceback (most recent call last):
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1345, in getresponse
    response.begin()
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\video2x-master\video2x-master\src\video2x_setup.py", line 475, in <module>
    setup.run()
  File "C:\video2x-master\video2x-master\src\video2x_setup.py", line 110, in run
    getattr(self, f"_install_{driver}")()
  File "C:\video2x-master\video2x-master\src\video2x_setup.py", line 146, in _install_ffmpeg
    ffmpeg_7z = download(latest_release, tempfile.gettempdir())
  File "C:\video2x-master\video2x-master\src\video2x_setup.py", line 374, in download
    stream = requests.get(url, stream=True, allow_redirects=True)
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\sbernard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
An error has occurred
Video2X Automatic Setup has failed

Cleaning up temporary files
Script finished
Time taken: 0:00:14

C:\video2x-master\video2x-master\src>

**Comment by k4yt3x** [comment]
Looks like FFmpeg might have moved their build address again.
I'll look into that later, but for now you might want to consider using the release?
