### ISSUE TITLE
Anime4KCPP fails with non .png input extension

### ISSUE THREAD

**Issue by jrobgh** [k4yt3x/video2x#513]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 
4.8.1-win32-full 
also repros on python version from master 37d567f on Mar 13
- **Upscaler version**:
- **GUI version**: 2.8.1
- **CLI version**: 4.3.3

## Symptom

When Video2X is set to non .png input extension (.bmp, .jpg, etc.) Anime4KCPP does not follow this extension for its output (CLI always generates .png). This causes the subsequent ffmpeg commands to fail because they are looking for the video2x non .png extension.

Operation with intermediate .png files saves temporary disk space though requires a lot more cpu overhead (on my i7-2600k) and runtime than using .bmp.

I could work around this by modifying the video2x script to look for .png when converting the extracted frames to video, and also modified the instances in upscaler.py that pointed to upscaled_frames folder to instead use the extracted_frames folder from anime4kcpp.

## Error Log or Screenshots

video2x:
  video2x_cache_directory: e:\temp # default: %TEMP%\video2x, directory where cache files are stored, will be deleted if preserve_frames is not set to true
  extracted_frame_format: bmp # png/jpg intermediate file format used for extracted frames during video processing
  output_file_name_format_string: "{original_file_name}_output{extension}" # format string to use for generating output file names
  image_output_extension: .bmp # image output extension during batch processing

[+] INFO: Starting upscaling video/GIF
[+] INFO: Getting total number of frames in the file
2021-05-28 11:06:05.873490 [+] INFO: Executing: C:\temp\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 C:\temp\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\fff4.mkv
[+] INFO: Calculating scaling parameters
2021-05-28 11:06:21.189045 [+] INFO: Framerate: 23.976023976023978
2021-05-28 11:06:21.189045 [+] INFO: Width: 640
2021-05-28 11:06:21.190045 [+] INFO: Height: 480
2021-05-28 11:06:21.190045 [+] INFO: Total number of frames: 2379
2021-05-28 11:06:21.190045 [+] INFO: Output width: 1280
2021-05-28 11:06:21.191044 [+] INFO: Output height: 960
2021-05-28 11:06:21.191044 [+] INFO: Required scale ratio: 2.0
2021-05-28 11:06:21.191044 [+] INFO: Upscaling jobs queue: [2.0]
2021-05-28 11:06:21.192042 [+] INFO: Executing: C:\temp\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -hwaccel auto -y -i C:\temp\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\fff4.mkv -pix_fmt rgb24 -qscale:v 1 e:\temp\tmp406ctulo\extracted_%0d.bmp
2021-05-28 11:06:21.208032 [+] INFO: Main process waiting for subprocesses to exit
2021-05-28 11:07:06.146314 [+] INFO: Subprocess 7316 exited with code 0
[+] INFO: Starting to upscale extracted frames
2021-05-28 11:07:07.020776 [+] INFO: [upscaler] Subprocess 4424 executing: C:\temp\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\anime4kcpp\CLI\Anime4KCPP_CLI\Anime4KCPP_CLI --passes 2 --pushColorCount 2 --strengthColor 0.3 --strengthGradient 1.0 --zoomFactor 2.0 --threads 99 --preFilters 4 --postFilters 40 --GPUMode --CNNMode --HDNLevel 1 --platformID 0 --deviceID 0 --codec mp4v --forceFps 0.0 --input e:\temp\tmp406ctulo --output e:\temp\tmpn6zzs2ix
2021-05-28 11:07:07.118715 [+] INFO: Starting progress monitor
2021-05-28 11:07:07.150694 [+] INFO: Starting upscaled image cleaner
2021-05-28 11:07:07.157691 [+] INFO: Main process waiting for subprocesses to exit
Processing: fff4.mkv (pass 1/1):   0%|                                                        | 0/2379 [01:22<?, ?it/s]2021-05-28 11:08:29.446021 [+] INFO: Subprocess 14736 exited with code 0
Processing: fff4.mkv (pass 1/1):   0%|                                                        | 0/2379 [01:23<?, ?it/s]
Processing: fff4.mkv (pass 1/1):   0%|                                                        | 0/2379 [01:24<?, ?it/s]
2021-05-28 11:08:31.879520 [+] INFO: Killing upscaled image cleaner
[+] INFO: Upscaling completed
[+] INFO: Average processing speed: 27.57657347837965 seconds per frame
[+] INFO: Lanczos downscaling frames
Downscaling: 0it [00:00, ?it/s]
[+] INFO: Converting extracted frames into video
2021-05-28 11:08:34.286037 [+] INFO: Executing: C:\temp\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -r 23.976023976023978 -hwaccel cuda -y -f image2 -i e:\temp\tmpn6zzs2ix\extracted_%d.bmp -vcodec h264_nvenc -pix_fmt yuv420p -crf 17 -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 -tune animation e:\temp\tmpn6zzs2ix\intermediate.mkv
2021-05-28 11:08:34.296031 [+] INFO: Main process waiting for subprocesses to exit
[!] ERROR: Subprocess 11572 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 941, in run
  File "upscaler.py", line 489, in _wait
  File "upscaler.py", line 467, in _wait
subprocess.CalledProcessError: Command '['C:\\temp\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-r', '23.976023976023978', '-hwaccel', 'cuda', '-y', '-f', 'image2', '-i', 'e:\\temp\\tmpn6zzs2ix\\extracted_%d.bmp', '-vcodec', 'h264_nvenc', '-pix_fmt', 'yuv420p', '-crf', '17', '-vf', 'pad=ceil(iw/2)*2:ceil(ih/2)*2', '-tune', 'animation', 'e:\\temp\\tmpn6zzs2ix\\intermediate.mkv']' returned non-zero exit status 1.

![image](https://user-images.githubusercontent.com/84988403/120025246-41d63b00-bfa5-11eb-88bd-38636e44c082.png)
![image](https://user-images.githubusercontent.com/84988403/120025302-561a3800-bfa5-11eb-88ab-574ac1dd83eb.png)

![image](https://user-images.githubusercontent.com/84988403/120025568-b90bcf00-bfa5-11eb-88f0-1126b5c2335e.png)

**Comment by k4yt3x** [comment]
Please upload the error log file. The logs from the terminal does not contain STDOUT output.

**Comment by ArakiSatoshi** [comment]
Nope, not completed. I have the same issue. It's quite simple what's happening when you choose anything except .png:

1. Video2X listens to the `extracted_frame_format: jpg` line in the video2x.yaml file and extracts the files as .**jpg**

`INFO: Executing: C:\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -hwaccel auto -y -i E:\Downloads\Hentai\2022-07-20\[Z] Isekai Harem Monogatari (2020) [DVDRip]\1_edit.mp4 -pix_fmt rgb24 -qscale:v 1 C:\cache-test\cache\tmpjfb4t58d\extracted_%0d.jpg`

\tmpjfb4t58d
- extracted_1.**jpg**
- extracted_2.**jpg**
- extracted_3.**jpg**
- ...

2. Video2X handles this data to Anime4KCPP for it to upscale. It is not specified to Anime4KCPP to use .jpg, so Anime4KCPP outputs the upscaled images as .png

`INFO: [upscaler] Subprocess 260 executing: C:\video2x-4.8.1-win32-full\dependencies\anime4kcpp\CLI\Anime4KCPP_CLI\Anime4KCPP_CLI --passes 2 --pushColorCount 2 --strengthColor 0.3 --strengthGradient 1.0 --zoomFactor 2.0 --threads 16 --preprocessing --postprocessing --preFilters 4 --postFilters 40 --GPUMode --CNNMode --HDN --HDNLevel 1 --platformID 0 --deviceID 0 --codec mp4v --forceFps 0.0 --input C:\cache-test\cache\tmpjfb4t58d --output C:\cache-test\cache\tmp9p39zad0`

\tmp9p39zad0
- extracted_1.**png**
- extracted_2.**png**
- extracted_3.**png**
- ...

3. Video2X handles the upscaled images to ffmpeg as .jpg, having no idea that the images Anime4KCPP produced are .png images

`INFO: Executing: C:\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -r 23.976023976023978 -hwaccel auto -y -f image2 -i C:\cache-test\cache\tmp9p39zad0\extracted_%d.**jpg** -vcodec hevc_amf -pix_fmt yuv420p -crf 12 -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 C:\cache-test\cache\tmp9p39zad0\intermediate.mkv`

4. ffmpeg expectedly returns an error, Video2X handles the generalized error to the user in the frontend.

If you try to run the command above manually (changing tmp9p39zad0 to tmpjfb4t58d since "Preserve Frames" moves the upscaled frames to the initial input folder after an error on this step)

`C:\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -r 23.976023976023978 -hwaccel auto -y -f image2 -i C:\cache-test\cache\tmpjfb4t58d\extracted_%d.jpg -vcodec hevc_amf -pix_fmt yuv420p -crf 12 -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 C:\cache-test\cache\tmp9p39zad0\intermediate.mkv`

 ffmpeg tells you this:

`[image2 @ 00000265a884e600] Could find no file with path 'C:\cache-test\cache\tmpjfb4t58d\extracted_%d.jpg' and index in the range 0-4`
`C:\cache-test\cache\tmpjfb4t58d\extracted_%d.jpg: No such file or directory`

This is expected since there are no .jpg files, those are .png, as Anime4KCPP outputted. Simply changing extracted_%d.jpg to extracted_%d.png:

`C:\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -r 23.976023976023978 -hwaccel auto -y -f image2 -i C:\cache-test\cache\tmpjfb4t58d\extracted_%d.**png** -vcodec hevc_amf -pix_fmt yuv420p -crf 12 -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 C:\cache-test\cache\tmp9p39zad0\intermediate.mkv`

Will produce a nice and clean intermediate.mkv file from the upscaled images.

So the workaround for this would be to upscale something with Anime2x with the frames preserved and then use these upscaled frames to manually combine them with ffmpeg.
However, this does not solve the initial problem. Anime4KCPP upscales the images to .png, this is not what the user wants. In their [CLI documentation](https://github.com/TianZerL/Anime4KCPP/wiki/CLI) they have this:

```
  -o, --output
        File for outputting
         (string [=output.png])
```

Which does exist in the video2x.yaml:

`  #output: null # File for outputting (string [=output.png])`

But it's written in a so confused way even the Video2x's developer just `#` commented it and left the original explanation the way it was.

Full terminal output:

```
[+] INFO: Loading files into processing queue
2022-08-16 01:37:04.682716 [+] INFO: Input path(s): E:\Downloads\Hentai\2022-07-20\[Z] Isekai Harem Monogatari (2020) [DVDRip]\1_edit.mp4
2022-08-16 01:37:04.684716 [+] INFO: File MIME type: video/mp4
[+] INFO: Loaded files into processing queue
2022-08-16 01:37:04.687717 [+] INFO: Input file: E:\Downloads\Hentai\2022-07-20\[Z] Isekai Harem Monogatari (2020) [DVDRip]\1_edit.mp4
[+] INFO: Reading file information
2022-08-16 01:37:04.688717 [+] INFO: Executing: C:\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i E:\Downloads\Hentai\2022-07-20\[Z] Isekai Harem Monogatari (2020) [DVDRip]\1_edit.mp4
2022-08-16 01:37:04.746731 [+] INFO: Creating cache directory C:\cache-test\cache
2022-08-16 01:37:04.747732 [+] INFO: Extracted frames are being saved to: C:\cache-test\cache\tmpjfb4t58d
2022-08-16 01:37:04.747732 [+] INFO: Upscaled frames are being saved to: C:\cache-test\cache\tmp9p39zad0
[+] INFO: Starting upscaling video/GIF
[+] INFO: Getting total number of frames in the file
[+] INFO: Calculating scaling parameters
2022-08-16 01:37:04.748731 [+] INFO: Framerate: 23.976023976023978
2022-08-16 01:37:04.749732 [+] INFO: Width: 854
2022-08-16 01:37:04.749732 [+] INFO: Height: 480
2022-08-16 01:37:04.749732 [+] INFO: Total number of frames: 120
2022-08-16 01:37:04.749732 [+] INFO: Output width: 1708
2022-08-16 01:37:04.749732 [+] INFO: Output height: 960
2022-08-16 01:37:04.749732 [+] INFO: Required scale ratio: 2.0
2022-08-16 01:37:04.750742 [+] INFO: Upscaling jobs queue: [2.0]
2022-08-16 01:37:04.750742 [+] INFO: Executing: C:\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -hwaccel auto -y -i E:\Downloads\Hentai\2022-07-20\[Z] Isekai Harem Monogatari (2020) [DVDRip]\1_edit.mp4 -pix_fmt rgb24 -qscale:v 1 C:\cache-test\cache\tmpjfb4t58d\extracted_%0d.jpg
2022-08-16 01:37:04.752732 [+] INFO: Main process waiting for subprocesses to exit
2022-08-16 01:37:05.358951 [+] INFO: Subprocess 2972 exited with code 0
[+] INFO: Starting to upscale extracted frames
2022-08-16 01:37:05.466966 [+] INFO: [upscaler] Subprocess 260 executing: C:\video2x-4.8.1-win32-full\dependencies\anime4kcpp\CLI\Anime4KCPP_CLI\Anime4KCPP_CLI --passes 2 --pushColorCount 2 --strengthColor 0.3 --strengthGradient 1.0 --zoomFactor 2.0 --threads 16 --preprocessing --postprocessing --preFilters 4 --postFilters 40 --GPUMode --CNNMode --HDN --HDNLevel 1 --platformID 0 --deviceID 0 --codec mp4v --forceFps 0.0 --input C:\cache-test\cache\tmpjfb4t58d --output C:\cache-test\cache\tmp9p39zad0
2022-08-16 01:37:05.469966 [+] INFO: Starting progress monitor
2022-08-16 01:37:05.470966 [+] INFO: Starting upscaled image cleaner
2022-08-16 01:37:05.472966 [+] INFO: Main process waiting for subprocesses to exit
Processing: 1_edit.mp4 (pass 1/1):   0%|                                                       | 0/120 [00:04<?, ?it/s]2022-08-16 01:37:09.643216 [+] INFO: Subprocess 2340 exited with code 0
2022-08-16 01:37:09.753240 [+] INFO: Killing progress monitor
Processing: 1_edit.mp4 (pass 1/1):   0%|                                                       | 0/120 [00:05<?, ?it/s]
2022-08-16 01:37:10.524631 [+] INFO: Killing upscaled image cleaner
[+] INFO: Upscaling completed
[+] INFO: Average processing speed: 19.798722853075237 seconds per frame
[+] INFO: Lanczos downscaling frames
Downscaling: 0it [00:00, ?it/s]
[+] INFO: Converting extracted frames into video
2022-08-16 01:37:11.563963 [+] INFO: Executing: C:\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -r 23.976023976023978 -hwaccel auto -y -f image2 -i C:\cache-test\cache\tmp9p39zad0\extracted_%d.jpg -vcodec hevc_amf -pix_fmt yuv420p -crf 12 -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 C:\cache-test\cache\tmp9p39zad0\intermediate.mkv
2022-08-16 01:37:11.565963 [+] INFO: Main process waiting for subprocesses to exit
[!] ERROR: Subprocess 11572 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 941, in run
  File "upscaler.py", line 489, in _wait
  File "upscaler.py", line 467, in _wait
subprocess.CalledProcessError: Command '['C:\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-r', '23.976023976023978', '-hwaccel', 'auto', '-y', '-f', 'image2', '-i', 'C:\\cache-test\\cache\\tmp9p39zad0\\extracted_%d.jpg', '-vcodec', 'hevc_amf', '-pix_fmt', 'yuv420p', '-crf', '12', '-vf', 'pad=ceil(iw/2)*2:ceil(ih/2)*2', 'C:\\cache-test\\cache\\tmp9p39zad0\\intermediate.mkv']' returned non-zero exit status 1.
```
