### ISSUE TITLE
FileNotFoundError: C:\Users\fezarmon\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan

### ISSUE THREAD

**Issue by feztr** [k4yt3x/video2x#545]
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 633, in run
  File "upscaler.py", line 294, in _check_arguments
FileNotFoundError: C:\Users\fezarmon\AppData\Local\video2x\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan

**Comment by k4yt3x** [comment]
Use the full release.
