### ISSUE TITLE
Cannot upscale video with waifu cpp

### ISSUE THREAD

**Issue by MrAlexEsisteGia** [K4YT3X/video2x#56]
Once it finishes extracting the frames, it just throws an error and freezes

> i5 8600k
> RX 570 4Gb
> Gtx 750 ti 2Gb
> Ram 16Gb

"waifu2x_converter_path": "C:\\Users\\ale54\\AppData\\Local\\video2x\\waifu2x-cpp",
[Video with all the details](https://streamable.com/q7vtu)

```
      handler_name    : VideoHandler
      encoder         : Lavc58.35.100 png
frame= 1970 fps=212 q=-0.0 Lsize=N/A time=00:01:05.66 bitrate=N/A speed=7.05x
video:353350kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2019-03-25 09:19:37.752248 [+] INFO: Executing: C:\Users\ale54\AppData\Local\video2x\ffmpeg-4.1-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i C:\Users\ale54\Desktop\video2x-master\bin\360p.mp4
[+] INFO: Framerate: 30.0
[+] INFO: Starting to upscale extracted images
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 254, in <module>
    upscaler.run()
  File "C:\Users\ale54\Desktop\video2x-master\bin\upscaler.py", line 298, in run
    self._upscale_frames(w2)
  File "C:\Users\ale54\Desktop\video2x-master\bin\upscaler.py", line 152, in _upscale_frames
    w2.upscale(self.extracted_frames, self.upscaled_frames, self.scale_ratio, self.threads)
TypeError: upscale() missing 1 required positional argument: 'threads_exceptions'
[!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using
Upscaling Progress:   0%|                               | 0/1970 [00:00<?, ?it/s]
```

**Comment by K4YT3X** [comment]
This problem has been fixed in the newest update.
