### ISSUE TITLE
In Google Colab: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by DarkHorse-APP2** [k4yt3x/video2x#597]
_shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/video2x/__init__.py", line 25, in <module>
    from .video2x import Video2X
  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 59, in <module>
    from rich import print
  File "/usr/local/lib/python3.8/dist-packages/rich/__init__.py", line 16, in <module>
    _IMPORT_CWD = os.path.abspath(os.getcwd())
FileNotFoundError: [Errno 2] No such file or directory_

How or where do I specify the video file path? what am I doing wrong?

**Comment by DarkHorse-APP2** [comment]
> This is the video's path:
> 
> ![image](https://user-images.githubusercontent.com/21986859/153689888-b37cf7fb-38bf-45c2-bf02-8793eb7c8c2d.png)
> 
> You need to name your input file the same name and put it under the root of your Google Drive:
> 
> ![image](https://user-images.githubusercontent.com/21986859/153689940-2b08282b-a758-4845-a12d-3ef061d71b38.png)

**The file (input.mp4) is under the root of my Google Drive, despite that I still get that message: _[No such file or directory]_**(https://github.com/k4yt3x/video2x/issues/597#)

**Comment by DarkHorse-APP2** [comment]
Yes I already mount my Google Drive

**Comment by k4yt3x** [comment]
Can you create a new code section and run:

```shell
!ls /mnt/gdrive
```

**Comment by DarkHorse-APP2** [comment]
> Can you create a new code section and run:
> 
> ```shell
> !ls /mnt/gdrive
> ```

Everything was fine with the script, but the thing is that I uploaded a file in which it's name was something like this "upscaling videos.mp4" but despite I renamed the file to input.mp4 the script did not recognize or it was not able to look for file named "input.mp4" because Google Drive does not really rename the files  it keeps its real name.

Another thing in step 2 I got this warning twice: **WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv**

Now that the video is been processed I got this another warning: 

**UPSC input.mp4:   0% 1/66029 [00:37<692:40:14, 37.77s/it][swscaler @ 0x55f136ed4000] Warning: data is not aligned! This can lead to a speed loss
UPSC input.mp4:   0% 1/66029 [00:37<694:31:25, 37.87s/it][libx264 @ 0x55f135c31900]**

Seems like the script it's not processing anything at all: 

**UPSC input.mp4:   0% 1/66029 [00:39<720:22:57, 39.28s/it]**

How long should I wait for 43 minutes video to be processed?
