### ISSUE TITLE
Setting env={"AV_LOG_FORCE_COLOR": "TRUE"} in subprocess.Popen calls overwrites system path on Linux

### ISSUE THREAD

**Issue by snixon** [k4yt3x/video2x#627]
Hi there, I was running into some trouble playing around with video2x on an Ubuntu machine today and noticed this.

When subprocess.Popen is used to invoke ffmpeg the env settings on Linux are overwritten, leading to video2k complaining about 'ffmpeg not found' 

I think this may be due to differences in how subprocess.Popen behaves between Windows and Linux, or perhaps changes between versions of python?

I see this note here: https://docs.python.org/3/library/subprocess.html
```
New in version 3.9.

If env is not None, it must be a mapping that defines the environment variables for the new process; these are used instead of the default behavior of inheriting the current process’ environment.
```

FWIW I'm on an ubuntu box running a clean virtualenv of python 3.10.4 with a fresh git clone of the video2x repo.

Removing the env settings from the Popen calls lets the app run normally.

**Comment by snixon** [comment]
Doing a little more poking around:

```env={"AV_LOG_FORCE_COLOR": "TRUE", "PATH": os.environ["PATH"]},```

This works on Linux to keep your color settings in the env for the callouts as well as getting the right path, not sure if this is portable on Windows though.

**Comment by k4yt3x** [comment]
Interesting discovery. I've always been using v2x on my Arch so I should, theoretically work. I'm also on 3.10.4. Where's your FFmpeg and how is it installed?

**Comment by snixon** [comment]
It was a source build from their site and I plunked the trio of binaries in my user path `$HOME/bin/`

To give a little more context, sorry the first comment was probably more conversational than helpful:

PATH Info and ffmpeg versions from the active virtualenv:
```(video2x) steve@kimmy:~/Videos/upscale_tests$ which ffmpeg
/home/steve/bin/ffmpeg

(video2x) steve@kimmy:~/Videos/upscale_tests$ ls -l /home/steve/bin/ff*
-rwxr-xr-x 1 steve steve 22857880 Apr  5 15:16 /home/steve/bin/ffmpeg
-rwxr-xr-x 1 steve steve 22718584 Apr  5 15:16 /home/steve/bin/ffplay
-rwxr-xr-x 1 steve steve 22756024 Apr  5 15:16 /home/steve/bin/ffprobe

(video2x) steve@kimmy:~/Videos/upscale_tests$ ffmpeg

ffmpeg version N-106509-g21ca221068 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/opt/ffmpeg/build --pkg-config-flags=--static --extra-cflags=-I/opt/ffmpeg/build/include --extra-ldflags=-L/opt/ffmpeg/build/lib --extra-libs='-lpthread -lm' --ld=g++ --bindir=/opt/ffmpeg/bin --disable-shared --enable-gpl --enable-gnutls --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libx264 --enable-libx265 --enable-pic --enable-nonfree
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.100 / 59. 25.100
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 30.100 /  8. 30.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

(video2x) steve@kimmy:~/Videos/upscale_tests$ echo $PATH
*/home/steve/bin*:/home/steve/.pyenv/plugins/pyenv-virtualenv/shims:/home/steve/.pyenv/shims:/home/steve/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Running the unmodified version:
```
(video2x) steve@kimmy:~/Videos/upscale_tests$ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json video2x -i title_t01.mkv -o v2x_test2.mkv upscale -w 1920 -h 1080 -a srmd
06:42:14.901693 | INFO     | Video2X 5.0.0-beta5
06:42:14.901838 | INFO     | Copyright (C) 2018-2022 K4YT3X and contributors.
06:42:14.901921 | INFO     | Reading input video information
06:42:14.925177 | INFO     | Starting video decoder
06:42:14.927052 | ERROR    | [Errno 2] No such file or directory: 'ffmpeg'
Traceback (most recent call last):

  File "/home/steve/.pyenv/versions/video2x/bin/video2x", line 8, in <module>
    sys.exit(main())
    |   |    -> <function main at 0x7f49145b0670>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>
> File "/home/steve/.pyenv/versions/3.10.4/envs/video2x/lib/python3.10/site-packages/video2x/video2x.py", line 612, in main
    video2x.upscale(
    |       -> <function Video2X.upscale at 0x7f49145b0550>
    -> <video2x.video2x.Video2X object at 0x7f491473aad0>
  File "/home/steve/.pyenv/versions/3.10.4/envs/video2x/lib/python3.10/site-packages/video2x/video2x.py", line 412, in upscale
    self._run(
    |    -> <function Video2X._run at 0x7f49145b04c0>
    -> <video2x.video2x.Video2X object at 0x7f491473aad0>
  File "/home/steve/.pyenv/versions/3.10.4/envs/video2x/lib/python3.10/site-packages/video2x/video2x.py", line 220, in _run
    self.decoder = VideoDecoder(
    |              -> <class 'video2x.decoder.VideoDecoder'>
    -> <video2x.video2x.Video2X object at 0x7f491473aad0>
  File "/home/steve/.pyenv/versions/3.10.4/envs/video2x/lib/python3.10/site-packages/video2x/decoder.py", line 80, in __init__
    self.decoder = subprocess.Popen(
    |              |          -> <class 'subprocess.Popen'>
    |              -> <module 'subprocess' from '/home/steve/.pyenv/versions/3.10.4/lib/python3.10/subprocess.py'>
    -> <VideoDecoder(Thread-1, initial)>
  File "/home/steve/.pyenv/versions/3.10.4/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    |    |              |     |           |           -> True
    |    |              |     |           -> None
    |    |              |     -> None
    |    |              -> ['ffmpeg', '-r', '23.976023976023978', '-i', PosixPath('title_t01.mkv'), '-map', '0:v', '-f', 'rawvideo', '-pix_fmt', 'rgb24'...
    |    -> <function Popen._execute_child at 0x7f494158e320>
    -> <Popen: returncode: 255 args: ['ffmpeg', '-r', '23.976023976023978', '-i', P...>
  File "/home/steve/.pyenv/versions/3.10.4/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
          |                    |          |        -> 'ffmpeg'
          |                    |          -> 'No such file or directory'
          |                    -> 2
          -> <class 'OSError'>

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```


Quick touch on encoder/decoder.py:
```
(video2x) steve@kimmy:~/Videos/upscale_tests$ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json video2x -i title_t01.mkv -o v2x_test2.mkv upscale -w 1920 -h 1080 -a srmd
06:49:41.470125 | INFO     | Video2X 5.0.0-beta5
06:49:41.470268 | INFO     | Copyright (C) 2018-2022 K4YT3X and contributors.
06:49:41.470359 | INFO     | Reading input video information
06:49:41.492675 | INFO     | Starting video decoder
06:49:41.494805 | INFO     | Starting video encoder
06:49:41.499003 | INFO     | Upscaler process 0 initiating
[0 AMD RADV POLARIS10]  queueC=1[4]  queueG=0[1]  queueT=0[1]
[0 AMD RADV POLARIS10]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD RADV POLARIS10]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 AMD RADV POLARIS10]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
Input #0, matroska,webm, from 'title_t01.mkv':
  Metadata:
    title           : title_t00
    creation_time   : 2022-04-05T21:02:19.000000Z
    ENCODER         : Lavf58.76.100
  Duration: 00:12:50.17, start: 0.000000, bitrate: 1032 kb/s
  Stream #0:0: Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x478 [SAR 32:27 DAR 1280:717], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:12:50.166000000
  Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Surround 5.1
      DURATION        : 00:12:50.090000000
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Output #0, rawvideo, to 'pipe:1':
  Metadata:
    title           : title_t00
    encoder         : Lavf59.20.101
  Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24(pc, gbr/smpte170m/bt709, progressive), 720x478 [SAR 32:27 DAR 1280:717], q=2-31, 198038 kb/s, 23.98
fps, 23.98 tbn (default)
    Metadata:
      DURATION        : 00:12:50.166000000
      encoder         : Lavc59.25.100 rawvideo

Input #0, rawvideo, from 'pipe:0':
  Duration: N/A, start: 0.000000, bitrate: 1193200 kb/s
  Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 1920x1080, 1193200 kb/s, 23.98 tbr, 23.98 tbn
Input #1, matroska,webm, from 'title_t01.mkv':
  Metadata:
    title           : title_t00
    creation_time   : 2022-04-05T21:02:19.000000Z
    ENCODER         : Lavf58.76.100
  Duration: 00:12:50.17, start: 0.000000, bitrate: 1032 kb/s
  Stream #1:0: Video: h264 (Main), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x478 [SAR 32:27 DAR 1280:717], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:12:50.166000000
  Stream #1:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Surround 5.1
      DURATION        : 00:12:50.090000000
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
  Stream #1:1 -> #0:1 (aac (native) -> vorbis (libvorbis))
[libx264 @ 0x55993a27cd00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55993a27cd00] profile High, level 5.1, 4:2:0, 8-bit
[libx264 @ 0x55993a27cd00] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1
ref=16 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=10 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=24 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11
fast_pskip=1 chroma_qp_offset=-2 threads=18 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=8
b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1
crf=17.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, matroska, to 'v2x_test2.mkv':
  Metadata:
    title           : title_t00
    creation_time   : 2022-04-05T21:02:19.000000Z
    comment         : Processed with Video2X
    encoder         : Lavf59.20.101
  Stream #0:0: Video: h264 (H264 / 0x34363248), yuv420p(tv, progressive), 1920x1080, q=2-31, 23.98 fps, 1k tbn
    Metadata:
      encoder         : Lavc59.25.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(eng): Audio: vorbis (oV[0][0] / 0x566F), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Surround 5.1
      DURATION        : 00:12:50.090000000
      encoder         : Lavc59.25.100 libvorbis

Upscaling ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% (59/18466) 10.79 FPS 0:00:06 < 0:28:27
```

**Comment by k4yt3x** [comment]
I've pushed a fix. Try it out.

![image](https://user-images.githubusercontent.com/21986859/162566461-0d81eeef-15c2-46a3-91a4-f6af819d0639.png)

**Comment by snixon** [comment]
This one's working on my end, thanks for the patch!
