### ISSUE TITLE
av_interleaved_write_frame(): I/O error

### ISSUE THREAD

**Issue by StevenNani** [k4yt3x/video2x#640]
This is the error I'm getting, any help? I'm using default(mostly) settings. The only things I changed are output video width and height, driver(Waify2X Caffe), and video extension.

`[image2 @ 000001d2b6775100] Could not open file : C:\Users\STEVEN~1\AppData\Local\Temp\video2x\tmperudznxe\extracted_29334.png
av_interleaved_write_frame(): I/O error
frame=29338 fps= 22 q=-0.0 Lsize=N/A time=00:20:23.47 bitrate=N/A speed=0.897x    
video:47321249kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
[31m[1m[!] ERROR: Subprocess 32792 exited with code 1[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
Cleaning up cache directory: C:\Users\STEVEN~1\AppData\Local\Temp\video2x\tmperudznxe
Cleaning up cache directory: C:\Users\STEVEN~1\AppData\Local\Temp\video2x\tmpv87rvqay
Cleaning up cache directory: C:\Users\STEVEN~1\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 817, in run
  File "upscaler.py", line 489, in _wait
  File "upscaler.py", line 467, in _wait
subprocess.CalledProcessError: Command '['F:\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'I:\\Movie\\New Folder\\[Erai-raws] One Piece - 1015 [1080p][24C55AAD].mkv', '-pix_fmt', 'rgb24', 'C:\\Users\\STEVEN~1\\AppData\\Local\\Temp\\video2x\\tmperudznxe\\extracted_%0d.png']' returned non-zero exit status 1.`
[video2x_error2.log](https://github.com/k4yt3x/video2x/files/8559760/video2x_error2.log)

**Comment by StevenNani** [comment]
[video2x_error2.log](https://github.com/k4yt3x/video2x/files/8559756/video2x_error2.log)

**Comment by StevenNani** [comment]
So, I ran the application with administrator permissions and it seems to be working, will update when it's done processing.
