### ISSUE TITLE
 ERROR    | [Errno 32] Broken pipe -  self.encoder.stdin.write(image.tobytes())

### ISSUE THREAD

**Issue by wesleyorama2** [k4yt3x/video2x#641]
Hey, I have been trying to get this working with podman for a few hours and I am finally breaking down and asking for help. 
It looks like its having a hard time writing to the output file. It create the file as expected, but its always 0 bytes after the crash. I have even gone so far as to set `-R 777` permissions on the folder the video files are in.  

Command I am running to start the container:
```shell
podman run -it --rm --privileged --security-opt=label=disable -v $PWD:/host ghcr.io/k4yt3x/video2x:5.0.0-beta5 -i '02-Andy-Joins-The-PTA.mkv' -o '02-Andy-Joins-The-PTA-waifu.mkv' -p1 upscale -h 1080 -a waifu2x -n3
```
Output from video2x container before the error:
```shell
07:21:48.242734 | INFO     | Video2X 5.0.0-beta5
07:21:48.242873 | INFO     | Copyright (C) 2018-2022 K4YT3X and contributors.
07:21:48.242944 | INFO     | Reading input video information
07:21:48.288957 | INFO     | Starting video decoder
07:21:48.292649 | INFO     | Starting video encoder
07:21:48.297747 | INFO     | Upscaler process 0 initiating
[0 NVIDIA GeForce RTX 2070]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 2070]  bugsbn1=0  bugbilz=118  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 2070]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 2070]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
Input #0, matroska,webm, from '02-Andy-Joins-The-PTA.mkv':
  Metadata:
    encoder         : libmakemkv v1.15.2 (1.3.10/1.5.2) win(x64-release)
    creation_time   : 2020-11-17T02:16:47.000000Z
  Duration: 01:07:11.03, start: 0.000000, bitrate: 3730 kb/s
    Chapter #0:0: start 0.000000, end 468.634833
    Metadata:
      title           : Chapter 01
    Chapter #0:1: start 468.634833, end 846.478967
    Metadata:
      title           : Chapter 02
    Chapter #0:2: start 846.478967, end 1282.881600
    Metadata:
      title           : Chapter 03
    Chapter #0:3: start 1282.881600, end 1324.323000
    Metadata:
      title           : Chapter 04
    Chapter #0:4: start 1324.323000, end 1798.897100
    Metadata:
      title           : Chapter 05
    Chapter #0:5: start 1798.897100, end 2202.333467
    Metadata:
      title           : Chapter 06
    Chapter #0:6: start 2202.333467, end 2638.369067
    Metadata:
      title           : Chapter 07
    Chapter #0:7: start 2638.369067, end 2676.674000
    Metadata:
      title           : Chapter 08
    Chapter #0:8: start 2676.674000, end 3205.268733
    Metadata:
      title           : Chapter 09
    Chapter #0:9: start 3205.268733, end 3561.891667
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 3561.891667, end 3989.318667
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 3989.318667, end 4031.027000
    Metadata:
      title           : Chapter 12
    Stream #0:0(eng): Video: mpeg2video (Main), yuv420p(tv, top first), 720x480 [SAR 8:9 DAR 4:3], 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc
    Metadata:
      BPS-eng         : 3516839
      DURATION-eng    : 01:07:11.027000000
      NUMBER_OF_FRAMES-eng: 120810
      NUMBER_OF_BYTES-eng: 1772059189
      SOURCE_ID-eng   : 0100E0
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:1(eng): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      title           : Stereo
      BPS-eng         : 191998
      DURATION-eng    : 01:07:11.010000000
      NUMBER_OF_FRAMES-eng: 125968
      NUMBER_OF_BYTES-eng: 96743424
      SOURCE_ID-eng   : 0180BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:2(eng): Subtitle: dvd_subtitle, 720x480 (default)
    Metadata:
      BPS-eng         : 5562
      DURATION-eng    : 01:06:17.028844444
      NUMBER_OF_FRAMES-eng: 1018
      NUMBER_OF_BYTES-eng: 2765416
      SOURCE_ID-eng   : 0120BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:3(fre): Subtitle: dvd_subtitle, 720x480
    Metadata:
      BPS-eng         : 5403
      DURATION-eng    : 01:06:17.028844444
      NUMBER_OF_FRAMES-eng: 1026
      NUMBER_OF_BYTES-eng: 2686376
      SOURCE_ID-eng   : 0121BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:4(spa): Subtitle: dvd_subtitle, 720x480
    Metadata:
      BPS-eng         : 5421
      DURATION-eng    : 01:07:03.408511111
      NUMBER_OF_FRAMES-eng: 1061
      NUMBER_OF_BYTES-eng: 2726364
      SOURCE_ID-eng   : 0122BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:5(eng): Subtitle: subrip
    Metadata:
      BPS-eng         : 185
      DURATION-eng    : 01:07:00.314000000
      NUMBER_OF_FRAMES-eng: 1735
      NUMBER_OF_BYTES-eng: 92991
      SOURCE_ID-eng   : 0100E0
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (native) -> rawvideo (native))
Output #0, rawvideo, to 'pipe:1':
  Metadata:
    encoder         : Lavf58.29.100
    Chapter #0:0: start 0.000000, end 468.634833
    Metadata:
      title           : Chapter 01
    Chapter #0:1: start 468.634833, end 846.478967
    Metadata:
      title           : Chapter 02
    Chapter #0:2: start 846.478967, end 1282.881600
    Metadata:
      title           : Chapter 03
    Chapter #0:3: start 1282.881600, end 1324.323000
    Metadata:
      title           : Chapter 04
    Chapter #0:4: start 1324.323000, end 1798.897100
    Metadata:
      title           : Chapter 05
    Chapter #0:5: start 1798.897100, end 2202.333467
    Metadata:
      title           : Chapter 06
    Chapter #0:6: start 2202.333467, end 2638.369067
    Metadata:
      title           : Chapter 07
    Chapter #0:7: start 2638.369067, end 2676.674000
    Metadata:
      title           : Chapter 08
    Chapter #0:8: start 2676.674000, end 3205.268733
    Metadata:
      title           : Chapter 09
    Chapter #0:9: start 3205.268733, end 3561.891667
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 3561.891667, end 3989.318667
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 3989.318667, end 4031.027000
    Metadata:
      title           : Chapter 12
    Stream #0:0(eng): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 720x480 [SAR 8:9 DAR 4:3], q=2-31, 248583 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc
    Metadata:
      BPS-eng         : 3516839
      DURATION-eng    : 01:07:11.027000000
      NUMBER_OF_FRAMES-eng: 120810
      NUMBER_OF_BYTES-eng: 1772059189
      SOURCE_ID-eng   : 0100E0
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      encoder         : Lavc58.54.100 rawvideo

Input #0, rawvideo, from 'pipe:0':
  Duration: N/A, start: 0.000000, bitrate: 559312 kb/s
    Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 1080x720, 559312 kb/s, 29.97 tbr, 29.97 tbn, 29.97 tbc
Input #1, matroska,webm, from '02-Andy-Joins-The-PTA.mkv':
  Metadata:
    encoder         : libmakemkv v1.15.2 (1.3.10/1.5.2) win(x64-release)
    creation_time   : 2020-11-17T02:16:47.000000Z
  Duration: 01:07:11.03, start: 0.000000, bitrate: 3730 kb/s
    Chapter #1:0: start 0.000000, end 468.634833
    Metadata:
      title           : Chapter 01
    Chapter #1:1: start 468.634833, end 846.478967
    Metadata:
      title           : Chapter 02
    Chapter #1:2: start 846.478967, end 1282.881600
    Metadata:
      title           : Chapter 03
    Chapter #1:3: start 1282.881600, end 1324.323000
    Metadata:
      title           : Chapter 04
    Chapter #1:4: start 1324.323000, end 1798.897100
    Metadata:
      title           : Chapter 05
    Chapter #1:5: start 1798.897100, end 2202.333467
    Metadata:
      title           : Chapter 06
    Chapter #1:6: start 2202.333467, end 2638.369067
    Metadata:
      title           : Chapter 07
    Chapter #1:7: start 2638.369067, end 2676.674000
    Metadata:
      title           : Chapter 08
    Chapter #1:8: start 2676.674000, end 3205.268733
    Metadata:
      title           : Chapter 09
    Chapter #1:9: start 3205.268733, end 3561.891667
    Metadata:
      title           : Chapter 10
    Chapter #1:10: start 3561.891667, end 3989.318667
    Metadata:
      title           : Chapter 11
    Chapter #1:11: start 3989.318667, end 4031.027000
    Metadata:
      title           : Chapter 12
    Stream #1:0(eng): Video: mpeg2video (Main), yuv420p(tv, top first), 720x480 [SAR 8:9 DAR 4:3], 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc
    Metadata:
      BPS-eng         : 3516839
      DURATION-eng    : 01:07:11.027000000
      NUMBER_OF_FRAMES-eng: 120810
      NUMBER_OF_BYTES-eng: 1772059189
      SOURCE_ID-eng   : 0100E0
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #1:1(eng): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      title           : Stereo
      BPS-eng         : 191998
      DURATION-eng    : 01:07:11.010000000
      NUMBER_OF_FRAMES-eng: 125968
      NUMBER_OF_BYTES-eng: 96743424
      SOURCE_ID-eng   : 0180BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #1:2(eng): Subtitle: dvd_subtitle, 720x480 (default)
    Metadata:
      BPS-eng         : 5562
      DURATION-eng    : 01:06:17.028844444
      NUMBER_OF_FRAMES-eng: 1018
      NUMBER_OF_BYTES-eng: 2765416
      SOURCE_ID-eng   : 0120BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #1:3(fre): Subtitle: dvd_subtitle, 720x480
    Metadata:
      BPS-eng         : 5403
      DURATION-eng    : 01:06:17.028844444
      NUMBER_OF_FRAMES-eng: 1026
      NUMBER_OF_BYTES-eng: 2686376
      SOURCE_ID-eng   : 0121BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #1:4(spa): Subtitle: dvd_subtitle, 720x480
    Metadata:
      BPS-eng         : 5421
      DURATION-eng    : 01:07:03.408511111
      NUMBER_OF_FRAMES-eng: 1061
      NUMBER_OF_BYTES-eng: 2726364
      SOURCE_ID-eng   : 0122BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #1:5(eng): Subtitle: subrip
    Metadata:
      BPS-eng         : 185
      DURATION-eng    : 01:07:00.314000000
      NUMBER_OF_FRAMES-eng: 1735
      NUMBER_OF_BYTES-eng: 92991
      SOURCE_ID-eng   : 0100E0
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.2 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-17 02:16:47
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
  Stream #1:1 -> #0:1 (ac3 (native) -> vorbis (libvorbis))
  Stream #1:2 -> #0:2 (dvd_subtitle (dvdsub) -> ass (ssa))
  Stream #1:3 -> #0:3 (dvd_subtitle (dvdsub) -> ass (ssa))
  Stream #1:4 -> #0:4 (dvd_subtitle (dvdsub) -> ass (ssa))
  Stream #1:5 -> #0:5 (subrip (srt) -> ass (ssa))
Subtitle encoding currently only possible from text to text or bitmap to bitmap
```

Error from video2x conatiner:
```shell
07:21:49.815000 | ERROR    | [Errno 32] Broken pipe
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7f4a4ca38dc0>
    -> <VideoEncoder(Thread-3, started 139956803020544)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    |    -> <function VideoEncoder.run at 0x7f4a3d246a60>
    -> <VideoEncoder(Thread-3, started 139956803020544)>

> File "/usr/local/lib/python3.8/dist-packages/video2x/encoder.py", line 157, in run
    self.encoder.stdin.write(image.tobytes())
    |    |       |     |     |     -> <function Image.tobytes at 0x7f4a4bf8bb80>
    |    |       |     |     -> <PIL.Image.Image image mode=RGB size=1080x720 at 0x7F4A3D0B0BB0>
    |    |       |     -> <method 'write' of '_io.BufferedWriter' objects>
    |    |       -> <_io.BufferedWriter name=11>
    |    -> <subprocess.Popen object at 0x7f4a3d0b0c10>
    -> <VideoEncoder(Thread-3, started 139956803020544)>

BrokenPipeError: [Errno 32] Broken pipe
07:21:50.303117 | INFO     | Encoder thread exiting
Upscaling ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% (1/120810) ? FPS 0:00:03 < -:--:--
07:21:51.303014 | ERROR    | encoder died unexpectedly
Traceback (most recent call last):

  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           |         |     -> {'__name__': '__main__', '__doc__': '\nCopyright (C) 2018-2022 K4YT3X and contributors.\n\nThis program is free software: you...
           |         -> <code object <module> at 0x7f4a3d0f5f50, file "/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 3>
           -> <function _run_code at 0x7f4a4cae7040>
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': '\nCopyright (C) 2018-2022 K4YT3X and contributors.\n\nThis program is free software: you...
         -> <code object <module> at 0x7f4a3d0f5f50, file "/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 3>

  File "/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 30, in <module>
    sys.exit(main())
    |   |    -> <function main at 0x7f4a3d07c040>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>

  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 612, in main
    video2x.upscale(
    |       -> <function Video2X.upscale at 0x7f4a3d112ee0>
    -> <video2x.video2x.Video2X object at 0x7f4a3d0831c0>

  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 412, in upscale
    self._run(
    |    -> <function Video2X._run at 0x7f4a3d112e50>
    -> <video2x.video2x.Video2X object at 0x7f4a3d0831c0>

> File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 316, in _run
    raise Exception("encoder died unexpectedly")

Exception: encoder died unexpectedly
07:21:51.306282 | INFO     | Stopping processor processes
07:21:51.525870 | INFO     | Upscaler process 0 terminating
07:21:51.614896 | INFO     | Stopping decoder and encoder threads
07:21:51.633326 | DEBUG    | Decoding queue depleted
07:21:51.807425 | INFO     | Decoder thread exiting
07:21:51.807910 | ERROR    | encoder died unexpectedly
Traceback (most recent call last):

  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           |         |     -> {'__name__': '__main__', '__doc__': '\nCopyright (C) 2018-2022 K4YT3X and contributors.\n\nThis program is free software: you...
           |         -> <code object <module> at 0x7f4a3d0f5f50, file "/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 3>
           -> <function _run_code at 0x7f4a4cae7040>
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': '\nCopyright (C) 2018-2022 K4YT3X and contributors.\n\nThis program is free software: you...
         -> <code object <module> at 0x7f4a3d0f5f50, file "/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 3>

  File "/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 30, in <module>
    sys.exit(main())
    |   |    -> <function main at 0x7f4a3d07c040>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>

> File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 612, in main
    video2x.upscale(
    |       -> <function Video2X.upscale at 0x7f4a3d112ee0>
    -> <video2x.video2x.Video2X object at 0x7f4a3d0831c0>

  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 412, in upscale
    self._run(
    |    -> <function Video2X._run at 0x7f4a3d112e50>
    -> <video2x.video2x.Video2X object at 0x7f4a3d0831c0>

  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 375, in _run
    raise exception[0]
          -> [Exception('encoder died unexpectedly')]

  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 316, in _run
    raise Exception("encoder died unexpectedly")

Exception: encoder died unexpectedly
```

**Comment by k4yt3x** [comment]
> Subtitle encoding currently only possible from text to text or bitmap to bitmap

It might be the subtitles that failed to get copied. Try processing the [standard test clip](https://files.k4yt3x.com/Resources/Videos/standard-test.mp4) first just to make sure that the baseline works. If it does, it's a problem with the subtitle. I already have the code in place to disable the copying of subtitles and stuff with a single parameter. I can push an update in the next beta if this turns out to be the case.

**Comment by wesleyorama2** [comment]
its processing the test clip... I had gotten so caught up by the `stdin.write` that I didnt even think to get rid of the subs that I dont even need... 

Sorry for the issue, and thanks for getting back to me so quickly. I am going to sponsor this project because of this.
