### ISSUE TITLE
[Colab] Upscale does not seem to do anything with the file in gdrive, interpolate immediately fails

### ISSUE THREAD

**Issue by Kyle2142** [k4yt3x/video2x#666]
Good day, I tried out the linked Colab script and ran into issues

In both cases I tried
- Spy x Family - 9.mkv (480p, unedited)
- Spy X Family - 9.mp4 (my re-encode of above using handbrake)

<details><summary>Upscale seems to idle after finding the file and printing some info:</summary>

```
12:48:39.651979 | INFO     | Reading input video information
12:48:39.801321 | INFO     | Starting video decoder
12:48:39.822143 | INFO     | Starting video encoder

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/gdrive/MyDrive/Spy X Family - 9.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42iso2avc1mp41
    creation_time   : 2022-06-06T12:34:02.000000Z
    encoder         : HandBrake 1.4.2 2021100300
  Duration: 00:24:10.02, start: 0.000000, bitrate: 1596 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, 
smpte170m/smpte170m/bt709), 848x480 [SAR 160:159 DAR 16:9], 1494 kb/s, 23.98 fps, 23.98 tbr, 
90k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2022-06-06T12:34:02.000000Z
      handler_name    : VideoHandler
    Stream #0:1(jpn): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s 
(default)
    Metadata:
      creation_time   : 2022-06-06T12:34:02.000000Z
      handler_name    : Stereo
    Stream #0:2(eng): Subtitle: mov_text (tx3g / 0x67337874), 853x72, 0 kb/s (default)
    Metadata:
      creation_time   : 2022-06-06T12:34:02.000000Z
      handler_name    : English subs
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Output #0, rawvideo, to 'pipe:1':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42iso2avc1mp41
    encoder         : Lavf57.83.100
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 848x480 [SAR 160:159 DAR
16:9], q=2-31, 234220 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2022-06-06T12:34:02.000000Z
      handler_name    : VideoHandler
      encoder         : Lavc57.107.100 rawvideo

```

</details>

(it never does anything further, I quit it after 30m+)

----

<details><summary>Interpolate fails immediately</summary>

```
Input #0, rawvideo, from 'pipe:0':
  Duration: N/A, start: 0.000000, bitrate: 468441 kb/s
    Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 848x480, 468441 kb/s, 47.95 
tbr, 47.95 tbn, 47.95 tbc

Interpolating ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% (1/69531) ? FPS 0:00:10 < -:--:--

12:48:21.219287 | ERROR    | [Errno 32] Broken pipe
Traceback (most recent call last):

  File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7f80935bd710>
    -> <VideoEncoder(Thread-43, started 140189564438272)>
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
    |    -> <function VideoEncoder.run at 0x7f806f093a70>
    -> <VideoEncoder(Thread-43, started 140189564438272)>

> File "/usr/local/lib/python3.8/dist-packages/video2x/encoder.py", line 157, in run
    self.encoder.stdin.write(image.tobytes())
    |    |       |     |     |     -> <function Image.tobytes at 0x7f808008ba70>
    |    |       |     |     -> <PIL.Image.Image image mode=RGB size=848x480 at 
0x7F806EF2C9D0>
    |    |       |     -> <method 'write' of '_io.BufferedWriter' objects>
    |    |       -> <_io.BufferedWriter name=76>
    |    -> <subprocess.Popen object at 0x7f806ef69550>
    -> <VideoEncoder(Thread-43, started 140189564438272)>

BrokenPipeError: [Errno 32] Broken pipe

12:48:22.173183 | ERROR    | encoder died unexpectedly
Traceback (most recent call last):

  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
                -> ModuleSpec(name='ipykernel_launcher', 
loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f809389c310>, origin='...
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython 
kernel.\n\nThis is separate from the ipykernel pack...
         -> <code object <module> at 0x7f80938784b0, file 
"/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 5>

  File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
    |   -> <bound method Application.launch_instance of <class 
'ipykernel.kernelapp.IPKernelApp'>>
    -> <module 'ipykernel.kernelapp' from 
'/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py'>

  File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in
launch_instance
    app.start()
    |   -> <function IPKernelApp.start at 0x7f808d590b90>
    -> <ipykernel.kernelapp.IPKernelApp object at 0x7f8093a5e290>

  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
    |    |       -> <function BaseAsyncIOLoop.start at 0x7f808d8d9320>
    |    -> <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f808bcfaf50>
    -> <ipykernel.kernelapp.IPKernelApp object at 0x7f8093a5e290>

  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in 
start
    self.asyncio_loop.run_forever()
    |    |            -> <function BaseEventLoop.run_forever at 0x7f808d8e5320>
    |    -> <_UnixSelectorEventLoop running=True closed=False debug=False>
    -> <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f808bcfaf50>

  File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x7f808d8e6dd0>
    -> <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x7f808dd364d0>
    -> <Handle BaseAsyncIOLoop._handle_events(14, 1)>
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle BaseAsyncIOLoop._handle_events(14, 1)>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle BaseAsyncIOLoop._handle_events(14, 1)>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle BaseAsyncIOLoop._handle_events(14, 1)>

  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in 
_handle_events
    handler_func(fileobj, events)
    |            |        -> 1
    |            -> <zmq.Socket(zmq.ROUTER) at 0x7f808cf68bb0>
    -> <function wrap.<locals>.null_wrapper at 0x7f808cf65e60>

  File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in 
null_wrapper
    return fn(*args, **kwargs)
           |   |       -> {}
           |   -> (<zmq.Socket(zmq.ROUTER) at 0x7f808cf68bb0>, 1)
           -> <bound method ZMQStream._handle_events of <zmq.eventloop.zmqstream.ZMQStream 
object at 0x7f808bcfaad0>>

  File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 577, in 
_handle_events
    self._handle_recv()
    |    -> <function ZMQStream._handle_recv at 0x7f808d878d40>
    -> <zmq.eventloop.zmqstream.ZMQStream object at 0x7f808bcfaad0>

  File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 606, in 
_handle_recv
    self._run_callback(callback, msg)
    |    |             |         -> [<zmq.sugar.frame.Frame object at 0x7f806f2a2350>, 
<zmq.sugar.frame.Frame object at 0x7f806f2a2c50>, <zmq.sugar.frame.Frame o...
    |    |             -> <function wrap.<locals>.null_wrapper at 0x7f807fff78c0>
    |    -> <function ZMQStream._run_callback at 0x7f808d878c20>
    -> <zmq.eventloop.zmqstream.ZMQStream object at 0x7f808bcfaad0>

  File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 556, in 
_run_callback
    callback(*args, **kwargs)
    |         |       -> {}
    |         -> ([<zmq.sugar.frame.Frame object at 0x7f806f2a2350>, <zmq.sugar.frame.Frame 
object at 0x7f806f2a2c50>, <zmq.sugar.frame.Frame ...
    -> <function wrap.<locals>.null_wrapper at 0x7f807fff78c0>

  File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in 
null_wrapper
    return fn(*args, **kwargs)
           |   |       -> {}
           |   -> ([<zmq.sugar.frame.Frame object at 0x7f806f2a2350>, <zmq.sugar.frame.Frame 
object at 0x7f806f2a2c50>, <zmq.sugar.frame.Frame ...
           -> <function Kernel.start.<locals>.make_dispatcher.<locals>.dispatcher at 
0x7f80800a19e0>

  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in 
dispatcher
    return self.dispatch_shell(stream, msg)
           |    |              |       -> [<zmq.sugar.frame.Frame object at 0x7f806f2a2350>, 
<zmq.sugar.frame.Frame object at 0x7f806f2a2c50>, <zmq.sugar.frame.Frame o...
           |    |              -> <zmq.eventloop.zmqstream.ZMQStream object at 
0x7f808bcfaad0>
           |    -> <function Kernel.dispatch_shell at 0x7f808d565d40>
           -> <google.colab._kernel.Kernel object at 0x7f808bd01390>

  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in 
dispatch_shell
    handler(stream, idents, msg)
    |       |       |       -> {'header': {'msg_id': '92314fac-a989-440c-e338-eaaf346749d1', 
'username': 'username', 'session': '40cfdbc9-4939-4c77-ead1-3b8...
    |       |       -> [b'40cfdbc9-4939-4c77-ead1-3b87fe262f56']
    |       -> <zmq.eventloop.zmqstream.ZMQStream object at 0x7f808bcfaad0>
    -> <bound method Kernel.execute_request of <google.colab._kernel.Kernel object at 
0x7f808bd01390>>

  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in 
execute_request
    user_expressions, allow_stdin)
    |                 -> True
    -> {}

  File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in 
do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
          |     |        |                   |                     -> False
          |     |        |                   -> True
          |     |        -> '#@title ## Step 4.2 Interpolate\n\n#@markdown Fill in the form 
and run this cell to interpolate a video (currently only 2x i...
          |     -> <function ZMQInteractiveShell.run_cell at 0x7f808d584cb0>
          -> <google.colab._shell.Shell object at 0x7f808bd01450>

  File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
                 |                    |               |       -> {'store_history': True, 
'silent': False}
                 |                    |               -> ('#@title ## Step 4.2 
Interpolate\n\n#@markdown Fill in the form and run this cell to interpolate a video 
(currently only 2x ...
                 |                    -> <google.colab._shell.Shell object at 0x7f808bd01450>
                 -> <class 'ipykernel.zmqshell.ZMQInteractiveShell'>

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, 
in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
                  |                       |                -> <ExecutionResult object at 
7f806ef84610, execution_count=20 error_before_exec=None error_in_exec=None result=None>
                  |                       -> <IPython.core.compilerop.CachingCompiler object 
at 0x7f808d4d54d0>
                  -> 'last_expr'

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2828, 
in run_ast_nodes
    if self.run_code(code, result):
       |    |        |     -> <ExecutionResult object at 7f806ef84610, execution_count=20 
error_before_exec=None error_in_exec=None result=None>
       |    |        -> <code object <module> at 0x7f806efc5390, file 
"<ipython-input-20-45446e35c57a>", line 32>
       |    -> <function InteractiveShell.run_code at 0x7f8091760710>
       -> <google.colab._shell.Shell object at 0x7f808bd01450>

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, 
in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         |         |    |               |    -> {'__name__': '__main__', '__doc__': 
'Automatically created module for IPython interactive environment', '__package__': None, ...
         |         |    |               -> <google.colab._shell.Shell object at 
0x7f808bd01450>
         |         |    -> <property object at 0x7f8091750a10>
         |         -> <google.colab._shell.Shell object at 0x7f808bd01450>
         -> <code object <module> at 0x7f806efc5390, file "<ipython-input-20-45446e35c57a>", 
line 32>

  File "<ipython-input-20-45446e35c57a>", line 37, in <module>
    algorithm,
    -> 'rife'

  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 461, in interpolate
    processes,
    -> 4

> File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 316, in _run
    if not self.encoder.is_alive() and self.encoder.exception is not None:
           |    |       |              |    |       -> BrokenPipeError(32, 'Broken pipe')
           |    |       |              |    -> <VideoEncoder(Thread-43, stopped 
140189564438272)>
           |    |       |              -> <video2x.video2x.Video2X object at 0x7f806ef57210>
           |    |       -> <function Thread.is_alive at 0x7f80935bdb90>
           |    -> <VideoEncoder(Thread-43, stopped 140189564438272)>
           -> <video2x.video2x.Video2X object at 0x7f806ef57210>

Exception: encoder died unexpectedly

12:48:22.246086 | INFO     | Stopping processor processes

12:48:23.256481 | INFO     | Stopping decoder and encoder threads

12:48:23.317708 | DEBUG    | Decoding queue depleted

12:48:23.567554 | INFO     | Decoder thread exiting

---------------------------------------------------------------------------

Exception                                 Traceback (most recent call last)

[<ipython-input-20-45446e35c57a>](https://localhost:8080/#) in <module>()
     35     processes,
     36     threshold,
---> 37     algorithm,
     38 )

2 frames

[/usr/local/lib/python3.8/dist-packages/video2x/video2x.py](https://localhost:8080/#) in interpolate(self, input_path, output_path, processes, threshold, algorithm)
    459             Interpolator,
    460             "interpolate",
--> 461             processes,
    462             (threshold, algorithm),
    463         )

[/usr/local/lib/python3.8/dist-packages/video2x/video2x.py](https://localhost:8080/#) in _run(self, input_path, width, height, total_frames, frame_rate, output_path, output_width, output_height, Processor, mode, processes, processing_settings)
    373 
    374             # raise the error if there is any
--> 375             if len(exception) > 0:
    376                 raise exception[0]
    377 

[/usr/local/lib/python3.8/dist-packages/video2x/video2x.py](https://localhost:8080/#) in _run(self, input_path, width, height, total_frames, frame_rate, output_path, output_width, output_height, Processor, mode, processes, processing_settings)
    314 
    315                 # check encoder health
--> 316                 if not self.encoder.is_alive() and self.encoder.exception is not None:
    317                     raise Exception("encoder died unexpectedly")
    318 

Exception: encoder died unexpectedly
```

</details>

----

I'd be happy to provide the file itself (yes, I tested both in a video player) other than copyright issues... 
Should I try out the sample videos? That'd be a major regression if those don't work

**Comment by Kyle2142** [comment]
@k4yt3x do you have any closing comments?

**Comment by k4yt3x** [comment]
See the homepage of the project. Since the project went through a rewrite, I'll need to make a new colab playbook for it.
