### ISSUE TITLE
Upscaling with waifu2x fails 100% for me. Interpolation also fails 100%. (ColabPro user)

### ISSUE THREAD

**Issue by cbmtrx** [k4yt3x/video2x#673]
I love the idea of having this upscaler in a colab but I'm not having any luck running a video. I'm not sure if others are getting this to run? Running with waifu2x will not complete beyond ~85% and all attempts to run the interpolation fail.

I've had a few different errors I think but on the upscaler I get:

```
  File "<ipython-input-5-4835500e1207>", line 51, in <module>
    algorithm,
    -> 'waifu2x'

  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 429, in upscale
    algorithm,
    -> 'waifu2x'

> File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 308, in _run
    raise Exception("process died unexpectedly")
```

For the Interpolation section I get:

```
Exception                                 Traceback (most recent call last)
[<ipython-input-2-6761e98879a0>](https://localhost:8080/#) in <module>()
     35     processes,
     36     threshold,
---> 37     algorithm,
     38 )

2 frames
[/usr/local/lib/python3.8/dist-packages/video2x/video2x.py](https://localhost:8080/#) in _run(self, input_path, width, height, total_frames, frame_rate, output_path, output_width, output_height, Processor, mode, processes, processing_settings)
    306                 for process in self.processor_processes:
    307                     if not process.is_alive():
--> 308                         raise Exception("process died unexpectedly")
    309 
    310                 # check decoder health

Exception: process died unexpectedly
```

**Comment by cbmtrx** [comment]
Also:

```
[<ipython-input-11-af4ab830ba27>](https://localhost:8080/#) in <module>()
      8 
      9 import pathlib
---> 10 from video2x import Video2X
     11 
     12 video2x = Video2X()

ModuleNotFoundError: No module named 'video2x'
```

Not really sure what's going on.

**Comment by Loc-VD** [comment]
The run time keep restarting when I perform interpolate... ( upscale works fine for me)
![image](https://user-images.githubusercontent.com/99942008/181689853-3dcbdd9a-0513-4524-9478-40d280b8150b.png)

**Comment by k4yt3x** [comment]
The Colab version is just updated to beta6. Please try again and I'll reopen if this is still not fixed.
