### ISSUE TITLE
ImportError: Bindings generation error.

### ISSUE THREAD

**Issue by arch-user-france1** [k4yt3x/video2x#677]
I always get the following ImportError:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/france1/.local/lib/python3.10/site-packages/video2x/__init__.py", line 34, in <module>
    from .video2x import Video2X, main
  File "/home/france1/.local/lib/python3.10/site-packages/video2x/video2x.py", line 53, in <module>
    from cv2 import cv2
ImportError: Bindings generation error. Submodule name should always start with a parent module name. Parent name: cv2.cv2. Submodule name: cv2
```
Why is that?

**Comment by k4yt3x** [comment]
This should be fixed in the newest commits. It's a bug in opencv-python: https://github.com/opencv/opencv-python/issues/676

**Comment by arch-user-france1** [comment]
It's happening again.
```
Traceback (most recent call last):
  File "/home/france1/anaconda3/envs/mmedit/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/france1/anaconda3/envs/mmedit/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/france1/smr-hdd/asdasd/video2x/video2x/video2x.py", line 52, in <module>
    from cv2 import cv2
ImportError: Bindings generation error. Submodule name should always start with a parent module name. Parent name: cv2.cv2. Submodule name: cv2
```

Python version 3.8.13 (anaconda environment), repository is up-to-date
I installed cv2 by pip install `python-opencv`
