### ISSUE TITLE
invalid literal for int() with base 10: '34130\r\n34130'

### ISSUE THREAD

**Issue by aiden04** [k4yt3x/video2x#692]
Idk why this keeps happening, can someone help? the log and a photo of settings will be listed.
logs:
```
[+] INFO: Loading files into processing queue
2022-08-24 21:51:16.871457 [+] INFO: Input path(s): D:\Anime\ReLife (Dubbed)\ReLife - Episode 2 - Copy.mp4
2022-08-24 21:51:16.874458 [+] INFO: File MIME type: video/mp4
[+] INFO: Loaded files into processing queue
2022-08-24 21:51:16.878467 [+] INFO: Input file: D:\Anime\ReLife (Dubbed)\ReLife - Episode 2 - Copy.mp4
[+] INFO: Reading file information
2022-08-24 21:51:16.878467 [+] INFO: Executing: C:\Users\tingt\OneDrive\Desktop\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i D:\Anime\ReLife (Dubbed)\ReLife - Episode 2 - Copy.mp4
2022-08-24 21:51:16.936218 [+] INFO: Creating cache directory C:\Users\tingt\AppData\Local\Temp\video2x
2022-08-24 21:51:16.937218 [+] INFO: Extracted frames are being saved to: C:\Users\tingt\AppData\Local\Temp\video2x\tmpqn_880ah
2022-08-24 21:51:16.938218 [+] INFO: Upscaled frames are being saved to: C:\Users\tingt\AppData\Local\Temp\video2x\tmpbhp3d5u3
[+] INFO: Starting upscaling video/GIF
[+] INFO: Getting total number of frames in the file
2022-08-24 21:51:16.940210 [+] INFO: Executing: C:\Users\tingt\OneDrive\Desktop\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 D:\Anime\ReLife (Dubbed)\ReLife - Episode 2 - Copy.mp4
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 716, in run
  File "wrappers\ffmpeg.py", line 112, in get_number_of_frames
ValueError: invalid literal for int() with base 10: '34130\r\n34130'
```
settings:
![image](https://user-images.githubusercontent.com/9298623/186556505-088edf38-a858-40b4-8ffb-492b73675503.png)

**Comment by k4yt3x** [comment]
dup of #650
