### ISSUE TITLE
Command '['C:\\Users\\Anime\\AppData\\Local\\video2x\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'T:\\Медиа\\Видео\\поднять кадры\\[Yousei-raws] Fate Zero 15 [BDrip 1280x720 x264 Vorbis]-2x-RIFE-RIFE4.0-47.95205fps.mkv', '-pix_fmt', 'rgb24', 'C:\\Users\\Anime\\AppData\\Local\\Temp\\video2x\\tmpr11rhds9\\extracted_%0d.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Aniforka** [k4yt3x/video2x#729]
![image](https://user-images.githubusercontent.com/66227729/192662967-33a05eb5-0f40-4c3a-9437-b6c86806b9e4.png)
[!] ERROR: Subprocess 1728 exited with code 1
[!] ERROR: Subprocess execution ran into an error
[!] WARNING: Terminating all processes
Cleaning up cache directory: C:\Users\Anime\AppData\Local\Temp\video2x\tmpr11rhds9
Cleaning up cache directory: C:\Users\Anime\AppData\Local\Temp\video2x\tmpq44fmv4g
Cleaning up cache directory: C:\Users\Anime\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "p:\Programs\video2x-4.8.1\src\video2x_gui.py", line 105, in run
    self.fn(*self.args, **self.kwargs)
  File "p:\Programs\video2x-4.8.1\src\upscaler.py", line 1022, in run
    raise e
  File "p:\Programs\video2x-4.8.1\src\upscaler.py", line 817, in run
    self._wait()
  File "p:\Programs\video2x-4.8.1\src\upscaler.py", line 489, in _wait
    raise e
  File "p:\Programs\video2x-4.8.1\src\upscaler.py", line 467, in _wait
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['C:\\Users\\Anime\\AppData\\Local\\video2x\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'T:\\Медиа\\Видео\\поднять кадры\\[Yousei-raws] Fate Zero 15 [BDrip 1280x720 x264 Vorbis]-2x-RIFE-RIFE4.0-47.95205fps.mkv', '-pix_fmt', 'rgb24', 'C:\\Users\\Anime\\AppData\\Local\\Temp\\video2x\\tmpr11rhds9\\extracted_%0d.png']' returned non-zero exit status 1.

**Comment by Aniforka** [comment]
![image](https://user-images.githubusercontent.com/66227729/192663334-a413ea23-51df-471b-b398-8f6257afb3a3.png)
version
