### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by NobFox** [k4yt3x/video2x#748]
I hit the following error when doing a simple 2x upscale for an mpg.

Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 716, in run
  File "wrappers\ffmpeg.py", line 112, in get_number_of_frames
ValueError: invalid literal for int() with base 10: ''

**Comment by lolsilent** [comment]
have same error on older computer:
ValueError: invalid literal for int() with base 10:
