### ISSUE TITLE
Command '['C:\\Users\\brady\\Downloads\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-r', '23.976023976023978', '-hwaccel', 'auto', '-y', '-f', 'image2', '-i', 'C:\\Users\\brady\\AppData\\Local\\Temp\\video2x\\tmpc1785e7o\\extracted_%d.png', '-vcodec', 'prores-ks', '-pix_fmt', 'yuv422p', '-crf', '0', '-vf', 'pad=ceil(iw/2)*2:ceil(ih/2)*2', 'C:\\Users\\brady\\AppData\\Local\\Temp\\video2x\\tmpc1785e7o\\intermediate.mkv']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Bradum** [k4yt3x/video2x#781]
Keep getting error when it goes to encode with ffmpeg.

**Comment by Bradum** [comment]
Full log:

`[32m[+] INFO: Loading files into processing queue[0m
[90m2022-11-15 12:10:21.956133 [+] INFO: Input path(s): C:\Users\brady\Downloads\[Yameii] Call of the Night - 01 [English Dub] [WEB-DL 1080p] [7E668632].mkv[0m
[90m2022-11-15 12:10:21.957138 [+] INFO: File MIME type: video/x-matroska[0m
[31m[1m[!] ERROR: FFmpeg or FFprobe cannot be found under the specified path[0m
[31m[1m[!] ERROR: Please check the configuration file settings[0m
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 633, in run
  File "upscaler.py", line 281, in _check_arguments
FileNotFoundError: C:\Program Files\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe
[32m[+] INFO: Loading files into processing queue[0m
[90m2022-11-15 12:12:55.022331 [+] INFO: Input path(s): C:\Users\brady\Downloads\[Yameii] Call of the Night - 01 [English Dub] [WEB-DL 1080p] [7E668632].mkv[0m
[90m2022-11-15 12:12:55.023332 [+] INFO: File MIME type: video/x-matroska[0m
[31m[1m[!] ERROR: FFmpeg or FFprobe cannot be found under the specified path[0m
[31m[1m[!] ERROR: Please check the configuration file settings[0m
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 633, in run
  File "upscaler.py", line 281, in _check_arguments
FileNotFoundError: C:\Users\brady\Downloads\ffmpeg-2022-11-03-git-5ccd4d3060-full_build\bin\ffmpeg.exe
`
