### ISSUE TITLE
Change cache directory

### ISSUE THREAD

**Issue by extradough** [k4yt3x/video2x#83]
Would it be possible to add an argument that would allow you to manually set the cache directory, or if there is a way to do this it should be mentioned in the wiki.

**Comment by k4yt3x** [comment]
It's in the configuration file. I will add a page about the configuration file later.

Change the `video2x_cache_folder` key in `video2x.json`.

**Comment by k4yt3x** [comment]
@extradough see this: https://github.com/K4YT3X/video2x/wiki/Basic-Configuration

**Comment by nostalgicc** [comment]
> @extradough see this: https://github.com/K4YT3X/video2x/wiki/Basic-Configuration

it doesn't work as soon as I change that key in video2x.json:

Traceback (most recent call last):
  File "video2x.py", line 235, in <module>
    config = read_config(args.config)
  File "video2x.py", line 170, in read_config
    config = json.load(raw_config)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 70 column 36 (char 2058)

**Comment by nostalgicc** [comment]
there should be a comment about how to format directories, with // instead of / which triggers escape in python.

Not a programmer, took ages to figure it out...

**Comment by k4yt3x** [comment]
> there should be a comment about how to format directories, with // instead of / which triggers escape in python.

Sure.
