### ISSUE TITLE
AttributeError: 'Interpolator' object has no attribute 'process'

### ISSUE THREAD

**Issue by mocaturtle1** [k4yt3x/video2x#840]
```
mocaturtle@Moca:~/Videos$ sudo docker run --gpus all -it --rm -v $PWD:/host ghcr.io/k4yt3x/video2x:5.0.0-beta6 -i 'Dragonball.Z.-.083.-.1080p.BluRay.x264.DHD.1080.mp4' -o 'dragon ball z ep83.mp4' -p3 interpolate
[sudo] password for mocaturtle:          
17:09:20.645277 | INFO     | Video2X 5.0.0-beta6
17:09:20.645479 | INFO     | Copyright (C) 2018-2022 K4YT3X and contributors.
17:09:20.645594 | INFO     | Reading input video information
17:09:20.861787 | INFO     | Starting video decoder
17:09:20.868483 | INFO     | Starting video encoder
17:09:20.872722 | ERROR    | 'Interpolator' object has no attribute 'process'
Traceback (most recent call last):

  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           |         |     -> {'__name__': '__main__', '__doc__': '\nCopyright 
(C) 2018-2022 K4YT3X and contributors.\n\nThis program is free software: you...
           |         -> <code object <module> at 0x7f7164722870, file 
"/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 3>
           -> <function _run_code at 0x7f717465d040>
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': '\nCopyright (C) 2018-2022
K4YT3X and contributors.\n\nThis program is free software: you...
         -> <code object <module> at 0x7f7164722870, file 
"/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 3>

  File "/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 239, 
in <module>
    sys.exit(main())
    |   |    -> <function main at 0x7f7164720700>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>

> File "/usr/local/lib/python3.8/dist-packages/video2x/__main__.py", line 216, 
in main
    video2x.interpolate(
    |       -> <function Video2X.interpolate at 0x7f71647205e0>
    -> <video2x.video2x.Video2X object at 0x7f71647bce80>

  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 424, in
interpolate
    self._run(
    |    -> <function Video2X._run at 0x7f71647b9d30>
    -> <video2x.video2x.Video2X object at 0x7f71647bce80>

  File "/usr/local/lib/python3.8/dist-packages/video2x/video2x.py", line 208, in
_run
    processor_pool = Pool(processes, processor.process)
                     |    |          -> <Interpolator name='Interpolator-2' 
parent=1 initial>
                     |    -> 3
                     -> <bound method BaseContext.Pool of 
<multiprocessing.context.DefaultContext object at 0x7f7174553670>>

AttributeError: 'Interpolator' object has no attribute 'process'
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 
'Dragonball.Z.-.083.-.1080p.BluRay.x264.DHD.1080.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.10.100
  Duration: 00:24:13.31, start: 0.000000, bitrate: 2327 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080
[SAR 1:1 DAR 16:9], 2194 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, 
fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Output #0, rawvideo, to 'pipe:1':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 1920x1080 
[SAR 1:1 DAR 16:9], q=2-31, 1194393 kb/s, 24 fps, 24 tbn, 24 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 rawvideo
```

**Comment by katurov** [comment]
#765 is first message about it and have a solution to use standalone file (as I suppose without docker) which is reportedly works.
