### ISSUE TITLE
I get this error every time:  Traceback (most recent call last):   File "video2x_gui.py", line 105, in run   File "upscaler.py", line 1022, in run   File "upscaler.py", line 817, in run   File "upscaler.py", line 489, in _wait   File "upscaler.py", line 467, in _wait subprocess.CalledProcessError: Command '['C:\\Users\\Admin\\Desktop\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'D:\\Emil und die Detektive.mp4', '-pix_fmt', 'rgb24', 'C:\\Users\\Admin\\AppData\\Local\\Temp\\video2x\\tmppst2zjvz\\extracted_%0d.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Filipposcmd** [k4yt3x/video2x#864]
### Returned non-zero exit status 1

What can i do about this?
I tried everything, no result.
I think it is because of the ffmpeg package, but I have it installed and upgraded. 
_I'm running on a wildows 11 machine (with pip installed). I tried  running it on a windows 10 vm, that also didn't gave me any result_ 
[video2x_error.log](https://github.com/k4yt3x/video2x/files/11185027/video2x_error.log)

**Comment by arikyo07** [comment]
duplicate: #711
```
[image2 @ 000001df9e042440] Could not open file : C:\Users\Admin\AppData\Local\Temp\video2x\tmppst2zjvz\extracted_21721.png
av_interleaved_write_frame(): I/O error
```
You may not have enough storage space.
