### ISSUE TITLE
input output path type mismatch

### ISSUE THREAD

**Issue by Darth-Gitter** [k4yt3x/video2x#871]
I'm running 32gb of memory, Winblows 11, i5 11,400 CPU, NVIDIA 3060TI.
Any help would be HELLA appreciated.
Trying to upscale 480p digital video tape file to 1080P

Log File:
[32m[+] INFO: Loading files into processing queue[0m
[90m2023-04-25 22:25:19.977760 [+] INFO: Input path(s): D:\00 TEMP\Live Cover_ Iggy Pop - Real Wild Child.mp4[0m
[90m2023-04-25 22:25:19.980597 [+] INFO: File MIME type: video/mp4[0m
[31m[1m[!] ERROR: Input and output path type mismatch[0m
[31m[1m[!] ERROR: Input is single file but output is directory[0m
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 633, in run
  File "upscaler.py", line 239, in _check_arguments
exceptions.ArgumentError: input output path type mismatch

**Comment by Darth-Gitter** [comment]
Note: If I output to the same source folder as the file being worked on: No problem.
This issue arises when i choose a different folder on a different drive.
Is this software _really_ set up like this?! _Forcing me to read and write to the same SSD_ vs using 2 different drives?
That is makes NO sense!
