### ISSUE TITLE
invalid literal for int() with base 10: 'N/A'

### ISSUE THREAD

**Issue by RShand81** [k4yt3x/video2x#922]
Tried to use the GUI upscaler with the default settings and Waifu2X NCNN Vulkan driver to upscale an mp4 video and got the error shown in the title. 

I saved the error file, which contains the following: 

[32m[+] INFO: Loading files into processing queue[0m
[90m2023-07-07 17:14:21.635276 [+] INFO: Input path(s): C:\Users\Rob_S\Videos\Pompeii The Last Day 2.mp4[0m
[90m2023-07-07 17:14:21.637284 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2023-07-07 17:14:21.649941 [+] INFO: Input file: C:\Users\Rob_S\Videos\Pompeii The Last Day 2.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2023-07-07 17:14:21.649941 [+] INFO: Executing: C:\Apps\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i C:\Users\Rob_S\Videos\Pompeii The Last Day 2.mp4[0m
[90m2023-07-07 17:14:24.038151 [+] INFO: Creating cache directory C:\Users\Rob_S\AppData\Local\Temp\video2x[0m
[90m2023-07-07 17:14:24.047201 [+] INFO: Extracted frames are being saved to: C:\Users\Rob_S\AppData\Local\Temp\video2x\tmp83jble8w[0m
[90m2023-07-07 17:14:24.075116 [+] INFO: Upscaled frames are being saved to: C:\Users\Rob_S\AppData\Local\Temp\video2x\tmp0imgshxe[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[90m2023-07-07 17:14:24.131534 [+] INFO: Executing: C:\Apps\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 C:\Users\Rob_S\Videos\Pompeii The Last Day 2.mp4[0m
Cleaning up cache directory: C:\Users\Rob_S\AppData\Local\Temp\video2x\tmp83jble8w
Cleaning up cache directory: C:\Users\Rob_S\AppData\Local\Temp\video2x\tmp0imgshxe
Cleaning up cache directory: C:\Users\Rob_S\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 716, in run
  File "wrappers\ffmpeg.py", line 112, in get_number_of_frames
ValueError: invalid literal for int() with base 10: 'N/A'
[32m[+] INFO: Loading files into processing queue[0m
[90m2023-07-07 17:34:36.041423 [+] INFO: Input path(s): C:\Users\Rob_S\Videos\Pompeii The Last Day 2.mp4[0m
[90m2023-07-07 17:34:36.043428 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2023-07-07 17:34:36.046426 [+] INFO: Input file: C:\Users\Rob_S\Videos\Pompeii The Last Day 2.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2023-07-07 17:34:36.046426 [+] INFO: Executing: C:\Apps\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i C:\Users\Rob_S\Videos\Pompeii The Last Day 2.mp4[0m
[90m2023-07-07 17:34:36.164742 [+] INFO: Creating cache directory C:\Users\Rob_S\AppData\Local\Temp\video2x[0m
[90m2023-07-07 17:34:36.166731 [+] INFO: Extracted frames are being saved to: C:\Users\Rob_S\AppData\Local\Temp\video2x\tmphnniz2vn[0m
[90m2023-07-07 17:34:36.166731 [+] INFO: Upscaled frames are being saved to: C:\Users\Rob_S\AppData\Local\Temp\video2x\tmpslelovqn[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[90m2023-07-07 17:34:36.168731 [+] INFO: Executing: C:\Apps\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 C:\Users\Rob_S\Videos\Pompeii The Last Day 2.mp4[0m
Cleaning up cache directory: C:\Users\Rob_S\AppData\Local\Temp\video2x\tmphnniz2vn
Cleaning up cache directory: C:\Users\Rob_S\AppData\Local\Temp\video2x\tmpslelovqn
Cleaning up cache directory: C:\Users\Rob_S\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 716, in run
  File "wrappers\ffmpeg.py", line 112, in get_number_of_frames
ValueError: invalid literal for int() with base 10: 'N/A'

**Comment by RShand81** [comment]
Just realised how to attach files lol.  Here's the log: 

[video2x_error.log](https://github.com/k4yt3x/video2x/files/11984161/video2x_error.log)
