### ISSUE TITLE
Error when upscaling starts

### ISSUE THREAD

**Issue by Lustrissan** [k4yt3x/video2x#93]
```
Traceback (most recent call last):
  File "video2x.py", line 318, in <module>
    upscaler.run()
  File "D:\Videos\video2x\bin\upscaler.py", line 295, in run
    self._upscale_frames(w2)
  File "D:\Videos\video2x\bin\upscaler.py", line 234, in _upscale_frames
    raise(self.upscaler_exceptions[0])
  File "D:\Videos\video2x\bin\waifu2x_caffe.py", line 83, in upscale
    completed_command = subprocess.run(execute, check=True)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\xxx\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_ratio', '2.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\xxx\\AppData\\Local\\Temp\\video2x\\tmpumzudkty\\0', '--output_path', 'C:\\Users\\xxx\\AppData\\Local\\Temp\\video2x\\tmp8f_9ffzz']' returned non-zero exit status 1.
```

**Comment by k4yt3x** [comment]
This section of the log only tells that waifu2x failed. You'll need to include waifu2x's output for me to be able to see WHY it failed.

**Comment by k4yt3x** [comment]
Issue owner has not responded for over a week. Closing the issue.
Reopen if needed.
