### ISSUE TITLE
ends process after waiting for subprocesses to exit (Error code Command "{"C: Users\Coda\Downloads\video2x-4.8.1-win32-fullvideo2x-4.8.1-win32-full\dependencies\waifu2x-nenn-vulkan\waifu2x-nenn-vulkan', "-n', '24, 5, '2, '-t, '400', "-m' 'C: Users\Coda\Downloads\video2x-4.8.1-win32- full\video2x-4.8.1-win32-full\ dependencies\waifu2x-nenn-vulkan\models-cunet', '-g', 'O', '-j', '1:1:1', 'f, 'png, -i, C \Users\ Coda\ AppData\Local\ Temp\video2x\tmp7ynbbnzj', '-o', 'C: \Users\ Coda\ AppData\Local\ Temp\video2x\tmp7yeywinx'J' returned non-zero exit status 3221225781

### ISSUE THREAD

**Issue by CodaCM** [k4yt3x/video2x#956]
Here's the log file.

[32m[+] INFO: Loading files into processing queue[0m
[90m2023-08-16 17:40:48.745275 [+] INFO: Input path(s): C:\Users\Coda\Downloads\_Resonant Chamber_ - Animusic.com.mp4[0m
[90m2023-08-16 17:40:48.752211 [+] INFO: File MIME type: video/mp4[0m
[32m[+] INFO: Loaded files into processing queue[0m
[90m2023-08-16 17:40:48.762230 [+] INFO: Input file: C:\Users\Coda\Downloads\_Resonant Chamber_ - Animusic.com.mp4[0m
[32m[+] INFO: Reading file information[0m
[90m2023-08-16 17:40:48.764211 [+] INFO: Executing: C:\Users\Coda\Downloads\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffprobe -v quiet -print_format json -show_format -show_streams -i C:\Users\Coda\Downloads\_Resonant Chamber_ - Animusic.com.mp4[0m
[90m2023-08-16 17:40:49.007242 [+] INFO: Extracted frames are being saved to: C:\Users\Coda\AppData\Local\Temp\video2x\tmpdjs3z7da[0m
[90m2023-08-16 17:40:49.010210 [+] INFO: Upscaled frames are being saved to: C:\Users\Coda\AppData\Local\Temp\video2x\tmpy4u_dytr[0m
[32m[+] INFO: Starting upscaling video/GIF[0m
[32m[+] INFO: Getting total number of frames in the file[0m
[32m[+] INFO: Calculating scaling parameters[0m
[90m2023-08-16 17:40:49.012273 [+] INFO: Framerate: 29.97002997002997[0m
[90m2023-08-16 17:40:49.013212 [+] INFO: Width: 640[0m
[90m2023-08-16 17:40:49.013212 [+] INFO: Height: 360[0m
[90m2023-08-16 17:40:49.014268 [+] INFO: Total number of frames: 8007[0m
[90m2023-08-16 17:40:49.014268 [+] INFO: Output width: 1280[0m
[90m2023-08-16 17:40:49.015257 [+] INFO: Output height: 720[0m
[90m2023-08-16 17:40:49.015257 [+] INFO: Required scale ratio: 2.0[0m
[90m2023-08-16 17:40:49.016255 [+] INFO: Upscaling jobs queue: [2][0m
[90m2023-08-16 17:40:49.016255 [+] INFO: Executing: C:\Users\Coda\Downloads\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\ffmpeg\bin\ffmpeg -hwaccel auto -y -i C:\Users\Coda\Downloads\_Resonant Chamber_ - Animusic.com.mp4 -pix_fmt rgb24 C:\Users\Coda\AppData\Local\Temp\video2x\tmpdjs3z7da\extracted_%0d.png[0m
[90m2023-08-16 17:40:49.072217 [+] INFO: Main process waiting for subprocesses to exit[0m
ffmpeg version 4.3.1-2020-11-19-full_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Coda\Downloads\_Resonant Chamber_ - Animusic.com.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2022-03-18T05:27:16.000000Z
  Duration: 00:04:27.17, start: 0.000000, bitrate: 457 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 640x360 [SAR 1:1 DAR 16:9], 325 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2022-03-18T05:27:16.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/17/2022.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2022-03-18T05:27:16.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/17/2022.
[h264 @ 0000014a1fce1840] Using auto hwaccel type dxva2 with new default device.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\Users\Coda\AppData\Local\Temp\video2x\tmpdjs3z7da\extracted_%0d.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.45.100
    Stream #0:0(und): Video: png, rgb24, 640x360 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc (default)
    Metadata:
      creation_time   : 2022-03-18T05:27:16.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/17/2022.
      encoder         : Lavc58.91.100 png
frame=   63 fps=0.0 q=-0.0 size=N/A time=00:00:01.90 bitrate=N/A speed=3.77x    
frame=  121 fps=120 q=-0.0 size=N/A time=00:00:03.77 bitrate=N/A speed=3.73x    
frame=  174 fps=115 q=-0.0 size=N/A time=00:00:05.53 bitrate=N/A speed=3.66x    
frame=  227 fps=112 q=-0.0 size=N/A time=00:00:07.30 bitrate=N/A speed=3.62x    
frame=  276 fps=109 q=-0.0 size=N/A time=00:00:08.94 bitrate=N/A speed=3.54x    
frame=  326 fps=107 q=-0.0 size=N/A time=00:00:10.61 bitrate=N/A speed= 3.5x    
frame=  375 fps=106 q=-0.0 size=N/A time=00:00:12.24 bitrate=N/A speed=3.46x    
frame=  416 fps=103 q=-0.0 size=N/A time=00:00:13.61 bitrate=N/A speed=3.36x    
frame=  455 fps=100 q=-0.0 size=N/A time=00:00:14.91 bitrate=N/A speed=3.28x    
frame=  489 fps= 97 q=-0.0 size=N/A time=00:00:16.04 bitrate=N/A speed=3.18x    
frame=  529 fps= 95 q=-0.0 size=N/A time=00:00:17.38 bitrate=N/A speed=3.13x    
frame=  576 fps= 95 q=-0.0 size=N/A time=00:00:18.95 bitrate=N/A speed=3.13x    
frame=  623 fps= 95 q=-0.0 size=N/A time=00:00:20.52 bitrate=N/A speed=3.13x    
frame=  654 fps= 93 q=-0.0 size=N/A time=00:00:21.55 bitrate=N/A speed=3.05x    
frame=  701 fps= 93 q=-0.0 size=N/A time=00:00:23.12 bitrate=N/A speed=3.06x    
frame=  749 fps= 93 q=-0.0 size=N/A time=00:00:24.72 bitrate=N/A speed=3.06x    
frame=  796 fps= 93 q=-0.0 size=N/A time=00:00:26.29 bitrate=N/A speed=3.07x    
frame=  846 fps= 93 q=-0.0 size=N/A time=00:00:27.96 bitrate=N/A speed=3.07x    
frame=  894 fps= 93 q=-0.0 size=N/A time=00:00:29.56 bitrate=N/A speed=3.08x    
frame=  943 fps= 93 q=-0.0 size=N/A time=00:00:31.19 bitrate=N/A speed=3.08x    
frame=  991 fps= 93 q=-0.0 size=N/A time=00:00:32.79 bitrate=N/A speed=3.09x    
frame= 1040 fps= 93 q=-0.0 size=N/A time=00:00:34.43 bitrate=N/A speed=3.09x    
frame= 1089 fps= 94 q=-0.0 size=N/A time=00:00:36.06 bitrate=N/A speed= 3.1x    
frame= 1132 fps= 93 q=-0.0 size=N/A time=00:00:37.50 bitrate=N/A speed=3.09x    
frame= 1153 fps= 91 q=-0.0 size=N/A time=00:00:38.20 bitrate=N/A speed=3.02x    
frame= 1207 fps= 92 q=-0.0 size=N/A time=00:00:40.00 bitrate=N/A speed=3.04x    
frame= 1264 fps= 93 q=-0.0 size=N/A time=00:00:41.90 bitrate=N/A speed=3.07x    
frame= 1319 fps= 93 q=-0.0 size=N/A time=00:00:43.74 bitrate=N/A speed=3.09x    
frame= 1370 fps= 93 q=-0.0 size=N/A time=00:00:45.44 bitrate=N/A speed= 3.1x    
frame= 1418 fps= 93 q=-0.0 size=N/A time=00:00:47.04 bitrate=N/A speed= 3.1x    
frame= 1464 fps= 93 q=-0.0 size=N/A time=00:00:48.58 bitrate=N/A speed= 3.1x    
frame= 1511 fps= 93 q=-0.0 size=N/A time=00:00:50.15 bitrate=N/A speed= 3.1x    
frame= 1559 fps= 93 q=-0.0 size=N/A time=00:00:51.75 bitrate=N/A speed= 3.1x    
frame= 1610 fps= 94 q=-0.0 size=N/A time=00:00:53.45 bitrate=N/A speed=3.11x    
frame= 1660 fps= 94 q=-0.0 size=N/A time=00:00:55.12 bitrate=N/A speed=3.11x    
frame= 1680 fps= 92 q=-0.0 size=N/A time=00:00:55.78 bitrate=N/A speed=3.06x    
frame= 1733 fps= 93 q=-0.0 size=N/A time=00:00:57.55 bitrate=N/A speed=3.08x    
frame= 1785 fps= 93 q=-0.0 size=N/A time=00:00:59.29 bitrate=N/A speed=3.09x    
frame= 1833 fps= 93 q=-0.0 size=N/A time=00:01:00.89 bitrate=N/A speed=3.09x    
frame= 1879 fps= 93 q=-0.0 size=N/A time=00:01:02.42 bitrate=N/A speed=3.09x    
frame= 1928 fps= 93 q=-0.0 size=N/A time=00:01:04.06 bitrate=N/A speed=3.09x    
frame= 1979 fps= 93 q=-0.0 size=N/A time=00:01:05.76 bitrate=N/A speed= 3.1x    
frame= 2029 fps= 93 q=-0.0 size=N/A time=00:01:07.43 bitrate=N/A speed= 3.1x    
frame= 2080 fps= 94 q=-0.0 size=N/A time=00:01:09.13 bitrate=N/A speed=3.11x    
frame= 2133 fps= 94 q=-0.0 size=N/A time=00:01:10.90 bitrate=N/A speed=3.12x    
frame= 2184 fps= 94 q=-0.0 size=N/A time=00:01:12.60 bitrate=N/A speed=3.12x    
frame= 2214 fps= 93 q=-0.0 size=N/A time=00:01:13.60 bitrate=N/A speed=3.09x    
frame= 2241 fps= 92 q=-0.0 size=N/A time=00:01:14.50 bitrate=N/A speed=3.05x    
frame= 2293 fps= 92 q=-0.0 size=N/A time=00:01:16.24 bitrate=N/A speed=3.05x    
frame= 2340 fps= 92 q=-0.0 size=N/A time=00:01:17.81 bitrate=N/A speed=3.05x    
frame= 2383 fps= 92 q=-0.0 size=N/A time=00:01:19.24 bitrate=N/A speed=3.05x    
frame= 2432 fps= 92 q=-0.0 size=N/A time=00:01:20.88 bitrate=N/A speed=3.05x    
frame= 2481 fps= 92 q=-0.0 size=N/A time=00:01:22.51 bitrate=N/A speed=3.06x    
frame= 2529 fps= 92 q=-0.0 size=N/A time=00:01:24.11 bitrate=N/A speed=3.06x    
frame= 2579 fps= 92 q=-0.0 size=N/A time=00:01:25.78 bitrate=N/A speed=3.06x    
frame= 2614 fps= 92 q=-0.0 size=N/A time=00:01:26.95 bitrate=N/A speed=3.05x    
frame= 2658 fps= 92 q=-0.0 size=N/A time=00:01:28.42 bitrate=N/A speed=3.05x    
frame= 2687 fps= 91 q=-0.0 size=N/A time=00:01:29.38 bitrate=N/A speed=3.03x    
frame= 2737 fps= 91 q=-0.0 size=N/A time=00:01:31.05 bitrate=N/A speed=3.03x    
frame= 2789 fps= 91 q=-0.0 size=N/A time=00:01:32.79 bitrate=N/A speed=3.04x    
frame= 2841 fps= 91 q=-0.0 size=N/A time=00:01:34.52 bitrate=N/A speed=3.04x    
frame= 2893 fps= 92 q=-0.0 size=N/A time=00:01:36.26 bitrate=N/A speed=3.05x    
frame= 2897 fps= 90 q=-0.0 size=N/A time=00:01:36.39 bitrate=N/A speed=2.98x    
frame= 2944 fps= 90 q=-0.0 size=N/A time=00:01:37.96 bitrate=N/A speed=2.99x    
frame= 2989 fps= 90 q=-0.0 size=N/A time=00:01:39.46 bitrate=N/A speed=2.99x    
frame= 3034 fps= 90 q=-0.0 size=N/A time=00:01:40.96 bitrate=N/A speed=2.99x    
frame= 3077 fps= 90 q=-0.0 size=N/A time=00:01:42.40 bitrate=N/A speed=2.98x    
frame= 3112 fps= 89 q=-0.0 size=N/A time=00:01:43.57 bitrate=N/A speed=2.96x    
frame= 3159 fps= 89 q=-0.0 size=N/A time=00:01:45.13 bitrate=N/A speed=2.96x    
frame= 3202 fps= 89 q=-0.0 size=N/A time=00:01:46.57 bitrate=N/A speed=2.96x    
frame= 3248 fps= 89 q=-0.0 size=N/A time=00:01:48.10 bitrate=N/A speed=2.96x    
frame= 3291 fps= 89 q=-0.0 size=N/A time=00:01:49.54 bitrate=N/A speed=2.96x    
frame= 3335 fps= 89 q=-0.0 size=N/A time=00:01:51.01 bitrate=N/A speed=2.96x    
frame= 3380 fps= 89 q=-0.0 size=N/A time=00:01:52.51 bitrate=N/A speed=2.96x    
frame= 3422 fps= 89 q=-0.0 size=N/A time=00:01:53.91 bitrate=N/A speed=2.96x    
frame= 3466 fps= 89 q=-0.0 size=N/A time=00:01:55.38 bitrate=N/A speed=2.95x    
frame= 3506 fps= 89 q=-0.0 size=N/A time=00:01:56.71 bitrate=N/A speed=2.95x    
frame= 3552 fps= 89 q=-0.0 size=N/A time=00:01:58.25 bitrate=N/A speed=2.95x    
frame= 3576 fps= 88 q=-0.0 size=N/A time=00:01:59.05 bitrate=N/A speed=2.93x    
frame= 3624 fps= 88 q=-0.0 size=N/A time=00:02:00.65 bitrate=N/A speed=2.93x    
frame= 3671 fps= 88 q=-0.0 size=N/A time=00:02:02.22 bitrate=N/A speed=2.93x    
frame= 3721 fps= 88 q=-0.0 size=N/A time=00:02:03.89 bitrate=N/A speed=2.94x    
frame= 3768 fps= 88 q=-0.0 size=N/A time=00:02:05.45 bitrate=N/A speed=2.94x    
frame= 3819 fps= 88 q=-0.0 size=N/A time=00:02:07.16 bitrate=N/A speed=2.94x    
frame= 3870 fps= 89 q=-0.0 size=N/A time=00:02:08.86 bitrate=N/A speed=2.95x    
frame= 3917 fps= 89 q=-0.0 size=N/A time=00:02:10.43 bitrate=N/A speed=2.95x    
frame= 3964 fps= 89 q=-0.0 size=N/A time=00:02:11.99 bitrate=N/A speed=2.95x    
frame= 3993 fps= 88 q=-0.0 size=N/A time=00:02:12.96 bitrate=N/A speed=2.94x    
frame= 4044 fps= 88 q=-0.0 size=N/A time=00:02:14.66 bitrate=N/A speed=2.94x    
frame= 4077 fps= 88 q=-0.0 size=N/A time=00:02:15.76 bitrate=N/A speed=2.94x    
frame= 4125 fps= 88 q=-0.0 size=N/A time=00:02:17.37 bitrate=N/A speed=2.94x    
frame= 4172 fps= 88 q=-0.0 size=N/A time=00:02:18.93 bitrate=N/A speed=2.94x    
frame= 4199 fps= 88 q=-0.0 size=N/A time=00:02:19.83 bitrate=N/A speed=2.93x    
frame= 4242 fps= 88 q=-0.0 size=N/A time=00:02:21.27 bitrate=N/A speed=2.92x    
frame= 4289 fps= 88 q=-0.0 size=N/A time=00:02:22.84 bitrate=N/A speed=2.93x    
frame= 4335 fps= 88 q=-0.0 size=N/A time=00:02:24.37 bitrate=N/A speed=2.93x    
frame= 4382 fps= 88 q=-0.0 size=N/A time=00:02:25.94 bitrate=N/A speed=2.93x    
frame= 4430 fps= 88 q=-0.0 size=N/A time=00:02:27.54 bitrate=N/A speed=2.93x    
frame= 4476 fps= 88 q=-0.0 size=N/A time=00:02:29.08 bitrate=N/A speed=2.93x    
frame= 4523 fps= 88 q=-0.0 size=N/A time=00:02:30.65 bitrate=N/A speed=2.93x    
frame= 4543 fps= 88 q=-0.0 size=N/A time=00:02:31.31 bitrate=N/A speed=2.92x    
frame= 4597 fps= 88 q=-0.0 size=N/A time=00:02:33.11 bitrate=N/A speed=2.92x    
frame= 4652 fps= 88 q=-0.0 size=N/A time=00:02:34.95 bitrate=N/A speed=2.93x    
frame= 4703 fps= 88 q=-0.0 size=N/A time=00:02:36.65 bitrate=N/A speed=2.93x    
frame= 4758 fps= 88 q=-0.0 size=N/A time=00:02:38.49 bitrate=N/A speed=2.94x    
frame= 4805 fps= 88 q=-0.0 size=N/A time=00:02:40.05 bitrate=N/A speed=2.94x    
frame= 4854 fps= 88 q=-0.0 size=N/A time=00:02:41.69 bitrate=N/A speed=2.95x    
frame= 4904 fps= 89 q=-0.0 size=N/A time=00:02:43.36 bitrate=N/A speed=2.95x    
frame= 4957 fps= 89 q=-0.0 size=N/A time=00:02:45.13 bitrate=N/A speed=2.95x    
frame= 5002 fps= 89 q=-0.0 size=N/A time=00:02:46.63 bitrate=N/A speed=2.95x    
frame= 5049 fps= 89 q=-0.0 size=N/A time=00:02:48.20 bitrate=N/A speed=2.96x    
frame= 5071 fps= 88 q=-0.0 size=N/A time=00:02:48.93 bitrate=N/A speed=2.94x    
frame= 5119 fps= 88 q=-0.0 size=N/A time=00:02:50.53 bitrate=N/A speed=2.94x    
frame= 5166 fps= 88 q=-0.0 size=N/A time=00:02:52.10 bitrate=N/A speed=2.94x    
frame= 5213 fps= 88 q=-0.0 size=N/A time=00:02:53.67 bitrate=N/A speed=2.94x    
frame= 5258 fps= 87 q=-0.0 size=N/A time=00:02:55.17 bitrate=N/A speed=2.91x    
frame= 5298 fps= 87 q=-0.0 size=N/A time=00:02:56.50 bitrate=N/A speed=2.91x    
frame= 5348 fps= 87 q=-0.0 size=N/A time=00:02:58.17 bitrate=N/A speed=2.91x    
frame= 5393 fps= 87 q=-0.0 size=N/A time=00:02:59.67 bitrate=N/A speed=2.91x    
frame= 5438 fps= 87 q=-0.0 size=N/A time=00:03:01.18 bitrate=N/A speed=2.91x    
frame= 5485 fps= 88 q=-0.0 size=N/A time=00:03:02.74 bitrate=N/A speed=2.92x    
frame= 5517 fps= 87 q=-0.0 size=N/A time=00:03:03.81 bitrate=N/A speed=2.91x    
frame= 5567 fps= 87 q=-0.0 size=N/A time=00:03:05.48 bitrate=N/A speed=2.91x    
frame= 5615 fps= 87 q=-0.0 size=N/A time=00:03:07.08 bitrate=N/A speed=2.91x    
frame= 5664 fps= 88 q=-0.0 size=N/A time=00:03:08.72 bitrate=N/A speed=2.92x    
frame= 5716 fps= 88 q=-0.0 size=N/A time=00:03:10.45 bitrate=N/A speed=2.92x    
frame= 5773 fps= 88 q=-0.0 size=N/A time=00:03:12.35 bitrate=N/A speed=2.93x    
frame= 5829 fps= 88 q=-0.0 size=N/A time=00:03:14.22 bitrate=N/A speed=2.93x    
frame= 5886 fps= 88 q=-0.0 size=N/A time=00:03:16.12 bitrate=N/A speed=2.94x    
frame= 5944 fps= 88 q=-0.0 size=N/A time=00:03:18.06 bitrate=N/A speed=2.95x    
frame= 5998 fps= 89 q=-0.0 size=N/A time=00:03:19.86 bitrate=N/A speed=2.95x    
frame= 6048 fps= 89 q=-0.0 size=N/A time=00:03:21.53 bitrate=N/A speed=2.95x    
frame= 6064 fps= 88 q=-0.0 size=N/A time=00:03:22.06 bitrate=N/A speed=2.93x    
frame= 6115 fps= 88 q=-0.0 size=N/A time=00:03:23.77 bitrate=N/A speed=2.94x    
frame= 6162 fps= 88 q=-0.0 size=N/A time=00:03:25.33 bitrate=N/A speed=2.94x    
frame= 6210 fps= 88 q=-0.0 size=N/A time=00:03:26.94 bitrate=N/A speed=2.94x    
frame= 6258 fps= 88 q=-0.0 size=N/A time=00:03:28.54 bitrate=N/A speed=2.94x    
frame= 6309 fps= 88 q=-0.0 size=N/A time=00:03:30.24 bitrate=N/A speed=2.94x    
frame= 6360 fps= 88 q=-0.0 size=N/A time=00:03:31.94 bitrate=N/A speed=2.95x    
frame= 6409 fps= 89 q=-0.0 size=N/A time=00:03:33.58 bitrate=N/A speed=2.95x    
frame= 6458 fps= 89 q=-0.0 size=N/A time=00:03:35.21 bitrate=N/A speed=2.95x    
frame= 6504 fps= 89 q=-0.0 size=N/A time=00:03:36.74 bitrate=N/A speed=2.95x    
frame= 6549 fps= 89 q=-0.0 size=N/A time=00:03:38.25 bitrate=N/A speed=2.95x    
frame= 6581 fps= 88 q=-0.0 size=N/A time=00:03:39.31 bitrate=N/A speed=2.95x    
frame= 6630 fps= 88 q=-0.0 size=N/A time=00:03:40.95 bitrate=N/A speed=2.95x    
frame= 6678 fps= 89 q=-0.0 size=N/A time=00:03:42.55 bitrate=N/A speed=2.95x    
frame= 6727 fps= 89 q=-0.0 size=N/A time=00:03:44.19 bitrate=N/A speed=2.95x    
frame= 6778 fps= 89 q=-0.0 size=N/A time=00:03:45.89 bitrate=N/A speed=2.95x    
frame= 6825 fps= 89 q=-0.0 size=N/A time=00:03:47.46 bitrate=N/A speed=2.96x    
frame= 6873 fps= 89 q=-0.0 size=N/A time=00:03:49.06 bitrate=N/A speed=2.96x    
frame= 6924 fps= 89 q=-0.0 size=N/A time=00:03:50.76 bitrate=N/A speed=2.96x    
frame= 6974 fps= 89 q=-0.0 size=N/A time=00:03:52.43 bitrate=N/A speed=2.96x    
frame= 7024 fps= 89 q=-0.0 size=N/A time=00:03:54.10 bitrate=N/A speed=2.96x    
frame= 7069 fps= 89 q=-0.0 size=N/A time=00:03:55.60 bitrate=N/A speed=2.96x    
frame= 7078 fps= 87 q=-0.0 size=N/A time=00:03:55.90 bitrate=N/A speed=2.91x    
frame= 7093 fps= 87 q=-0.0 size=N/A time=00:03:56.40 bitrate=N/A speed= 2.9x    
frame= 7145 fps= 87 q=-0.0 size=N/A time=00:03:58.13 bitrate=N/A speed= 2.9x    
frame= 7193 fps= 87 q=-0.0 size=N/A time=00:03:59.73 bitrate=N/A speed= 2.9x    
frame= 7246 fps= 87 q=-0.0 size=N/A time=00:04:01.50 bitrate=N/A speed= 2.9x    
frame= 7298 fps= 87 q=-0.0 size=N/A time=00:04:03.24 bitrate=N/A speed=2.91x    
frame= 7351 fps= 87 q=-0.0 size=N/A time=00:04:05.01 bitrate=N/A speed=2.91x    
frame= 7407 fps= 87 q=-0.0 size=N/A time=00:04:06.87 bitrate=N/A speed=2.91x    
frame= 7461 fps= 87 q=-0.0 size=N/A time=00:04:08.68 bitrate=N/A speed=2.92x    
frame= 7495 fps= 87 q=-0.0 size=N/A time=00:04:09.81 bitrate=N/A speed=2.91x    
frame= 7551 fps= 88 q=-0.0 size=N/A time=00:04:11.68 bitrate=N/A speed=2.92x    
frame= 7605 fps= 88 q=-0.0 size=N/A time=00:04:13.48 bitrate=N/A speed=2.92x    
frame= 7658 fps= 88 q=-0.0 size=N/A time=00:04:15.25 bitrate=N/A speed=2.92x    
frame= 7711 fps= 88 q=-0.0 size=N/A time=00:04:17.02 bitrate=N/A speed=2.93x    
frame= 7763 fps= 88 q=-0.0 size=N/A time=00:04:18.75 bitrate=N/A speed=2.93x    
frame= 7816 fps= 88 q=-0.0 size=N/A time=00:04:20.52 bitrate=N/A speed=2.93x    
frame= 7870 fps= 88 q=-0.0 size=N/A time=00:04:22.32 bitrate=N/A speed=2.94x    
frame= 7929 fps= 88 q=-0.0 size=N/A time=00:04:24.29 bitrate=N/A speed=2.94x    
frame= 7996 fps= 89 q=-0.0 size=N/A time=00:04:26.53 bitrate=N/A speed=2.95x    
frame= 8007 fps= 89 q=-0.0 Lsize=N/A time=00:04:27.16 bitrate=N/A speed=2.95x    
video:2787258kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[90m2023-08-16 17:42:20.265290 [+] INFO: Subprocess 10840 exited with code 0[0m
[32m[+] INFO: Starting to upscale extracted frames[0m
[90m2023-08-16 17:42:21.298202 [+] INFO: [upscaler] Subprocess 2704 executing: C:\Users\Coda\Downloads\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\waifu2x-ncnn-vulkan\waifu2x-ncnn-vulkan -n 2 -s 2 -t 400 -m C:\Users\Coda\Downloads\video2x-4.8.1-win32-full\video2x-4.8.1-win32-full\dependencies\waifu2x-ncnn-vulkan\models-cunet -g 0 -j 1:1:1 -f png -i C:\Users\Coda\AppData\Local\Temp\video2x\tmpdjs3z7da -o C:\Users\Coda\AppData\Local\Temp\video2x\tmpy4u_dytr[0m
[90m2023-08-16 17:42:21.578224 [+] INFO: Starting progress monitor[0m
[90m2023-08-16 17:42:21.582260 [+] INFO: Starting upscaled image cleaner[0m
[90m2023-08-16 17:42:21.585211 [+] INFO: Main process waiting for subprocesses to exit[0m

Processing: _Resonant Chamber_ - Animusic.com.mp4 (pass 1/1):   0%|                                                                                                        | 0/8007 [00:00<?, ?it/s][31m[1m[!] ERROR: Subprocess 16336 exited with code 3221225781[0m
[31m[1m[!] ERROR: Subprocess execution ran into an error[0m
[33m[1m[!] WARNING: Terminating all processes[0m
[90m2023-08-16 17:42:21.708241 [+] INFO: Killing progress monitor[0m

Processing: _Resonant Chamber_ - Animusic.com.mp4 (pass 1/1):   0%|                                                                                                        | 0/8007 [00:01<?, ?it/s]
[90m2023-08-16 17:42:22.629287 [+] INFO: Killing upscaled image cleaner[0m
Cleaning up cache directory: C:\Users\Coda\AppData\Local\Temp\video2x\tmpdjs3z7da
Cleaning up cache directory: C:\Users\Coda\AppData\Local\Temp\video2x\tmpy4u_dytr
Cleaning up cache directory: C:\Users\Coda\AppData\Local\Temp\video2x
Traceback (most recent call last):
  File "video2x_gui.py", line 105, in run
  File "upscaler.py", line 1022, in run
  File "upscaler.py", line 849, in run
  File "upscaler.py", line 416, in _upscale_frames
  File "upscaler.py", line 408, in _upscale_frames
  File "upscaler.py", line 489, in _wait
  File "upscaler.py", line 467, in _wait
subprocess.CalledProcessError: Command '['C:\\Users\\Coda\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\Coda\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\Coda\\AppData\\Local\\Temp\\video2x\\tmpdjs3z7da', '-o', 'C:\\Users\\Coda\\AppData\\Local\\Temp\\video2x\\tmpy4u_dytr']' returned non-zero exit status 3221225781.

**Comment by CodaCM** [comment]
Should I just use the google colab version?

**Comment by CodaCM** [comment]
also are these still being actively replied to?
